// Generated by scripts/generate.py from spec/openapi.json. Do not edit by hand;
// change the spec or the generator and run `npm run generate`.
module.exports = [
  {
    "key": "amazon_products",
    "path": "/v1/amazon/products",
    "method": "GET",
    "platform": "Amazon",
    "noun": "Product",
    "kind": "list",
    "listKey": "products",
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/amazon-products",
    "action": {
      "label": "Search Amazon Products",
      "description": "Searches Amazon products by free-text keyword (or an ASIN) across 24 marketplaces. Each page returns ~16 results with price, rating, Prime status, sales volume, and badges. $0.005 per request after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "query",
        "label": "Search Query",
        "required": true,
        "type": "string",
        "helpText": "Search keyword or a product ASIN (max 500 characters)",
        "placeholder": "phone"
      },
      {
        "key": "page",
        "label": "Page Number",
        "required": false,
        "type": "integer",
        "default": "1",
        "helpText": "Page number, 1-20 (default: 1) (1-20)."
      },
      {
        "key": "country",
        "label": "Country",
        "required": false,
        "type": "string",
        "default": "us",
        "helpText": "Marketplace country code (default: `us`)",
        "choices": {
          "us": "US",
          "au": "AU",
          "br": "BR",
          "ca": "CA",
          "cn": "CN",
          "fr": "FR",
          "de": "DE",
          "in": "IN",
          "it": "IT",
          "mx": "MX",
          "nl": "NL",
          "sg": "SG",
          "es": "ES",
          "tr": "TR",
          "ae": "AE",
          "gb": "GB",
          "jp": "JP",
          "sa": "SA",
          "pl": "PL",
          "se": "SE",
          "be": "BE",
          "eg": "EG",
          "za": "ZA",
          "ie": "IE"
        }
      },
      {
        "key": "sort_by",
        "label": "Sort By",
        "required": false,
        "type": "string",
        "default": "relevance",
        "helpText": "Sort order (default: `relevance`)",
        "choices": {
          "relevance": "Relevance",
          "lowest_price": "Lowest Price",
          "highest_price": "Highest Price",
          "reviews": "Reviews",
          "newest": "Newest",
          "best_sellers": "Best Sellers"
        },
        "placeholder": "reviews"
      },
      {
        "key": "category_id",
        "label": "Category ID",
        "required": false,
        "type": "string",
        "helpText": "Category slug, e.g. `electronics` (see [docs](https://apidirect.io/docs/amazon-categories)) (up to 200 characters).",
        "placeholder": "electronics"
      },
      {
        "key": "category",
        "label": "Category",
        "required": false,
        "type": "string",
        "helpText": "Numeric Amazon category node ID(s) from an Amazon URL's `?node=` parameter, comma-separated"
      },
      {
        "key": "min_price",
        "label": "Minimum Price",
        "required": false,
        "type": "number",
        "helpText": "Minimum price in the marketplace currency"
      },
      {
        "key": "max_price",
        "label": "Maximum Price",
        "required": false,
        "type": "number",
        "helpText": "Maximum price in the marketplace currency",
        "placeholder": "100.0"
      },
      {
        "key": "product_condition",
        "label": "Product Condition",
        "required": false,
        "type": "string",
        "default": "all",
        "helpText": "Product condition filter (default: `all`)",
        "choices": {
          "all": "All",
          "new": "New",
          "used": "Used",
          "renewed": "Renewed",
          "collectible": "Collectible"
        }
      },
      {
        "key": "brand",
        "label": "Brand",
        "required": false,
        "type": "string",
        "helpText": "Brand name(s), comma-separated for multiple (up to 500 characters)."
      },
      {
        "key": "seller_id",
        "label": "Seller ID",
        "required": false,
        "type": "string",
        "helpText": "Only products from specific seller ID(s), comma-separated (up to 500 characters)."
      },
      {
        "key": "is_prime",
        "label": "Prime Only",
        "required": false,
        "type": "boolean",
        "helpText": "Set to `true` to only return products with Prime-eligible offers"
      },
      {
        "key": "deals_and_discounts",
        "label": "Deals and Discounts",
        "required": false,
        "type": "string",
        "default": "none",
        "helpText": "Deals filter (default: `none`)",
        "choices": {
          "none": "None",
          "all_discounts": "All Discounts",
          "todays_deals": "Todays Deals"
        }
      },
      {
        "key": "four_stars_and_up",
        "label": "Four Stars and Up",
        "required": false,
        "type": "boolean",
        "helpText": "Set to `true` to only return products rated 4 stars and up"
      }
    ],
    "sample": {
      "products": [
        {
          "asin": "B0CTW8TXGH",
          "title": "Motorola Moto g Play 2024 | 64GB | 50MP Camera | Sapphire Blue",
          "price": "$39.88",
          "original_price": null,
          "unit_price": null,
          "unit_count": null,
          "currency": "USD",
          "rating": 4.3,
          "num_ratings": 856,
          "url": "https://www.amazon.com/dp/B0CTW8TXGH",
          "photo": "https://m.media-amazon.com/images/I/71fflP-3W4L._AC_UY654_FMwebp_QL65_.jpg",
          "num_offers": 1,
          "minimum_offer_price": "$39.88",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "5K+ bought in past month",
          "delivery": "FREE delivery Mon, Jun 9",
          "availability": null,
          "has_variations": false,
          "badge": "Overall Pick",
          "coupon_text": null
        }
      ],
      "count": 16,
      "total_products": 132661,
      "query": "phone",
      "page": 1
    },
    "outputFields": [
      {
        "key": "products[]asin",
        "label": "Products: ASIN"
      },
      {
        "key": "products[]title",
        "label": "Products: Title"
      },
      {
        "key": "products[]price",
        "label": "Products: Price"
      },
      {
        "key": "products[]original_price",
        "label": "Products: Original Price"
      },
      {
        "key": "products[]unit_price",
        "label": "Products: Unit Price"
      },
      {
        "key": "products[]unit_count",
        "label": "Products: Unit Count"
      },
      {
        "key": "products[]currency",
        "label": "Products: Currency"
      },
      {
        "key": "products[]rating",
        "label": "Products: Rating",
        "type": "number"
      },
      {
        "key": "products[]num_ratings",
        "label": "Products: Num Ratings",
        "type": "number"
      },
      {
        "key": "products[]url",
        "label": "Products: URL"
      },
      {
        "key": "products[]photo",
        "label": "Products: Photo"
      },
      {
        "key": "products[]num_offers",
        "label": "Products: Num Offers",
        "type": "number"
      },
      {
        "key": "products[]minimum_offer_price",
        "label": "Products: Minimum Offer Price"
      },
      {
        "key": "products[]is_best_seller",
        "label": "Products: Is Best Seller",
        "type": "boolean"
      },
      {
        "key": "products[]is_amazon_choice",
        "label": "Products: Is Amazon Choice",
        "type": "boolean"
      },
      {
        "key": "products[]is_prime",
        "label": "Products: Is Prime",
        "type": "boolean"
      },
      {
        "key": "products[]climate_pledge_friendly",
        "label": "Products: Climate Pledge Friendly",
        "type": "boolean"
      },
      {
        "key": "products[]sales_volume",
        "label": "Products: Sales Volume"
      },
      {
        "key": "products[]delivery",
        "label": "Products: Delivery"
      },
      {
        "key": "products[]availability",
        "label": "Products: Availability"
      },
      {
        "key": "products[]has_variations",
        "label": "Products: Has Variations",
        "type": "boolean"
      },
      {
        "key": "products[]badge",
        "label": "Products: Badge"
      },
      {
        "key": "products[]coupon_text",
        "label": "Products: Coupon Text"
      },
      {
        "key": "count",
        "label": "Count",
        "type": "number"
      },
      {
        "key": "total_products",
        "label": "Total Products",
        "type": "number"
      },
      {
        "key": "query",
        "label": "Query"
      },
      {
        "key": "page",
        "label": "Page",
        "type": "number"
      }
    ],
    "trigger": {
      "label": "New Amazon Product Matching Search",
      "description": "Triggers when a new product matches your Amazon search. Each check runs Search Amazon Products ($0.005 per request after the free tier (50 requests/month)).",
      "inputFields": [
        {
          "key": "query",
          "label": "Search Query",
          "required": true,
          "type": "string",
          "helpText": "Search keyword or a product ASIN (max 500 characters)",
          "placeholder": "phone"
        },
        {
          "key": "page",
          "label": "Page Number",
          "required": false,
          "type": "integer",
          "default": "1",
          "helpText": "Page number, 1-20 (default: 1) (1-20)."
        },
        {
          "key": "country",
          "label": "Country",
          "required": false,
          "type": "string",
          "default": "us",
          "helpText": "Marketplace country code (default: `us`)",
          "choices": {
            "us": "US",
            "au": "AU",
            "br": "BR",
            "ca": "CA",
            "cn": "CN",
            "fr": "FR",
            "de": "DE",
            "in": "IN",
            "it": "IT",
            "mx": "MX",
            "nl": "NL",
            "sg": "SG",
            "es": "ES",
            "tr": "TR",
            "ae": "AE",
            "gb": "GB",
            "jp": "JP",
            "sa": "SA",
            "pl": "PL",
            "se": "SE",
            "be": "BE",
            "eg": "EG",
            "za": "ZA",
            "ie": "IE"
          }
        },
        {
          "key": "sort_by",
          "label": "Sort By",
          "required": false,
          "type": "string",
          "default": "relevance",
          "helpText": "Sort order (default: `relevance`)",
          "choices": {
            "relevance": "Relevance",
            "lowest_price": "Lowest Price",
            "highest_price": "Highest Price",
            "reviews": "Reviews",
            "newest": "Newest",
            "best_sellers": "Best Sellers"
          },
          "placeholder": "reviews"
        },
        {
          "key": "category_id",
          "label": "Category ID",
          "required": false,
          "type": "string",
          "helpText": "Category slug, e.g. `electronics` (see [docs](https://apidirect.io/docs/amazon-categories)) (up to 200 characters).",
          "placeholder": "electronics"
        },
        {
          "key": "category",
          "label": "Category",
          "required": false,
          "type": "string",
          "helpText": "Numeric Amazon category node ID(s) from an Amazon URL's `?node=` parameter, comma-separated"
        },
        {
          "key": "min_price",
          "label": "Minimum Price",
          "required": false,
          "type": "number",
          "helpText": "Minimum price in the marketplace currency"
        },
        {
          "key": "max_price",
          "label": "Maximum Price",
          "required": false,
          "type": "number",
          "helpText": "Maximum price in the marketplace currency",
          "placeholder": "100.0"
        },
        {
          "key": "product_condition",
          "label": "Product Condition",
          "required": false,
          "type": "string",
          "default": "all",
          "helpText": "Product condition filter (default: `all`)",
          "choices": {
            "all": "All",
            "new": "New",
            "used": "Used",
            "renewed": "Renewed",
            "collectible": "Collectible"
          }
        },
        {
          "key": "brand",
          "label": "Brand",
          "required": false,
          "type": "string",
          "helpText": "Brand name(s), comma-separated for multiple (up to 500 characters)."
        },
        {
          "key": "seller_id",
          "label": "Seller ID",
          "required": false,
          "type": "string",
          "helpText": "Only products from specific seller ID(s), comma-separated (up to 500 characters)."
        },
        {
          "key": "is_prime",
          "label": "Prime Only",
          "required": false,
          "type": "boolean",
          "helpText": "Set to `true` to only return products with Prime-eligible offers"
        },
        {
          "key": "deals_and_discounts",
          "label": "Deals and Discounts",
          "required": false,
          "type": "string",
          "default": "none",
          "helpText": "Deals filter (default: `none`)",
          "choices": {
            "none": "None",
            "all_discounts": "All Discounts",
            "todays_deals": "Todays Deals"
          }
        },
        {
          "key": "four_stars_and_up",
          "label": "Four Stars and Up",
          "required": false,
          "type": "boolean",
          "helpText": "Set to `true` to only return products rated 4 stars and up"
        }
      ],
      "sample": {
        "id": "B0CTW8TXGH",
        "asin": "B0CTW8TXGH",
        "title": "Motorola Moto g Play 2024 | 64GB | 50MP Camera | Sapphire Blue",
        "price": "$39.88",
        "original_price": null,
        "unit_price": null,
        "unit_count": null,
        "currency": "USD",
        "rating": 4.3,
        "num_ratings": 856,
        "url": "https://www.amazon.com/dp/B0CTW8TXGH",
        "photo": "https://m.media-amazon.com/images/I/71fflP-3W4L._AC_UY654_FMwebp_QL65_.jpg",
        "num_offers": 1,
        "minimum_offer_price": "$39.88",
        "is_best_seller": false,
        "is_amazon_choice": true,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "5K+ bought in past month",
        "delivery": "FREE delivery Mon, Jun 9",
        "availability": null,
        "has_variations": false,
        "badge": "Overall Pick",
        "coupon_text": null
      },
      "outputFields": [
        {
          "key": "id",
          "label": "ID",
          "primary": true
        },
        {
          "key": "asin",
          "label": "ASIN"
        },
        {
          "key": "title",
          "label": "Title"
        },
        {
          "key": "price",
          "label": "Price"
        },
        {
          "key": "original_price",
          "label": "Original Price"
        },
        {
          "key": "unit_price",
          "label": "Unit Price"
        },
        {
          "key": "unit_count",
          "label": "Unit Count"
        },
        {
          "key": "currency",
          "label": "Currency"
        },
        {
          "key": "rating",
          "label": "Rating",
          "type": "number"
        },
        {
          "key": "num_ratings",
          "label": "Num Ratings",
          "type": "number"
        },
        {
          "key": "url",
          "label": "URL"
        },
        {
          "key": "photo",
          "label": "Photo"
        },
        {
          "key": "num_offers",
          "label": "Num Offers",
          "type": "number"
        },
        {
          "key": "minimum_offer_price",
          "label": "Minimum Offer Price"
        },
        {
          "key": "is_best_seller",
          "label": "Is Best Seller",
          "type": "boolean"
        },
        {
          "key": "is_amazon_choice",
          "label": "Is Amazon Choice",
          "type": "boolean"
        },
        {
          "key": "is_prime",
          "label": "Is Prime",
          "type": "boolean"
        },
        {
          "key": "climate_pledge_friendly",
          "label": "Climate Pledge Friendly",
          "type": "boolean"
        },
        {
          "key": "sales_volume",
          "label": "Sales Volume"
        },
        {
          "key": "delivery",
          "label": "Delivery"
        },
        {
          "key": "availability",
          "label": "Availability"
        },
        {
          "key": "has_variations",
          "label": "Has Variations",
          "type": "boolean"
        },
        {
          "key": "badge",
          "label": "Badge"
        },
        {
          "key": "coupon_text",
          "label": "Coupon Text"
        }
      ]
    }
  },
  {
    "key": "amazon_product",
    "path": "/v1/amazon/product",
    "method": "GET",
    "platform": "Amazon",
    "noun": "Product",
    "kind": "detail",
    "listKey": null,
    "unwrapKey": "product",
    "docs": "https://apidirect.io/docs/amazon-product-details",
    "action": {
      "label": "Find Amazon Product",
      "description": "Gets full details for an Amazon product by its 10-character ASIN — pricing, buy box with seller ID, availability, photos, videos, spec tables, rating breakdown per star, and top reviews. $0.005 per request after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "asin",
        "label": "ASIN",
        "required": true,
        "type": "string",
        "helpText": "10-character Amazon ASIN (e.g. `B07ZPKN6YR`), as returned by Product Search",
        "placeholder": "B07ZPKN6YR"
      },
      {
        "key": "country",
        "label": "Country",
        "required": false,
        "type": "string",
        "default": "us",
        "helpText": "Marketplace country code (default: `us`)",
        "choices": {
          "us": "US",
          "au": "AU",
          "br": "BR",
          "ca": "CA",
          "cn": "CN",
          "fr": "FR",
          "de": "DE",
          "in": "IN",
          "it": "IT",
          "mx": "MX",
          "nl": "NL",
          "sg": "SG",
          "es": "ES",
          "tr": "TR",
          "ae": "AE",
          "gb": "GB",
          "jp": "JP",
          "sa": "SA",
          "pl": "PL",
          "se": "SE",
          "be": "BE",
          "eg": "EG",
          "za": "ZA",
          "ie": "IE"
        }
      }
    ],
    "sample": {
      "asin": "B07ZPKN6YR",
      "title": "Apple iPhone 11, 64GB, Black - Unlocked (Renewed)",
      "item_highlight": "Fully unlocked, renewed and inspected, 64GB storage",
      "price": "$190.00",
      "original_price": "$249.00",
      "delivery_price": null,
      "minimum_order_quantity": null,
      "currency": "USD",
      "country": "US",
      "byline": "Visit the Amazon Renewed Store",
      "byline_link": "https://www.amazon.com/Amazon-Renewed/b/...",
      "rating": 4.2,
      "num_ratings": 57539,
      "url": "https://www.amazon.com/dp/B07ZPKN6YR",
      "slug": "Apple-iPhone-11-64GB-Black",
      "photo": "https://m.media-amazon.com/images/I/514k7uOBMwL._AC_SL1000_.jpg",
      "photos": [
        "https://m.media-amazon.com/images/I/514k7uOBMwL._AC_SL1000_.jpg"
      ],
      "videos": [],
      "user_uploaded_videos": [],
      "has_video": false,
      "num_offers": 47,
      "availability": "In Stock",
      "condition": "Buy New",
      "is_best_seller": false,
      "is_amazon_choice": false,
      "is_prime": false,
      "climate_pledge_friendly": false,
      "sales_volume": "2K+ bought in past month",
      "delivery": "FREE delivery Friday, June 6",
      "main_buy_box": {
        "title": "Buy New",
        "price": "$190.00",
        "seller": "iBlueberry",
        "seller_id": "A1B2C3D4E5F6G7",
        "seller_link": "https://www.amazon.com/gp/help/seller/at-a-glance.html/...",
        "return_policy": "30-day refund/replacement"
      },
      "buy_boxes": [
        {
          "title": "Buy New",
          "price": "$190.00"
        }
      ],
      "about": [
        "This phone is unlocked and compatible with any carrier of choice."
      ],
      "description": "The iPhone 11 features a 6.1-inch Liquid Retina display...",
      "product_information": {
        "Screen Size": "6.1 inches",
        "Color": "Black"
      },
      "product_details": {
        "Brand": "Apple",
        "Model Name": "iPhone 11"
      },
      "rating_distribution": {
        "1": "12",
        "2": "3",
        "3": "5",
        "4": "12",
        "5": "68"
      },
      "top_reviews": [
        {
          "review_id": "R3PXA2ZA1TUMCE",
          "title": "Five stars !! It's worth the money !!",
          "review_text": "I had my phone for a couple of years... it was a perfect phone.",
          "rating": 5.0,
          "review_link": "https://www.amazon.com/gp/customer-reviews/R3PXA2ZA1TUMCE",
          "review_date": "Reviewed in the United States on October 30, 2025",
          "author_id": "AHDG3DAH75Y6DILGMFNKDAXGX7YQ",
          "author_name": "Dorothyann",
          "author_avatar": "https://m.media-amazon.com/images/S/amazon-avatars-global/default.png",
          "images": [],
          "video": null,
          "is_verified_purchase": true,
          "helpful_votes": "12 people found this helpful",
          "product_variant": {
            "Size": "64GB",
            "Color": "Purple"
          },
          "is_vine": false
        }
      ]
    },
    "outputFields": [
      {
        "key": "asin",
        "label": "ASIN"
      },
      {
        "key": "title",
        "label": "Title"
      },
      {
        "key": "item_highlight",
        "label": "Item Highlight"
      },
      {
        "key": "price",
        "label": "Price"
      },
      {
        "key": "original_price",
        "label": "Original Price"
      },
      {
        "key": "delivery_price",
        "label": "Delivery Price"
      },
      {
        "key": "minimum_order_quantity",
        "label": "Minimum Order Quantity"
      },
      {
        "key": "currency",
        "label": "Currency"
      },
      {
        "key": "country",
        "label": "Country"
      },
      {
        "key": "byline",
        "label": "Byline"
      },
      {
        "key": "byline_link",
        "label": "Byline Link"
      },
      {
        "key": "rating",
        "label": "Rating",
        "type": "number"
      },
      {
        "key": "num_ratings",
        "label": "Num Ratings",
        "type": "number"
      },
      {
        "key": "url",
        "label": "URL"
      },
      {
        "key": "slug",
        "label": "Slug"
      },
      {
        "key": "photo",
        "label": "Photo"
      },
      {
        "key": "photos",
        "label": "Photos",
        "list": true
      },
      {
        "key": "videos",
        "label": "Videos",
        "list": true
      },
      {
        "key": "user_uploaded_videos",
        "label": "User Uploaded Videos",
        "list": true
      },
      {
        "key": "has_video",
        "label": "Has Video",
        "type": "boolean"
      },
      {
        "key": "num_offers",
        "label": "Num Offers",
        "type": "number"
      },
      {
        "key": "availability",
        "label": "Availability"
      },
      {
        "key": "condition",
        "label": "Condition"
      },
      {
        "key": "is_best_seller",
        "label": "Is Best Seller",
        "type": "boolean"
      },
      {
        "key": "is_amazon_choice",
        "label": "Is Amazon Choice",
        "type": "boolean"
      },
      {
        "key": "is_prime",
        "label": "Is Prime",
        "type": "boolean"
      },
      {
        "key": "climate_pledge_friendly",
        "label": "Climate Pledge Friendly",
        "type": "boolean"
      },
      {
        "key": "sales_volume",
        "label": "Sales Volume"
      },
      {
        "key": "delivery",
        "label": "Delivery"
      },
      {
        "key": "main_buy_box__title",
        "label": "Main Buy Box Title"
      },
      {
        "key": "main_buy_box__price",
        "label": "Main Buy Box Price"
      },
      {
        "key": "main_buy_box__seller",
        "label": "Main Buy Box Seller"
      },
      {
        "key": "main_buy_box__seller_id",
        "label": "Main Buy Box Seller ID"
      },
      {
        "key": "main_buy_box__seller_link",
        "label": "Main Buy Box Seller Link"
      },
      {
        "key": "main_buy_box__return_policy",
        "label": "Main Buy Box Return Policy"
      },
      {
        "key": "buy_boxes[]title",
        "label": "Buy Boxes: Title"
      },
      {
        "key": "buy_boxes[]price",
        "label": "Buy Boxes: Price"
      },
      {
        "key": "about",
        "label": "About",
        "list": true
      },
      {
        "key": "description",
        "label": "Description"
      },
      {
        "key": "product_information__Screen Size",
        "label": "Product Information Screen Size"
      },
      {
        "key": "product_information__Color",
        "label": "Product Information Color"
      },
      {
        "key": "product_details__Brand",
        "label": "Product Details Brand"
      },
      {
        "key": "product_details__Model Name",
        "label": "Product Details Model Name"
      },
      {
        "key": "rating_distribution__1",
        "label": "Rating Distribution 1"
      },
      {
        "key": "rating_distribution__2",
        "label": "Rating Distribution 2"
      },
      {
        "key": "rating_distribution__3",
        "label": "Rating Distribution 3"
      },
      {
        "key": "rating_distribution__4",
        "label": "Rating Distribution 4"
      },
      {
        "key": "rating_distribution__5",
        "label": "Rating Distribution 5"
      },
      {
        "key": "top_reviews[]review_id",
        "label": "Top Reviews: Review ID"
      },
      {
        "key": "top_reviews[]title",
        "label": "Top Reviews: Title"
      },
      {
        "key": "top_reviews[]review_text",
        "label": "Top Reviews: Review Text"
      },
      {
        "key": "top_reviews[]rating",
        "label": "Top Reviews: Rating",
        "type": "number"
      },
      {
        "key": "top_reviews[]review_link",
        "label": "Top Reviews: Review Link"
      },
      {
        "key": "top_reviews[]review_date",
        "label": "Top Reviews: Review Date"
      },
      {
        "key": "top_reviews[]author_id",
        "label": "Top Reviews: Author ID"
      },
      {
        "key": "top_reviews[]author_name",
        "label": "Top Reviews: Author Name"
      },
      {
        "key": "top_reviews[]author_avatar",
        "label": "Top Reviews: Author Avatar"
      },
      {
        "key": "top_reviews[]images",
        "label": "Top Reviews: Images",
        "list": true
      },
      {
        "key": "top_reviews[]video",
        "label": "Top Reviews: Video"
      },
      {
        "key": "top_reviews[]is_verified_purchase",
        "label": "Top Reviews: Is Verified Purchase",
        "type": "boolean"
      },
      {
        "key": "top_reviews[]helpful_votes",
        "label": "Top Reviews: Helpful Votes"
      },
      {
        "key": "top_reviews[]product_variant__Size",
        "label": "Product Variant Size"
      },
      {
        "key": "top_reviews[]product_variant__Color",
        "label": "Product Variant Color"
      },
      {
        "key": "top_reviews[]is_vine",
        "label": "Top Reviews: Is Vine",
        "type": "boolean"
      }
    ],
    "trigger": null
  },
  {
    "key": "amazon_seller",
    "path": "/v1/amazon/seller",
    "method": "GET",
    "platform": "Amazon",
    "noun": "Seller",
    "kind": "detail",
    "listKey": null,
    "unwrapKey": "seller",
    "docs": "https://apidirect.io/docs/amazon-seller-profile",
    "action": {
      "label": "Find Amazon Seller",
      "description": "Gets an Amazon seller's profile by seller ID — name, logo, about text, registered business name and address, average rating, and feedback percentages over 30 days, 90 days, 12 months, and lifetime. $0.005 per request after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "seller_id",
        "label": "Seller ID",
        "required": true,
        "type": "string",
        "helpText": "Amazon seller ID (e.g. `A2L77EE7U53NWQ`), from a product's `main_buy_box.seller_id` (up to 100 characters).",
        "placeholder": "A2L77EE7U53NWQ"
      },
      {
        "key": "country",
        "label": "Country",
        "required": false,
        "type": "string",
        "default": "us",
        "helpText": "Marketplace country code (default: `us`)",
        "choices": {
          "us": "US",
          "au": "AU",
          "br": "BR",
          "ca": "CA",
          "cn": "CN",
          "fr": "FR",
          "de": "DE",
          "in": "IN",
          "it": "IT",
          "mx": "MX",
          "nl": "NL",
          "sg": "SG",
          "es": "ES",
          "tr": "TR",
          "ae": "AE",
          "gb": "GB",
          "jp": "JP",
          "sa": "SA",
          "pl": "PL",
          "se": "SE",
          "be": "BE",
          "eg": "EG",
          "za": "ZA",
          "ie": "IE"
        }
      }
    ],
    "sample": {
      "seller_id": "A2L77EE7U53NWQ",
      "name": "Amazon Resale",
      "seller_link": "https://www.amazon.com/sp?seller=A2L77EE7U53NWQ",
      "store_link": "https://www.amazon.com/s?ie=UTF8&marketplaceID=ATVPDKIKX0DER&me=A2L77EE7U53NWQ",
      "logo": "https://m.media-amazon.com/images/I/01RxYGCdstL.gif",
      "about": "Quality used, pre-owned, or open box products, tested and inspected.",
      "business_name": "Amazon.com Services LLC",
      "business_address": "410 Terry Ave N Seattle WA 98109 US",
      "rating": 4.2,
      "ratings_total": 2593,
      "positive_percentage": 79,
      "review_summary": {
        "thirty_days": {
          "positive_percent": 75,
          "neutral_percent": 1,
          "negative_percent": 23,
          "count": 89
        },
        "ninety_days": {
          "positive_percent": 78,
          "neutral_percent": 1,
          "negative_percent": 21,
          "count": 232
        },
        "twelve_months": {
          "positive_percent": 79,
          "neutral_percent": 2,
          "negative_percent": 19,
          "count": 812
        },
        "lifetime": {
          "positive_percent": 82,
          "neutral_percent": 3,
          "negative_percent": 15,
          "count": 2593
        }
      },
      "country": "US"
    },
    "outputFields": [
      {
        "key": "seller_id",
        "label": "Seller ID"
      },
      {
        "key": "name",
        "label": "Name"
      },
      {
        "key": "seller_link",
        "label": "Seller Link"
      },
      {
        "key": "store_link",
        "label": "Store Link"
      },
      {
        "key": "logo",
        "label": "Logo"
      },
      {
        "key": "about",
        "label": "About"
      },
      {
        "key": "business_name",
        "label": "Business Name"
      },
      {
        "key": "business_address",
        "label": "Business Address"
      },
      {
        "key": "rating",
        "label": "Rating",
        "type": "number"
      },
      {
        "key": "ratings_total",
        "label": "Ratings Total",
        "type": "number"
      },
      {
        "key": "positive_percentage",
        "label": "Positive Percentage",
        "type": "number"
      },
      {
        "key": "review_summary__thirty_days__positive_percent",
        "label": "Thirty Days Positive Percent",
        "type": "number"
      },
      {
        "key": "review_summary__thirty_days__neutral_percent",
        "label": "Thirty Days Neutral Percent",
        "type": "number"
      },
      {
        "key": "review_summary__thirty_days__negative_percent",
        "label": "Thirty Days Negative Percent",
        "type": "number"
      },
      {
        "key": "review_summary__thirty_days__count",
        "label": "Thirty Days Count",
        "type": "number"
      },
      {
        "key": "review_summary__ninety_days__positive_percent",
        "label": "Ninety Days Positive Percent",
        "type": "number"
      },
      {
        "key": "review_summary__ninety_days__neutral_percent",
        "label": "Ninety Days Neutral Percent",
        "type": "number"
      },
      {
        "key": "review_summary__ninety_days__negative_percent",
        "label": "Ninety Days Negative Percent",
        "type": "number"
      },
      {
        "key": "review_summary__ninety_days__count",
        "label": "Ninety Days Count",
        "type": "number"
      },
      {
        "key": "review_summary__twelve_months__positive_percent",
        "label": "Twelve Months Positive Percent",
        "type": "number"
      },
      {
        "key": "review_summary__twelve_months__neutral_percent",
        "label": "Twelve Months Neutral Percent",
        "type": "number"
      },
      {
        "key": "review_summary__twelve_months__negative_percent",
        "label": "Twelve Months Negative Percent",
        "type": "number"
      },
      {
        "key": "review_summary__twelve_months__count",
        "label": "Twelve Months Count",
        "type": "number"
      },
      {
        "key": "review_summary__lifetime__positive_percent",
        "label": "Lifetime Positive Percent",
        "type": "number"
      },
      {
        "key": "review_summary__lifetime__neutral_percent",
        "label": "Lifetime Neutral Percent",
        "type": "number"
      },
      {
        "key": "review_summary__lifetime__negative_percent",
        "label": "Lifetime Negative Percent",
        "type": "number"
      },
      {
        "key": "review_summary__lifetime__count",
        "label": "Lifetime Count",
        "type": "number"
      },
      {
        "key": "country",
        "label": "Country"
      }
    ],
    "trigger": null
  },
  {
    "key": "amazon_seller_reviews",
    "path": "/v1/amazon/seller/reviews",
    "method": "GET",
    "platform": "Amazon",
    "noun": "Review",
    "kind": "list",
    "listKey": "reviews",
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/amazon-seller-reviews",
    "action": {
      "label": "Get Amazon Seller Reviews",
      "description": "Gets customer feedback for an Amazon seller by seller ID. Each review includes author, text, star rating, date, and whether the seller responded. Filter by star rating or positive/critical. $0.005 per request after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "seller_id",
        "label": "Seller ID",
        "required": true,
        "type": "string",
        "helpText": "Amazon seller ID (up to 100 characters).",
        "placeholder": "A2L77EE7U53NWQ"
      },
      {
        "key": "page",
        "label": "Page Number",
        "required": false,
        "type": "integer",
        "default": "1",
        "helpText": "Page number, 1-50 (default: 1) (1-50)."
      },
      {
        "key": "star_rating",
        "label": "Star Rating",
        "required": false,
        "type": "string",
        "default": "all",
        "helpText": "Star rating filter (default: `all`)",
        "choices": {
          "all": "All",
          "5_stars": "5 Stars",
          "4_stars": "4 Stars",
          "3_stars": "3 Stars",
          "2_stars": "2 Stars",
          "1_stars": "1 Stars",
          "positive": "Positive",
          "critical": "Critical"
        }
      },
      {
        "key": "country",
        "label": "Country",
        "required": false,
        "type": "string",
        "default": "us",
        "helpText": "Marketplace country code (default: `us`)",
        "choices": {
          "us": "US",
          "au": "AU",
          "br": "BR",
          "ca": "CA",
          "cn": "CN",
          "fr": "FR",
          "de": "DE",
          "in": "IN",
          "it": "IT",
          "mx": "MX",
          "nl": "NL",
          "sg": "SG",
          "es": "ES",
          "tr": "TR",
          "ae": "AE",
          "gb": "GB",
          "jp": "JP",
          "sa": "SA",
          "pl": "PL",
          "se": "SE",
          "be": "BE",
          "eg": "EG",
          "za": "ZA",
          "ie": "IE"
        }
      },
      {
        "key": "get_sentiment",
        "label": "Add Sentiment Analysis",
        "required": false,
        "type": "boolean",
        "helpText": "Set to true to add AI emotion analysis to each review. Adds a `sentiment` object containing `emotions` (joy, trust, fear, surprise, sadness, disgust, anger and anticipation, each scored 0-100), `dominant_emotion`, `emotional_intensity` (0-10), and `polarity` (positive, negative or neutral). Any review that cannot be scored returns `sentiment: null`."
      }
    ],
    "sample": {
      "reviews": [
        {
          "author_name": "Tammy Parson",
          "review_text": "Received the next day in perfect condition. Contacted the seller and was answered promptly.",
          "rating": 5.0,
          "review_date": "August 30, 2026",
          "has_response": false
        }
      ],
      "count": 5,
      "seller_id": "A2L77EE7U53NWQ",
      "page": 1,
      "star_rating": "all",
      "has_next_page": true
    },
    "outputFields": [
      {
        "key": "reviews[]author_name",
        "label": "Reviews: Author Name"
      },
      {
        "key": "reviews[]review_text",
        "label": "Reviews: Review Text"
      },
      {
        "key": "reviews[]rating",
        "label": "Reviews: Rating",
        "type": "number"
      },
      {
        "key": "reviews[]review_date",
        "label": "Reviews: Review Date"
      },
      {
        "key": "reviews[]has_response",
        "label": "Reviews: Has Response",
        "type": "boolean"
      },
      {
        "key": "count",
        "label": "Count",
        "type": "number"
      },
      {
        "key": "seller_id",
        "label": "Seller ID"
      },
      {
        "key": "page",
        "label": "Page",
        "type": "number"
      },
      {
        "key": "star_rating",
        "label": "Star Rating"
      },
      {
        "key": "has_next_page",
        "label": "Has Next Page",
        "type": "boolean"
      }
    ],
    "trigger": {
      "label": "New Amazon Seller Review",
      "description": "Triggers when an Amazon seller gets a new review. Each check runs Get Amazon Seller Reviews ($0.005 per request after the free tier (50 requests/month)).",
      "inputFields": [
        {
          "key": "seller_id",
          "label": "Seller ID",
          "required": true,
          "type": "string",
          "helpText": "Amazon seller ID (up to 100 characters).",
          "placeholder": "A2L77EE7U53NWQ"
        },
        {
          "key": "page",
          "label": "Page Number",
          "required": false,
          "type": "integer",
          "default": "1",
          "helpText": "Page number, 1-50 (default: 1) (1-50)."
        },
        {
          "key": "star_rating",
          "label": "Star Rating",
          "required": false,
          "type": "string",
          "default": "all",
          "helpText": "Star rating filter (default: `all`)",
          "choices": {
            "all": "All",
            "5_stars": "5 Stars",
            "4_stars": "4 Stars",
            "3_stars": "3 Stars",
            "2_stars": "2 Stars",
            "1_stars": "1 Stars",
            "positive": "Positive",
            "critical": "Critical"
          }
        },
        {
          "key": "country",
          "label": "Country",
          "required": false,
          "type": "string",
          "default": "us",
          "helpText": "Marketplace country code (default: `us`)",
          "choices": {
            "us": "US",
            "au": "AU",
            "br": "BR",
            "ca": "CA",
            "cn": "CN",
            "fr": "FR",
            "de": "DE",
            "in": "IN",
            "it": "IT",
            "mx": "MX",
            "nl": "NL",
            "sg": "SG",
            "es": "ES",
            "tr": "TR",
            "ae": "AE",
            "gb": "GB",
            "jp": "JP",
            "sa": "SA",
            "pl": "PL",
            "se": "SE",
            "be": "BE",
            "eg": "EG",
            "za": "ZA",
            "ie": "IE"
          }
        },
        {
          "key": "get_sentiment",
          "label": "Add Sentiment Analysis",
          "required": false,
          "type": "boolean",
          "helpText": "Set to true to add AI emotion analysis to each review. Adds a `sentiment` object containing `emotions` (joy, trust, fear, surprise, sadness, disgust, anger and anticipation, each scored 0-100), `dominant_emotion`, `emotional_intensity` (0-10), and `polarity` (positive, negative or neutral). Any review that cannot be scored returns `sentiment: null`."
        }
      ],
      "sample": {
        "id": "author_name=Tammy Parson|review_date=August 30, 2026|review_text=Received the next day in perfect condition. Contacted the seller and was answered promptly.",
        "author_name": "Tammy Parson",
        "review_text": "Received the next day in perfect condition. Contacted the seller and was answered promptly.",
        "rating": 5.0,
        "review_date": "August 30, 2026",
        "has_response": false
      },
      "outputFields": [
        {
          "key": "id",
          "label": "ID",
          "primary": true
        },
        {
          "key": "author_name",
          "label": "Author Name"
        },
        {
          "key": "review_text",
          "label": "Review Text"
        },
        {
          "key": "rating",
          "label": "Rating",
          "type": "number"
        },
        {
          "key": "review_date",
          "label": "Review Date"
        },
        {
          "key": "has_response",
          "label": "Has Response",
          "type": "boolean"
        }
      ]
    }
  },
  {
    "key": "amazon_seller_products",
    "path": "/v1/amazon/seller/products",
    "method": "GET",
    "platform": "Amazon",
    "noun": "Product",
    "kind": "list",
    "listKey": "products",
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/amazon-seller-products",
    "action": {
      "label": "Get Amazon Seller Products",
      "description": "Gets the products sold by an Amazon seller by seller ID — the same product objects as Product Search plus the seller's total catalog size. Sortable and paginated (~16 results per page). $0.005 per request after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "seller_id",
        "label": "Seller ID",
        "required": true,
        "type": "string",
        "helpText": "Amazon seller ID (up to 100 characters).",
        "placeholder": "A2L77EE7U53NWQ"
      },
      {
        "key": "page",
        "label": "Page Number",
        "required": false,
        "type": "integer",
        "default": "1",
        "helpText": "Page number, 1-50 (default: 1) (1-50)."
      },
      {
        "key": "sort_by",
        "label": "Sort By",
        "required": false,
        "type": "string",
        "default": "relevance",
        "helpText": "Sort order (default: `relevance`)",
        "choices": {
          "relevance": "Relevance",
          "lowest_price": "Lowest Price",
          "highest_price": "Highest Price",
          "reviews": "Reviews",
          "newest": "Newest",
          "best_sellers": "Best Sellers"
        },
        "placeholder": "best_sellers"
      },
      {
        "key": "country",
        "label": "Country",
        "required": false,
        "type": "string",
        "default": "us",
        "helpText": "Marketplace country code (default: `us`)",
        "choices": {
          "us": "US",
          "au": "AU",
          "br": "BR",
          "ca": "CA",
          "cn": "CN",
          "fr": "FR",
          "de": "DE",
          "in": "IN",
          "it": "IT",
          "mx": "MX",
          "nl": "NL",
          "sg": "SG",
          "es": "ES",
          "tr": "TR",
          "ae": "AE",
          "gb": "GB",
          "jp": "JP",
          "sa": "SA",
          "pl": "PL",
          "se": "SE",
          "be": "BE",
          "eg": "EG",
          "za": "ZA",
          "ie": "IE"
        }
      }
    ],
    "sample": {
      "products": [
        {
          "asin": "B0BSHF7WHW",
          "title": "Apple AirPods Pro (2nd Generation) - Refurbished",
          "price": "$179.99",
          "original_price": "$249.00",
          "unit_price": null,
          "unit_count": null,
          "currency": "USD",
          "rating": 4.4,
          "num_ratings": 11203,
          "url": "https://www.amazon.com/dp/B0BSHF7WHW",
          "photo": "https://m.media-amazon.com/images/I/61SUj2aKoEL._AC_UY654_QL65_.jpg",
          "num_offers": 3,
          "minimum_offer_price": "$171.50",
          "is_best_seller": false,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "1K+ bought in past month",
          "delivery": "FREE delivery Tue, Sep 1",
          "availability": null,
          "has_variations": false,
          "badge": null,
          "coupon_text": null
        }
      ],
      "count": 16,
      "total_products": 224061,
      "seller_id": "A2L77EE7U53NWQ",
      "page": 1,
      "sort_by": "relevance"
    },
    "outputFields": [
      {
        "key": "products[]asin",
        "label": "Products: ASIN"
      },
      {
        "key": "products[]title",
        "label": "Products: Title"
      },
      {
        "key": "products[]price",
        "label": "Products: Price"
      },
      {
        "key": "products[]original_price",
        "label": "Products: Original Price"
      },
      {
        "key": "products[]unit_price",
        "label": "Products: Unit Price"
      },
      {
        "key": "products[]unit_count",
        "label": "Products: Unit Count"
      },
      {
        "key": "products[]currency",
        "label": "Products: Currency"
      },
      {
        "key": "products[]rating",
        "label": "Products: Rating",
        "type": "number"
      },
      {
        "key": "products[]num_ratings",
        "label": "Products: Num Ratings",
        "type": "number"
      },
      {
        "key": "products[]url",
        "label": "Products: URL"
      },
      {
        "key": "products[]photo",
        "label": "Products: Photo"
      },
      {
        "key": "products[]num_offers",
        "label": "Products: Num Offers",
        "type": "number"
      },
      {
        "key": "products[]minimum_offer_price",
        "label": "Products: Minimum Offer Price"
      },
      {
        "key": "products[]is_best_seller",
        "label": "Products: Is Best Seller",
        "type": "boolean"
      },
      {
        "key": "products[]is_amazon_choice",
        "label": "Products: Is Amazon Choice",
        "type": "boolean"
      },
      {
        "key": "products[]is_prime",
        "label": "Products: Is Prime",
        "type": "boolean"
      },
      {
        "key": "products[]climate_pledge_friendly",
        "label": "Products: Climate Pledge Friendly",
        "type": "boolean"
      },
      {
        "key": "products[]sales_volume",
        "label": "Products: Sales Volume"
      },
      {
        "key": "products[]delivery",
        "label": "Products: Delivery"
      },
      {
        "key": "products[]availability",
        "label": "Products: Availability"
      },
      {
        "key": "products[]has_variations",
        "label": "Products: Has Variations",
        "type": "boolean"
      },
      {
        "key": "products[]badge",
        "label": "Products: Badge"
      },
      {
        "key": "products[]coupon_text",
        "label": "Products: Coupon Text"
      },
      {
        "key": "count",
        "label": "Count",
        "type": "number"
      },
      {
        "key": "total_products",
        "label": "Total Products",
        "type": "number"
      },
      {
        "key": "seller_id",
        "label": "Seller ID"
      },
      {
        "key": "page",
        "label": "Page",
        "type": "number"
      },
      {
        "key": "sort_by",
        "label": "Sort By"
      }
    ],
    "trigger": {
      "label": "New Amazon Seller Product",
      "description": "Triggers when an Amazon seller lists a new product. Each check runs Get Amazon Seller Products ($0.005 per request after the free tier (50 requests/month)).",
      "inputFields": [
        {
          "key": "seller_id",
          "label": "Seller ID",
          "required": true,
          "type": "string",
          "helpText": "Amazon seller ID (up to 100 characters).",
          "placeholder": "A2L77EE7U53NWQ"
        },
        {
          "key": "page",
          "label": "Page Number",
          "required": false,
          "type": "integer",
          "default": "1",
          "helpText": "Page number, 1-50 (default: 1) (1-50)."
        },
        {
          "key": "sort_by",
          "label": "Sort By",
          "required": false,
          "type": "string",
          "default": "relevance",
          "helpText": "Sort order (default: `relevance`)",
          "choices": {
            "relevance": "Relevance",
            "lowest_price": "Lowest Price",
            "highest_price": "Highest Price",
            "reviews": "Reviews",
            "newest": "Newest",
            "best_sellers": "Best Sellers"
          },
          "placeholder": "best_sellers"
        },
        {
          "key": "country",
          "label": "Country",
          "required": false,
          "type": "string",
          "default": "us",
          "helpText": "Marketplace country code (default: `us`)",
          "choices": {
            "us": "US",
            "au": "AU",
            "br": "BR",
            "ca": "CA",
            "cn": "CN",
            "fr": "FR",
            "de": "DE",
            "in": "IN",
            "it": "IT",
            "mx": "MX",
            "nl": "NL",
            "sg": "SG",
            "es": "ES",
            "tr": "TR",
            "ae": "AE",
            "gb": "GB",
            "jp": "JP",
            "sa": "SA",
            "pl": "PL",
            "se": "SE",
            "be": "BE",
            "eg": "EG",
            "za": "ZA",
            "ie": "IE"
          }
        }
      ],
      "sample": {
        "id": "B0BSHF7WHW",
        "asin": "B0BSHF7WHW",
        "title": "Apple AirPods Pro (2nd Generation) - Refurbished",
        "price": "$179.99",
        "original_price": "$249.00",
        "unit_price": null,
        "unit_count": null,
        "currency": "USD",
        "rating": 4.4,
        "num_ratings": 11203,
        "url": "https://www.amazon.com/dp/B0BSHF7WHW",
        "photo": "https://m.media-amazon.com/images/I/61SUj2aKoEL._AC_UY654_QL65_.jpg",
        "num_offers": 3,
        "minimum_offer_price": "$171.50",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "1K+ bought in past month",
        "delivery": "FREE delivery Tue, Sep 1",
        "availability": null,
        "has_variations": false,
        "badge": null,
        "coupon_text": null
      },
      "outputFields": [
        {
          "key": "id",
          "label": "ID",
          "primary": true
        },
        {
          "key": "asin",
          "label": "ASIN"
        },
        {
          "key": "title",
          "label": "Title"
        },
        {
          "key": "price",
          "label": "Price"
        },
        {
          "key": "original_price",
          "label": "Original Price"
        },
        {
          "key": "unit_price",
          "label": "Unit Price"
        },
        {
          "key": "unit_count",
          "label": "Unit Count"
        },
        {
          "key": "currency",
          "label": "Currency"
        },
        {
          "key": "rating",
          "label": "Rating",
          "type": "number"
        },
        {
          "key": "num_ratings",
          "label": "Num Ratings",
          "type": "number"
        },
        {
          "key": "url",
          "label": "URL"
        },
        {
          "key": "photo",
          "label": "Photo"
        },
        {
          "key": "num_offers",
          "label": "Num Offers",
          "type": "number"
        },
        {
          "key": "minimum_offer_price",
          "label": "Minimum Offer Price"
        },
        {
          "key": "is_best_seller",
          "label": "Is Best Seller",
          "type": "boolean"
        },
        {
          "key": "is_amazon_choice",
          "label": "Is Amazon Choice",
          "type": "boolean"
        },
        {
          "key": "is_prime",
          "label": "Is Prime",
          "type": "boolean"
        },
        {
          "key": "climate_pledge_friendly",
          "label": "Climate Pledge Friendly",
          "type": "boolean"
        },
        {
          "key": "sales_volume",
          "label": "Sales Volume"
        },
        {
          "key": "delivery",
          "label": "Delivery"
        },
        {
          "key": "availability",
          "label": "Availability"
        },
        {
          "key": "has_variations",
          "label": "Has Variations",
          "type": "boolean"
        },
        {
          "key": "badge",
          "label": "Badge"
        },
        {
          "key": "coupon_text",
          "label": "Coupon Text"
        }
      ]
    }
  },
  {
    "key": "amazon_best_sellers",
    "path": "/v1/amazon/best-sellers",
    "method": "GET",
    "platform": "Amazon",
    "noun": "Product",
    "kind": "list",
    "listKey": "products",
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/amazon-best-sellers",
    "action": {
      "label": "Get Amazon Best Sellers",
      "description": "Gets Amazon best-seller rankings for a category — Best Sellers, New Releases, Movers & Shakers, Most Wished For, or Gift Ideas. Up to 50 ranked items per page with rank, price, and rating. $0.005 per request after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "category",
        "label": "Category",
        "required": true,
        "type": "string",
        "helpText": "Category slug, e.g. `electronics` or `software` (see [docs](https://apidirect.io/docs/amazon-categories)) (up to 200 characters).",
        "placeholder": "software"
      },
      {
        "key": "type",
        "label": "Type",
        "required": false,
        "type": "string",
        "default": "best_sellers",
        "helpText": "Ranking type (default: `best_sellers`)",
        "choices": {
          "best_sellers": "Best Sellers",
          "gift_ideas": "Gift Ideas",
          "most_wished_for": "Most Wished For",
          "movers_and_shakers": "Movers And Shakers",
          "new_releases": "New Releases"
        }
      },
      {
        "key": "page",
        "label": "Page Number",
        "required": false,
        "type": "integer",
        "default": "1",
        "helpText": "Page number, 1 or 2 (default: 1). Rankings cover the top 100 (1-2)."
      },
      {
        "key": "country",
        "label": "Country",
        "required": false,
        "type": "string",
        "default": "us",
        "helpText": "Marketplace country code (default: `us`)",
        "choices": {
          "us": "US",
          "au": "AU",
          "br": "BR",
          "ca": "CA",
          "cn": "CN",
          "fr": "FR",
          "de": "DE",
          "in": "IN",
          "it": "IT",
          "mx": "MX",
          "nl": "NL",
          "sg": "SG",
          "es": "ES",
          "tr": "TR",
          "ae": "AE",
          "gb": "GB",
          "jp": "JP",
          "sa": "SA",
          "pl": "PL",
          "se": "SE",
          "be": "BE",
          "eg": "EG",
          "za": "ZA",
          "ie": "IE"
        }
      }
    ],
    "sample": {
      "products": [
        {
          "rank": 1,
          "rank_change": null,
          "asin": "B0FWV56H48",
          "title": "TurboTax Deluxe Desktop Edition 2025, Federal & State Tax Return",
          "price": "$79.99",
          "rating": 4.0,
          "num_ratings": 6866,
          "url": "https://www.amazon.com/dp/B0FWV56H48",
          "photo": "https://images-na.ssl-images-amazon.com/images/I/71OcM906MLL._AC_UL900_SR900,600_.jpg"
        }
      ],
      "count": 50,
      "category": "software",
      "category_name": "Software",
      "type": "best_sellers",
      "page": 1
    },
    "outputFields": [
      {
        "key": "products[]rank",
        "label": "Products: Rank",
        "type": "number"
      },
      {
        "key": "products[]rank_change",
        "label": "Products: Rank Change"
      },
      {
        "key": "products[]asin",
        "label": "Products: ASIN"
      },
      {
        "key": "products[]title",
        "label": "Products: Title"
      },
      {
        "key": "products[]price",
        "label": "Products: Price"
      },
      {
        "key": "products[]rating",
        "label": "Products: Rating",
        "type": "number"
      },
      {
        "key": "products[]num_ratings",
        "label": "Products: Num Ratings",
        "type": "number"
      },
      {
        "key": "products[]url",
        "label": "Products: URL"
      },
      {
        "key": "products[]photo",
        "label": "Products: Photo"
      },
      {
        "key": "count",
        "label": "Count",
        "type": "number"
      },
      {
        "key": "category",
        "label": "Category"
      },
      {
        "key": "category_name",
        "label": "Category Name"
      },
      {
        "key": "type",
        "label": "Type"
      },
      {
        "key": "page",
        "label": "Page",
        "type": "number"
      }
    ],
    "trigger": {
      "label": "New Amazon Best Seller",
      "description": "Triggers when a product enters an Amazon best sellers list. Each check runs Get Amazon Best Sellers ($0.005 per request after the free tier (50 requests/month)).",
      "inputFields": [
        {
          "key": "category",
          "label": "Category",
          "required": true,
          "type": "string",
          "helpText": "Category slug, e.g. `electronics` or `software` (see [docs](https://apidirect.io/docs/amazon-categories)) (up to 200 characters).",
          "placeholder": "software"
        },
        {
          "key": "type",
          "label": "Type",
          "required": false,
          "type": "string",
          "default": "best_sellers",
          "helpText": "Ranking type (default: `best_sellers`)",
          "choices": {
            "best_sellers": "Best Sellers",
            "gift_ideas": "Gift Ideas",
            "most_wished_for": "Most Wished For",
            "movers_and_shakers": "Movers And Shakers",
            "new_releases": "New Releases"
          }
        },
        {
          "key": "page",
          "label": "Page Number",
          "required": false,
          "type": "integer",
          "default": "1",
          "helpText": "Page number, 1 or 2 (default: 1). Rankings cover the top 100 (1-2)."
        },
        {
          "key": "country",
          "label": "Country",
          "required": false,
          "type": "string",
          "default": "us",
          "helpText": "Marketplace country code (default: `us`)",
          "choices": {
            "us": "US",
            "au": "AU",
            "br": "BR",
            "ca": "CA",
            "cn": "CN",
            "fr": "FR",
            "de": "DE",
            "in": "IN",
            "it": "IT",
            "mx": "MX",
            "nl": "NL",
            "sg": "SG",
            "es": "ES",
            "tr": "TR",
            "ae": "AE",
            "gb": "GB",
            "jp": "JP",
            "sa": "SA",
            "pl": "PL",
            "se": "SE",
            "be": "BE",
            "eg": "EG",
            "za": "ZA",
            "ie": "IE"
          }
        }
      ],
      "sample": {
        "id": "B0FWV56H48",
        "rank": 1,
        "rank_change": null,
        "asin": "B0FWV56H48",
        "title": "TurboTax Deluxe Desktop Edition 2025, Federal & State Tax Return",
        "price": "$79.99",
        "rating": 4.0,
        "num_ratings": 6866,
        "url": "https://www.amazon.com/dp/B0FWV56H48",
        "photo": "https://images-na.ssl-images-amazon.com/images/I/71OcM906MLL._AC_UL900_SR900,600_.jpg"
      },
      "outputFields": [
        {
          "key": "id",
          "label": "ID",
          "primary": true
        },
        {
          "key": "rank",
          "label": "Rank",
          "type": "number"
        },
        {
          "key": "rank_change",
          "label": "Rank Change"
        },
        {
          "key": "asin",
          "label": "ASIN"
        },
        {
          "key": "title",
          "label": "Title"
        },
        {
          "key": "price",
          "label": "Price"
        },
        {
          "key": "rating",
          "label": "Rating",
          "type": "number"
        },
        {
          "key": "num_ratings",
          "label": "Num Ratings",
          "type": "number"
        },
        {
          "key": "url",
          "label": "URL"
        },
        {
          "key": "photo",
          "label": "Photo"
        }
      ]
    }
  }
];
