// Generated by scripts/generate.py from spec/openapi.json. Do not edit by hand;
// change the spec or the generator and run `npm run generate`.
module.exports = [
  {
    "key": "forums_posts",
    "path": "/v1/forums/posts",
    "method": "GET",
    "platform": "Forums",
    "noun": "Post",
    "kind": "list",
    "listKey": "posts",
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/forum-posts",
    "action": {
      "label": "Search Forum Posts",
      "description": "Searches for forum posts across the web, including discussion boards, Q&A sites, and community boards. Each result returns its position and rank, the post title, URL, source forum, domain, and a content snippet. Supports filtering by time period (hour, day, week, month, year) and by country (ISO 3166-1 alpha-2 code). Results are paginated 10 at a time via the page parameter, and count reports how many were returned. The search runs in English. Set get_sentiment=true to add AI emotion analysis to each post. $0.008 per request after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "query",
        "label": "Search Query",
        "required": true,
        "type": "string",
        "helpText": "Search query (max 500 characters). Leading and trailing whitespace is trimmed, and the query must not be empty.",
        "placeholder": "programming"
      },
      {
        "key": "page",
        "label": "Page Number",
        "required": false,
        "type": "integer",
        "default": "1",
        "helpText": "Page number for pagination, 1-10 (default: 1). Results are paginated 10 at a time, so page=2 starts at the 11th result. Values below 1, and values that are not numbers, are treated as 1. A page above 10 returns 400 (1-10)."
      },
      {
        "key": "time",
        "label": "Time",
        "required": false,
        "type": "string",
        "default": "any",
        "helpText": "Filter by time period. 'any' applies no time filter. Any value outside this list returns 400.",
        "choices": {
          "any": "Any",
          "hour": "Hour",
          "day": "Day",
          "week": "Week",
          "month": "Month",
          "year": "Year"
        },
        "placeholder": "week"
      },
      {
        "key": "country",
        "label": "Country",
        "required": false,
        "type": "string",
        "helpText": "ISO 3166-1 alpha-2 country code (e.g., US, GB, DE). Case-insensitive. Any value that is not exactly 2 letters returns 400 (up to 2 characters).",
        "placeholder": "US"
      },
      {
        "key": "get_sentiment",
        "label": "Add Sentiment Analysis",
        "required": false,
        "type": "boolean",
        "helpText": "Set to true to add AI emotion analysis to each post. Adds a `sentiment` object containing `emotions` (joy, trust, fear, surprise, sadness, disgust, anger and anticipation, each scored 0-100), `dominant_emotion`, `emotional_intensity` (0-10), and `polarity` (positive, negative or neutral). Any post that cannot be scored returns `sentiment: null`."
      }
    ],
    "sample": {
      "count": 10,
      "page": 1,
      "posts": [
        {
          "domain": "reddit.com",
          "position": 1,
          "rank": 1,
          "snippet": "Programming is how everything in tech works. It's a set of instructions given to the computer to run a set of tasks. Let's take Google for ...",
          "source": "Reddit",
          "title": "What is programming? : r/AskProgramming - Reddit",
          "url": "https://www.reddit.com/r/AskProgramming/comments/1eo7fez/what_is_programming/"
        },
        {
          "domain": "sololearn.com",
          "position": 2,
          "rank": 2,
          "snippet": "'%' this sign stands for modulo sign. It is use to get carry after devision. Like if you are dividing 10 by 3 then carry will be 1 because 3*3 = 9 and 1 will ...",
          "source": "Sololearn",
          "title": "What does \"%\" mean in programming? - Sololearn",
          "url": "https://www.sololearn.com/en/Discuss/1629466/what-does-mean-in-programming"
        },
        {
          "domain": "forum.freecodecamp.org",
          "position": 3,
          "rank": 3,
          "snippet": "Computer programming is teaching humans to think like a computer and to write instructions in a human-like meta language that can be translated into the 1s and ...",
          "source": "The freeCodeCamp Forum",
          "title": "What is Programming - The freeCodeCamp Forum",
          "url": "https://forum.freecodecamp.org/t/what-is-programming/484906"
        }
      ]
    },
    "outputFields": [
      {
        "key": "count",
        "label": "Count",
        "type": "number"
      },
      {
        "key": "page",
        "label": "Page",
        "type": "number"
      },
      {
        "key": "posts[]domain",
        "label": "Posts: Domain"
      },
      {
        "key": "posts[]position",
        "label": "Posts: Position",
        "type": "number"
      },
      {
        "key": "posts[]rank",
        "label": "Posts: Rank",
        "type": "number"
      },
      {
        "key": "posts[]snippet",
        "label": "Posts: Snippet"
      },
      {
        "key": "posts[]source",
        "label": "Posts: Source"
      },
      {
        "key": "posts[]title",
        "label": "Posts: Title"
      },
      {
        "key": "posts[]url",
        "label": "Posts: URL"
      }
    ],
    "trigger": {
      "label": "New Forum Post Matching Search",
      "description": "Triggers when a new forum post matches your search. Each check runs Search Forum Posts ($0.008 per request after the free tier (50 requests/month)).",
      "inputFields": [
        {
          "key": "query",
          "label": "Search Query",
          "required": true,
          "type": "string",
          "helpText": "Search query (max 500 characters). Leading and trailing whitespace is trimmed, and the query must not be empty.",
          "placeholder": "programming"
        },
        {
          "key": "page",
          "label": "Page Number",
          "required": false,
          "type": "integer",
          "default": "1",
          "helpText": "Page number for pagination, 1-10 (default: 1). Results are paginated 10 at a time, so page=2 starts at the 11th result. Values below 1, and values that are not numbers, are treated as 1. A page above 10 returns 400 (1-10)."
        },
        {
          "key": "time",
          "label": "Time",
          "required": false,
          "type": "string",
          "default": "any",
          "helpText": "Filter by time period. 'any' applies no time filter. Any value outside this list returns 400.",
          "choices": {
            "any": "Any",
            "hour": "Hour",
            "day": "Day",
            "week": "Week",
            "month": "Month",
            "year": "Year"
          },
          "placeholder": "week"
        },
        {
          "key": "country",
          "label": "Country",
          "required": false,
          "type": "string",
          "helpText": "ISO 3166-1 alpha-2 country code (e.g., US, GB, DE). Case-insensitive. Any value that is not exactly 2 letters returns 400 (up to 2 characters).",
          "placeholder": "US"
        },
        {
          "key": "get_sentiment",
          "label": "Add Sentiment Analysis",
          "required": false,
          "type": "boolean",
          "helpText": "Set to true to add AI emotion analysis to each post. Adds a `sentiment` object containing `emotions` (joy, trust, fear, surprise, sadness, disgust, anger and anticipation, each scored 0-100), `dominant_emotion`, `emotional_intensity` (0-10), and `polarity` (positive, negative or neutral). Any post that cannot be scored returns `sentiment: null`."
        }
      ],
      "sample": {
        "id": "https://www.reddit.com/r/AskProgramming/comments/1eo7fez/what_is_programming/",
        "domain": "reddit.com",
        "position": 1,
        "rank": 1,
        "snippet": "Programming is how everything in tech works. It's a set of instructions given to the computer to run a set of tasks. Let's take Google for ...",
        "source": "Reddit",
        "title": "What is programming? : r/AskProgramming - Reddit",
        "url": "https://www.reddit.com/r/AskProgramming/comments/1eo7fez/what_is_programming/"
      },
      "outputFields": [
        {
          "key": "id",
          "label": "ID",
          "primary": true
        },
        {
          "key": "domain",
          "label": "Domain"
        },
        {
          "key": "position",
          "label": "Position",
          "type": "number"
        },
        {
          "key": "rank",
          "label": "Rank",
          "type": "number"
        },
        {
          "key": "snippet",
          "label": "Snippet"
        },
        {
          "key": "source",
          "label": "Source"
        },
        {
          "key": "title",
          "label": "Title"
        },
        {
          "key": "url",
          "label": "URL"
        }
      ]
    }
  }
];
