// Generated by scripts/generate.py from spec/openapi.json. Do not edit by hand;
// change the spec or the generator and run `npm run generate`.
module.exports = [
  {
    "key": "web_search",
    "path": "/v1/web/search",
    "method": "GET",
    "platform": "Google Search",
    "noun": "Search Result",
    "kind": "list",
    "listKey": "results",
    "idFields": [
      "url"
    ],
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/web-search",
    "action": {
      "label": "Search Google",
      "description": "Runs a real-time Google search and return organic results with position, rank, title, URL, snippet, source, domain, and displayed link. Supports Google advanced operators (site:, inurl:, intitle:). Fetch 1-10 pages of results in a single call: each page is 10 results and every page is merged into one results array. Supports country, language, time window, city-level location, and device targeting. Set include_ai_overview=true to include Google's AI Overview when one is available for the query. $0.004 per page (+$0.002 flat per request when include_ai_overview=true) after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "query",
        "label": "Search Query",
        "required": true,
        "type": "string",
        "helpText": "Search keyword (max 500 characters, measured after leading and trailing whitespace is trimmed). Supports Google advanced operators (site:, inurl:, intitle:, etc.)",
        "placeholder": "how to build a website"
      },
      {
        "key": "pages",
        "label": "Pages to Fetch",
        "required": false,
        "type": "integer",
        "default": "1",
        "helpText": "Number of result pages to fetch and merge (10 results per page). This is a count, not a page number: pages=3 returns the first 30 results in a single results array. Values above 10 are rejected with 400; values below 1 are treated as 1. Each page is billed as one request (1-10).",
        "placeholder": "2"
      },
      {
        "key": "country",
        "label": "Country",
        "required": false,
        "type": "string",
        "default": "us",
        "helpText": "2-letter ISO 3166-1 alpha-2 country code. A value that is not exactly 2 letters is rejected with 400 (up to 2 characters).",
        "placeholder": "us"
      },
      {
        "key": "language",
        "label": "Language",
        "required": false,
        "type": "string",
        "default": "en",
        "helpText": "2-letter ISO 639-1 language code. A value that is not exactly 2 letters is rejected with 400 (up to 2 characters).",
        "placeholder": "en"
      },
      {
        "key": "time",
        "label": "Time",
        "required": false,
        "type": "string",
        "default": "any",
        "helpText": "Time filter for results",
        "choices": {
          "any": "Any",
          "hour": "Hour",
          "day": "Day",
          "week": "Week",
          "month": "Month",
          "year": "Year"
        }
      },
      {
        "key": "location",
        "label": "Location",
        "required": false,
        "type": "string",
        "helpText": "City-level geo location (e.g. London,England,United Kingdom)"
      },
      {
        "key": "device",
        "label": "Device",
        "required": false,
        "type": "string",
        "default": "desktop",
        "helpText": "Device type to simulate",
        "choices": {
          "desktop": "Desktop",
          "mobile": "Mobile"
        }
      },
      {
        "key": "include_ai_overview",
        "label": "Include AI Overview",
        "required": false,
        "type": "boolean",
        "helpText": "When true, include Google's AI Overview for the query. Only the exact value true (case-insensitive) enables it. When enabled, the response always contains an ai_overview field, which is null if Google generated no overview for the query."
      }
    ],
    "sample": {
      "results": [
        {
          "position": 1,
          "rank": 1,
          "title": "Website Builder - Create a Free Website",
          "url": "https://www.canva.com/website-builder/",
          "snippet": "Design and launch a professional, one-of-a-kind website in minutes...",
          "source": "Canva",
          "domain": "canva.com",
          "displayed_link": "https://www.canva.com › website-builder"
        },
        {
          "position": 2,
          "rank": 2,
          "title": "Wix.com: Website Builder - Create a Free Website In Minutes",
          "url": "https://www.wix.com/",
          "snippet": "Get everything you need to create your website, your way...",
          "source": "Wix",
          "domain": "wix.com",
          "displayed_link": "https://www.wix.com"
        }
      ],
      "pages": 2,
      "count": 20,
      "ai_overview": {
        "text_parts": [
          {
            "type": "paragraph",
            "text": "Building a website involves choosing a platform, designing pages, and publishing. Most modern builders offer drag-and-drop interfaces..."
          }
        ],
        "reference_links": [
          {
            "title": "How to Create a Website From Scratch",
            "link": "https://www.wix.com/blog/how-to-build-website-from-scratch-guide",
            "source": "Wix"
          }
        ]
      }
    },
    "outputFields": [
      {
        "key": "results[]position",
        "label": "Results: Position",
        "type": "number"
      },
      {
        "key": "results[]rank",
        "label": "Results: Rank",
        "type": "number"
      },
      {
        "key": "results[]title",
        "label": "Results: Title"
      },
      {
        "key": "results[]url",
        "label": "Results: URL"
      },
      {
        "key": "results[]snippet",
        "label": "Results: Snippet"
      },
      {
        "key": "results[]source",
        "label": "Results: Source"
      },
      {
        "key": "results[]domain",
        "label": "Results: Domain"
      },
      {
        "key": "results[]displayed_link",
        "label": "Results: Displayed Link"
      },
      {
        "key": "pages",
        "label": "Pages",
        "type": "number"
      },
      {
        "key": "count",
        "label": "Count",
        "type": "number"
      },
      {
        "key": "ai_overview__text_parts[]type",
        "label": "Text Parts: Type"
      },
      {
        "key": "ai_overview__text_parts[]text",
        "label": "Text Parts: Text"
      },
      {
        "key": "ai_overview__reference_links[]title",
        "label": "Reference Links: Title"
      },
      {
        "key": "ai_overview__reference_links[]link",
        "label": "Reference Links: Link"
      },
      {
        "key": "ai_overview__reference_links[]source",
        "label": "Reference Links: Source"
      }
    ],
    "trigger": {
      "label": "New Google Search Result",
      "description": "Triggers when a new web page appears in Google results for your search. Each check runs Search Google ($0.004 per page (+$0.002 flat per request when include_ai_overview=true)).",
      "inputFields": [
        {
          "key": "query",
          "label": "Search Query",
          "required": true,
          "type": "string",
          "helpText": "Search keyword (max 500 characters, measured after leading and trailing whitespace is trimmed). Supports Google advanced operators (site:, inurl:, intitle:, etc.)",
          "placeholder": "how to build a website"
        },
        {
          "key": "pages",
          "label": "Pages to Fetch",
          "required": false,
          "type": "integer",
          "default": "1",
          "helpText": "Number of result pages to fetch and merge (10 results per page). This is a count, not a page number: pages=3 returns the first 30 results in a single results array. Values above 10 are rejected with 400; values below 1 are treated as 1. Each page is billed as one request (1-10). Every check of this trigger fetches this many pages, each billed as one request.",
          "placeholder": "2"
        },
        {
          "key": "country",
          "label": "Country",
          "required": false,
          "type": "string",
          "default": "us",
          "helpText": "2-letter ISO 3166-1 alpha-2 country code. A value that is not exactly 2 letters is rejected with 400 (up to 2 characters).",
          "placeholder": "us"
        },
        {
          "key": "language",
          "label": "Language",
          "required": false,
          "type": "string",
          "default": "en",
          "helpText": "2-letter ISO 639-1 language code. A value that is not exactly 2 letters is rejected with 400 (up to 2 characters).",
          "placeholder": "en"
        },
        {
          "key": "time",
          "label": "Time",
          "required": false,
          "type": "string",
          "default": "any",
          "helpText": "Time filter for results",
          "choices": {
            "any": "Any",
            "hour": "Hour",
            "day": "Day",
            "week": "Week",
            "month": "Month",
            "year": "Year"
          }
        },
        {
          "key": "location",
          "label": "Location",
          "required": false,
          "type": "string",
          "helpText": "City-level geo location (e.g. London,England,United Kingdom)"
        },
        {
          "key": "device",
          "label": "Device",
          "required": false,
          "type": "string",
          "default": "desktop",
          "helpText": "Device type to simulate",
          "choices": {
            "desktop": "Desktop",
            "mobile": "Mobile"
          }
        },
        {
          "key": "include_ai_overview",
          "label": "Include AI Overview",
          "required": false,
          "type": "boolean",
          "helpText": "When true, include Google's AI Overview for the query. Only the exact value true (case-insensitive) enables it. When enabled, the response always contains an ai_overview field, which is null if Google generated no overview for the query."
        }
      ],
      "sample": {
        "id": "https://www.canva.com/website-builder/",
        "position": 1,
        "rank": 1,
        "title": "Website Builder - Create a Free Website",
        "url": "https://www.canva.com/website-builder/",
        "snippet": "Design and launch a professional, one-of-a-kind website in minutes...",
        "source": "Canva",
        "domain": "canva.com",
        "displayed_link": "https://www.canva.com › website-builder"
      },
      "outputFields": [
        {
          "key": "id",
          "label": "ID",
          "primary": true
        },
        {
          "key": "position",
          "label": "Position",
          "type": "number"
        },
        {
          "key": "rank",
          "label": "Rank",
          "type": "number"
        },
        {
          "key": "title",
          "label": "Title"
        },
        {
          "key": "url",
          "label": "URL"
        },
        {
          "key": "snippet",
          "label": "Snippet"
        },
        {
          "key": "source",
          "label": "Source"
        },
        {
          "key": "domain",
          "label": "Domain"
        },
        {
          "key": "displayed_link",
          "label": "Displayed Link"
        }
      ]
    }
  },
  {
    "key": "web_ai_mode",
    "path": "/v1/web/ai-mode",
    "method": "GET",
    "platform": "Google Search",
    "noun": "Answer",
    "kind": "answer",
    "listKey": null,
    "idFields": null,
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/google-ai-mode",
    "action": {
      "label": "Ask Google AI Mode",
      "description": "Sends a prompt to Google's AI Mode and receive a structured conversational reply broken into ordered parts (paragraph, heading, list, images) with cited reference links. Each response includes a session_token: pass it on the next call to continue the conversation in context. Each call, including a follow-up, is billed as one request. The same endpoint also accepts POST with a JSON body for prompts that do not fit comfortably in a URL. In the rare case where Google returns no answer, the response is still 200 with an empty reply_parts array. $0.005 per request after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "prompt",
        "label": "Prompt",
        "required": true,
        "type": "string",
        "helpText": "The AI Mode prompt (max 12000 characters)",
        "placeholder": "How do I make pizza?"
      },
      {
        "key": "country",
        "label": "Country",
        "required": false,
        "type": "string",
        "default": "us",
        "helpText": "2-letter ISO 3166-1 alpha-2 country code. A value that is not exactly 2 letters is rejected with 400 (up to 2 characters)."
      },
      {
        "key": "language",
        "label": "Language",
        "required": false,
        "type": "string",
        "default": "en",
        "helpText": "2-letter ISO 639-1 language code. A value that is not exactly 2 letters is rejected with 400 (up to 2 characters)."
      },
      {
        "key": "session_token",
        "label": "Session Token",
        "required": false,
        "type": "string",
        "helpText": "Token from a previous AI Mode response. Pass it to continue the conversation with prior context. Treat as an opaque string."
      }
    ],
    "sample": {
      "reply_parts": [
        {
          "type": "paragraph",
          "text": "Making pizza at home involves preparing the dough, sauce, and toppings, then baking at high heat."
        },
        {
          "type": "heading",
          "text": "1. Prepare the Dough"
        },
        {
          "type": "list",
          "ordered": false,
          "list": [
            {
              "title": "Activate Yeast:",
              "text": "Mix warm water with yeast and a pinch of sugar. Let it sit for about 5-10 minutes until foamy."
            },
            {
              "title": "Mix and Knead:",
              "text": "Combine the yeast mixture with flour and salt. Knead for 5-10 minutes until smooth and elastic."
            }
          ]
        }
      ],
      "reference_links": [
        {
          "title": "Best Homemade Pizza Dough (photo tutorial)",
          "link": "https://www.crunchycreamysweet.com/the-best-homemade-pizza-dough-photo-tutorial/",
          "snippet": "Instructions. Place water and sugar in a large mixing bowl...",
          "source": "Crunchy Creamy Sweet",
          "favicon": "https://encrypted-tbn1.gstatic.com/faviconV2?url=https://www.crunchycreamysweet.com&size=128",
          "date": "Jul 6, 2012"
        }
      ],
      "session_token": "Q21vd1lUZHFaMjlNYWtOTWREQndWRmRyV1RNemFqRnViak01Ym1FeE1tdFZVemhFVGxCeFQxZE9RV1o0..."
    },
    "outputFields": [
      {
        "key": "reply_parts[]type",
        "label": "Reply Parts: Type"
      },
      {
        "key": "reply_parts[]text",
        "label": "Reply Parts: Text"
      },
      {
        "key": "reference_links[]title",
        "label": "Reference Links: Title"
      },
      {
        "key": "reference_links[]link",
        "label": "Reference Links: Link"
      },
      {
        "key": "reference_links[]snippet",
        "label": "Reference Links: Snippet"
      },
      {
        "key": "reference_links[]source",
        "label": "Reference Links: Source"
      },
      {
        "key": "reference_links[]favicon",
        "label": "Reference Links: Favicon"
      },
      {
        "key": "reference_links[]date",
        "label": "Reference Links: Date"
      },
      {
        "key": "session_token",
        "label": "Session Token"
      }
    ],
    "trigger": null
  }
];
