// Generated by scripts/generate.py from spec/openapi.json. Do not edit by hand;
// change the spec or the generator and run `npm run generate`.
module.exports = [
  {
    "key": "places_search",
    "path": "/v1/places/search",
    "method": "GET",
    "platform": "Google Places",
    "noun": "Place",
    "kind": "list",
    "listKey": "places",
    "idFields": [
      "place_id"
    ],
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/places-search",
    "action": {
      "label": "Search Google Places",
      "description": "Searches Google Maps places (local businesses, restaurants, hotels, shops and points of interest) by free-text query. Returns name, address, phone, website, rating, review count, opening hours, coordinates, and a sample of photos for each result. Optionally bias results by latitude, longitude and zoom level; lat and lng must be sent together. Each page returns up to 10 places and is billed as one request, up to 20 pages per call. $0.01 per page after the free tier (20 requests/month)."
    },
    "inputFields": [
      {
        "key": "query",
        "label": "Search Query",
        "required": true,
        "type": "string",
        "helpText": "Search keyword (max 500 characters). E.g. `coffee shops brooklyn`, `dentists 90210`, `hilton hotels paris`",
        "placeholder": "pizza new york"
      },
      {
        "key": "pages",
        "label": "Pages to Fetch",
        "required": false,
        "type": "integer",
        "default": "1",
        "helpText": "Number of pages to fetch and merge. Each page returns up to 10 results and is billed as one request (1-20).",
        "placeholder": "2"
      },
      {
        "key": "limit",
        "label": "Limit",
        "required": false,
        "type": "integer",
        "helpText": "Alternative to `pages`: maximum number of results, rounded up to whole pages of 10 (e.g. `limit=15` fetches 2 pages, so up to 20 results). Ignored when `pages` is also sent. Maximum 200 (1-200)."
      },
      {
        "key": "lat",
        "label": "Latitude",
        "required": false,
        "type": "number",
        "helpText": "Center latitude for geographic bias (provide with `lng`)"
      },
      {
        "key": "lng",
        "label": "Longitude",
        "required": false,
        "type": "number",
        "helpText": "Center longitude for geographic bias (provide with `lat`)"
      },
      {
        "key": "zoom",
        "label": "Zoom",
        "required": false,
        "type": "integer",
        "helpText": "Map zoom level. Smaller values widen the search radius (13 ≈ city, 15 ≈ neighborhood, 10 ≈ metro area) (1-20)."
      },
      {
        "key": "country",
        "label": "Country",
        "required": false,
        "type": "string",
        "default": "us",
        "helpText": "2-letter ISO 3166-1 alpha-2 region code (up to 2 characters)."
      },
      {
        "key": "language",
        "label": "Language",
        "required": false,
        "type": "string",
        "default": "en",
        "helpText": "2-letter ISO 639-1 language code (up to 2 characters)."
      }
    ],
    "sample": {
      "places": [
        {
          "place_id": "ChIJifIePKtZwokRVZ-UdRGkZzs",
          "name": "Joe's Pizza Broadway",
          "type": "Pizza restaurant",
          "subtypes": [
            "Pizza restaurant",
            "Pizza delivery",
            "Restaurant"
          ],
          "phone_number": "+16465550142",
          "website": "https://www.joespizzanyc.com",
          "domain": "joespizzanyc.com",
          "rating": 4.5,
          "review_count": 25433,
          "reviews_per_rating": {
            "1": 753,
            "2": 604,
            "3": 2107,
            "4": 4946,
            "5": 17023
          },
          "price_level": "$10–20",
          "verified": true,
          "business_status": "OPEN",
          "opening_status": "Open · Closes 3 AM",
          "working_hours": {
            "Monday": [
              "10 AM–3 AM"
            ],
            "Sunday": [
              "10 AM–3 AM"
            ]
          },
          "opening_date": null,
          "address": "Joe's Pizza Broadway, 1435 Broadway, New York, NY 10018",
          "street_address": "1435 Broadway",
          "district": "Manhattan",
          "city": "New York",
          "state": "New York",
          "zipcode": "10018",
          "country": "US",
          "latitude": 40.75468,
          "longitude": -73.98703,
          "timezone": "America/New_York",
          "summary": "Modern outpost of a longtime counter-serve pizza joint prepping New York-style slices and pies.",
          "about": {
            "summary": "Modern outpost of a longtime counter-serve pizza joint prepping New York-style slices and pies.",
            "details": {
              "Accessibility": {
                "Wheelchair accessible entrance": true,
                "Wheelchair accessible parking lot": false,
                "Wheelchair accessible seating": false
              }
            }
          },
          "photo_count": 22117,
          "photos_sample": [
            {
              "photo_id": "CIABIhBpKlqRIOpwhdI384bUAF4L",
              "type": "photo",
              "photo_url": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAH...",
              "photo_url_large": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAH...=w3000-h4000-k-no",
              "video_thumbnail_url": null,
              "latitude": 40.7546469,
              "longitude": -73.9868158,
              "photo_datetime_utc": "2026-06-16T00:00:00.000Z",
              "photo_timestamp": 1781568000
            }
          ],
          "place_link": "https://www.google.com/maps/place/data=...",
          "reviews_link": "https://search.google.com/local/reviews?placeid=ChIJifIePKtZwokRVZ-UdRGkZzs",
          "booking_link": "https://www.google.com/searchviewer/42?...",
          "reservations_link": "https://www.fooddiscoveryapp.com/new-york-city/joes-pizza",
          "order_link": "https://www.google.com/searchviewer/42?...",
          "owner_name": "Joe's Pizza Broadway",
          "owner_link": "https://maps.google.com/maps/contrib/103877821925204408966",
          "cid": "4280570365733019477"
        }
      ],
      "count": 1,
      "query": "pizza new york",
      "pages": 2
    },
    "outputFields": [
      {
        "key": "places[]place_id",
        "label": "Places: Place ID"
      },
      {
        "key": "places[]name",
        "label": "Places: Name"
      },
      {
        "key": "places[]type",
        "label": "Places: Type"
      },
      {
        "key": "places[]subtypes",
        "label": "Places: Subtypes",
        "list": true
      },
      {
        "key": "places[]phone_number",
        "label": "Places: Phone Number"
      },
      {
        "key": "places[]website",
        "label": "Places: Website"
      },
      {
        "key": "places[]domain",
        "label": "Places: Domain"
      },
      {
        "key": "places[]rating",
        "label": "Places: Rating",
        "type": "number"
      },
      {
        "key": "places[]review_count",
        "label": "Places: Review Count",
        "type": "number"
      },
      {
        "key": "places[]reviews_per_rating__1",
        "label": "Reviews Per Rating 1",
        "type": "number"
      },
      {
        "key": "places[]reviews_per_rating__2",
        "label": "Reviews Per Rating 2",
        "type": "number"
      },
      {
        "key": "places[]reviews_per_rating__3",
        "label": "Reviews Per Rating 3",
        "type": "number"
      },
      {
        "key": "places[]reviews_per_rating__4",
        "label": "Reviews Per Rating 4",
        "type": "number"
      },
      {
        "key": "places[]reviews_per_rating__5",
        "label": "Reviews Per Rating 5",
        "type": "number"
      },
      {
        "key": "places[]price_level",
        "label": "Places: Price Level"
      },
      {
        "key": "places[]verified",
        "label": "Places: Verified",
        "type": "boolean"
      },
      {
        "key": "places[]business_status",
        "label": "Places: Business Status"
      },
      {
        "key": "places[]opening_status",
        "label": "Places: Opening Status"
      },
      {
        "key": "places[]working_hours__Monday",
        "label": "Working Hours Monday",
        "list": true
      },
      {
        "key": "places[]working_hours__Sunday",
        "label": "Working Hours Sunday",
        "list": true
      },
      {
        "key": "places[]opening_date",
        "label": "Places: Opening Date"
      },
      {
        "key": "places[]address",
        "label": "Places: Address"
      },
      {
        "key": "places[]street_address",
        "label": "Places: Street Address"
      },
      {
        "key": "places[]district",
        "label": "Places: District"
      },
      {
        "key": "places[]city",
        "label": "Places: City"
      },
      {
        "key": "places[]state",
        "label": "Places: State"
      },
      {
        "key": "places[]zipcode",
        "label": "Places: Zipcode"
      },
      {
        "key": "places[]country",
        "label": "Places: Country"
      },
      {
        "key": "places[]latitude",
        "label": "Places: Latitude",
        "type": "number"
      },
      {
        "key": "places[]longitude",
        "label": "Places: Longitude",
        "type": "number"
      },
      {
        "key": "places[]timezone",
        "label": "Places: Timezone"
      },
      {
        "key": "places[]summary",
        "label": "Places: Summary"
      },
      {
        "key": "places[]about__summary",
        "label": "About Summary"
      },
      {
        "key": "places[]photo_count",
        "label": "Places: Photo Count",
        "type": "number"
      },
      {
        "key": "places[]photos_sample[]photo_id",
        "label": "Photos Sample: Photo ID"
      },
      {
        "key": "places[]photos_sample[]type",
        "label": "Photos Sample: Type"
      },
      {
        "key": "places[]photos_sample[]photo_url",
        "label": "Photos Sample: Photo URL"
      },
      {
        "key": "places[]photos_sample[]photo_url_large",
        "label": "Photos Sample: Photo URL Large"
      },
      {
        "key": "places[]photos_sample[]video_thumbnail_url",
        "label": "Photos Sample: Video Thumbnail URL"
      },
      {
        "key": "places[]photos_sample[]latitude",
        "label": "Photos Sample: Latitude",
        "type": "number"
      },
      {
        "key": "places[]photos_sample[]longitude",
        "label": "Photos Sample: Longitude",
        "type": "number"
      },
      {
        "key": "places[]photos_sample[]photo_datetime_utc",
        "label": "Photos Sample: Photo Datetime UTC"
      },
      {
        "key": "places[]photos_sample[]photo_timestamp",
        "label": "Photos Sample: Photo Timestamp",
        "type": "number"
      },
      {
        "key": "places[]place_link",
        "label": "Places: Place Link"
      },
      {
        "key": "places[]reviews_link",
        "label": "Places: Reviews Link"
      },
      {
        "key": "places[]booking_link",
        "label": "Places: Booking Link"
      },
      {
        "key": "places[]reservations_link",
        "label": "Places: Reservations Link"
      },
      {
        "key": "places[]order_link",
        "label": "Places: Order Link"
      },
      {
        "key": "places[]owner_name",
        "label": "Places: Owner Name"
      },
      {
        "key": "places[]owner_link",
        "label": "Places: Owner Link"
      },
      {
        "key": "places[]cid",
        "label": "Places: Cid"
      },
      {
        "key": "count",
        "label": "Count",
        "type": "number"
      },
      {
        "key": "query",
        "label": "Query"
      },
      {
        "key": "pages",
        "label": "Pages",
        "type": "number"
      }
    ],
    "trigger": {
      "label": "New Google Place Matching Search",
      "description": "Triggers when a new place matches your Google Maps search. Each check runs Search Google Places ($0.01 per page).",
      "inputFields": [
        {
          "key": "query",
          "label": "Search Query",
          "required": true,
          "type": "string",
          "helpText": "Search keyword (max 500 characters). E.g. `coffee shops brooklyn`, `dentists 90210`, `hilton hotels paris`",
          "placeholder": "pizza new york"
        },
        {
          "key": "pages",
          "label": "Pages to Fetch",
          "required": false,
          "type": "integer",
          "default": "1",
          "helpText": "Number of pages to fetch and merge. Each page returns up to 10 results and is billed as one request (1-20). Every check of this trigger fetches this many pages, each billed as one request.",
          "placeholder": "2"
        },
        {
          "key": "limit",
          "label": "Limit",
          "required": false,
          "type": "integer",
          "helpText": "Alternative to `pages`: maximum number of results, rounded up to whole pages of 10 (e.g. `limit=15` fetches 2 pages, so up to 20 results). Ignored when `pages` is also sent. Maximum 200 (1-200)."
        },
        {
          "key": "lat",
          "label": "Latitude",
          "required": false,
          "type": "number",
          "helpText": "Center latitude for geographic bias (provide with `lng`)"
        },
        {
          "key": "lng",
          "label": "Longitude",
          "required": false,
          "type": "number",
          "helpText": "Center longitude for geographic bias (provide with `lat`)"
        },
        {
          "key": "zoom",
          "label": "Zoom",
          "required": false,
          "type": "integer",
          "helpText": "Map zoom level. Smaller values widen the search radius (13 ≈ city, 15 ≈ neighborhood, 10 ≈ metro area) (1-20)."
        },
        {
          "key": "country",
          "label": "Country",
          "required": false,
          "type": "string",
          "default": "us",
          "helpText": "2-letter ISO 3166-1 alpha-2 region code (up to 2 characters)."
        },
        {
          "key": "language",
          "label": "Language",
          "required": false,
          "type": "string",
          "default": "en",
          "helpText": "2-letter ISO 639-1 language code (up to 2 characters)."
        }
      ],
      "sample": {
        "id": "ChIJifIePKtZwokRVZ-UdRGkZzs",
        "place_id": "ChIJifIePKtZwokRVZ-UdRGkZzs",
        "name": "Joe's Pizza Broadway",
        "type": "Pizza restaurant",
        "subtypes": [
          "Pizza restaurant",
          "Pizza delivery",
          "Restaurant"
        ],
        "phone_number": "+16465550142",
        "website": "https://www.joespizzanyc.com",
        "domain": "joespizzanyc.com",
        "rating": 4.5,
        "review_count": 25433,
        "reviews_per_rating": {
          "1": 753,
          "2": 604,
          "3": 2107,
          "4": 4946,
          "5": 17023
        },
        "price_level": "$10–20",
        "verified": true,
        "business_status": "OPEN",
        "opening_status": "Open · Closes 3 AM",
        "working_hours": {
          "Monday": [
            "10 AM–3 AM"
          ],
          "Sunday": [
            "10 AM–3 AM"
          ]
        },
        "opening_date": null,
        "address": "Joe's Pizza Broadway, 1435 Broadway, New York, NY 10018",
        "street_address": "1435 Broadway",
        "district": "Manhattan",
        "city": "New York",
        "state": "New York",
        "zipcode": "10018",
        "country": "US",
        "latitude": 40.75468,
        "longitude": -73.98703,
        "timezone": "America/New_York",
        "summary": "Modern outpost of a longtime counter-serve pizza joint prepping New York-style slices and pies.",
        "about": {
          "summary": "Modern outpost of a longtime counter-serve pizza joint prepping New York-style slices and pies.",
          "details": {
            "Accessibility": {
              "Wheelchair accessible entrance": true,
              "Wheelchair accessible parking lot": false,
              "Wheelchair accessible seating": false
            }
          }
        },
        "photo_count": 22117,
        "photos_sample": [
          {
            "photo_id": "CIABIhBpKlqRIOpwhdI384bUAF4L",
            "type": "photo",
            "photo_url": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAH...",
            "photo_url_large": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAH...=w3000-h4000-k-no",
            "video_thumbnail_url": null,
            "latitude": 40.7546469,
            "longitude": -73.9868158,
            "photo_datetime_utc": "2026-06-16T00:00:00.000Z",
            "photo_timestamp": 1781568000
          }
        ],
        "place_link": "https://www.google.com/maps/place/data=...",
        "reviews_link": "https://search.google.com/local/reviews?placeid=ChIJifIePKtZwokRVZ-UdRGkZzs",
        "booking_link": "https://www.google.com/searchviewer/42?...",
        "reservations_link": "https://www.fooddiscoveryapp.com/new-york-city/joes-pizza",
        "order_link": "https://www.google.com/searchviewer/42?...",
        "owner_name": "Joe's Pizza Broadway",
        "owner_link": "https://maps.google.com/maps/contrib/103877821925204408966",
        "cid": "4280570365733019477"
      },
      "outputFields": [
        {
          "key": "id",
          "label": "ID",
          "primary": true
        },
        {
          "key": "place_id",
          "label": "Place ID"
        },
        {
          "key": "name",
          "label": "Name"
        },
        {
          "key": "type",
          "label": "Type"
        },
        {
          "key": "subtypes",
          "label": "Subtypes",
          "list": true
        },
        {
          "key": "phone_number",
          "label": "Phone Number"
        },
        {
          "key": "website",
          "label": "Website"
        },
        {
          "key": "domain",
          "label": "Domain"
        },
        {
          "key": "rating",
          "label": "Rating",
          "type": "number"
        },
        {
          "key": "review_count",
          "label": "Review Count",
          "type": "number"
        },
        {
          "key": "reviews_per_rating__1",
          "label": "Reviews Per Rating 1",
          "type": "number"
        },
        {
          "key": "reviews_per_rating__2",
          "label": "Reviews Per Rating 2",
          "type": "number"
        },
        {
          "key": "reviews_per_rating__3",
          "label": "Reviews Per Rating 3",
          "type": "number"
        },
        {
          "key": "reviews_per_rating__4",
          "label": "Reviews Per Rating 4",
          "type": "number"
        },
        {
          "key": "reviews_per_rating__5",
          "label": "Reviews Per Rating 5",
          "type": "number"
        },
        {
          "key": "price_level",
          "label": "Price Level"
        },
        {
          "key": "verified",
          "label": "Verified",
          "type": "boolean"
        },
        {
          "key": "business_status",
          "label": "Business Status"
        },
        {
          "key": "opening_status",
          "label": "Opening Status"
        },
        {
          "key": "working_hours__Monday",
          "label": "Working Hours Monday",
          "list": true
        },
        {
          "key": "working_hours__Sunday",
          "label": "Working Hours Sunday",
          "list": true
        },
        {
          "key": "opening_date",
          "label": "Opening Date"
        },
        {
          "key": "address",
          "label": "Address"
        },
        {
          "key": "street_address",
          "label": "Street Address"
        },
        {
          "key": "district",
          "label": "District"
        },
        {
          "key": "city",
          "label": "City"
        },
        {
          "key": "state",
          "label": "State"
        },
        {
          "key": "zipcode",
          "label": "Zipcode"
        },
        {
          "key": "country",
          "label": "Country"
        },
        {
          "key": "latitude",
          "label": "Latitude",
          "type": "number"
        },
        {
          "key": "longitude",
          "label": "Longitude",
          "type": "number"
        },
        {
          "key": "timezone",
          "label": "Timezone"
        },
        {
          "key": "summary",
          "label": "Summary"
        },
        {
          "key": "about__summary",
          "label": "About Summary"
        },
        {
          "key": "photo_count",
          "label": "Photo Count",
          "type": "number"
        },
        {
          "key": "photos_sample[]photo_id",
          "label": "Photos Sample: Photo ID"
        },
        {
          "key": "photos_sample[]type",
          "label": "Photos Sample: Type"
        },
        {
          "key": "photos_sample[]photo_url",
          "label": "Photos Sample: Photo URL"
        },
        {
          "key": "photos_sample[]photo_url_large",
          "label": "Photos Sample: Photo URL Large"
        },
        {
          "key": "photos_sample[]video_thumbnail_url",
          "label": "Photos Sample: Video Thumbnail URL"
        },
        {
          "key": "photos_sample[]latitude",
          "label": "Photos Sample: Latitude",
          "type": "number"
        },
        {
          "key": "photos_sample[]longitude",
          "label": "Photos Sample: Longitude",
          "type": "number"
        },
        {
          "key": "photos_sample[]photo_datetime_utc",
          "label": "Photos Sample: Photo Datetime UTC"
        },
        {
          "key": "photos_sample[]photo_timestamp",
          "label": "Photos Sample: Photo Timestamp",
          "type": "number"
        },
        {
          "key": "place_link",
          "label": "Place Link"
        },
        {
          "key": "reviews_link",
          "label": "Reviews Link"
        },
        {
          "key": "booking_link",
          "label": "Booking Link"
        },
        {
          "key": "reservations_link",
          "label": "Reservations Link"
        },
        {
          "key": "order_link",
          "label": "Order Link"
        },
        {
          "key": "owner_name",
          "label": "Owner Name"
        },
        {
          "key": "owner_link",
          "label": "Owner Link"
        },
        {
          "key": "cid",
          "label": "Cid"
        }
      ]
    }
  },
  {
    "key": "places_details",
    "path": "/v1/places/details",
    "method": "GET",
    "platform": "Google Places",
    "noun": "Place",
    "kind": "detail",
    "listKey": null,
    "idFields": null,
    "unwrapKey": "place",
    "docs": "https://apidirect.io/docs/places-details",
    "action": {
      "label": "Find Google Place",
      "description": "Gets full details for a single Google Maps place by place_id. Returns everything Places Search returns, plus Plus Codes, a menu link, and an emails_and_contacts scrape of the place's official website (emails, phone numbers and links to Facebook, Instagram, LinkedIn, Twitter/X, TikTok, YouTube, Pinterest, Snapchat, Yelp, and GitHub). The emails_and_contacts block is always present: emails and phone_numbers come back as empty arrays and each social link as null when nothing is found. $0.003 per request after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "place_id",
        "label": "Place ID",
        "required": true,
        "type": "string",
        "helpText": "Google `place_id` (e.g. `ChIJifIePKtZwokRVZ-UdRGkZzs`), as returned by the Places Search endpoint (up to 200 characters).",
        "placeholder": "ChIJifIePKtZwokRVZ-UdRGkZzs"
      },
      {
        "key": "country",
        "label": "Country",
        "required": false,
        "type": "string",
        "default": "us",
        "helpText": "2-letter ISO 3166-1 alpha-2 region code (up to 2 characters)."
      },
      {
        "key": "language",
        "label": "Language",
        "required": false,
        "type": "string",
        "default": "en",
        "helpText": "2-letter ISO 639-1 language code (up to 2 characters)."
      }
    ],
    "sample": {
      "place_id": "ChIJifIePKtZwokRVZ-UdRGkZzs",
      "name": "Joe's Pizza Broadway",
      "type": "Pizza restaurant",
      "subtypes": [
        "Pizza restaurant",
        "Pizza delivery",
        "Restaurant"
      ],
      "phone_number": "+16465550142",
      "website": "https://www.joespizzanyc.com",
      "domain": "joespizzanyc.com",
      "rating": 4.5,
      "review_count": 25433,
      "reviews_per_rating": {
        "1": 753,
        "2": 604,
        "3": 2107,
        "4": 4946,
        "5": 17023
      },
      "price_level": "$10–20",
      "verified": true,
      "business_status": "OPEN",
      "opening_status": "Open · Closes 3 AM",
      "working_hours": {
        "Monday": [
          "10 AM–3 AM"
        ]
      },
      "opening_date": null,
      "address": "1435 Broadway, New York, NY 10018",
      "street_address": "1435 Broadway",
      "district": "Manhattan",
      "city": "New York",
      "state": "New York",
      "zipcode": "10018",
      "country": "US",
      "latitude": 40.75468,
      "longitude": -73.98703,
      "timezone": "America/New_York",
      "summary": "Modern outpost of a longtime counter-serve pizza joint prepping New York-style slices and pies.",
      "about": {
        "summary": "Modern outpost of a longtime counter-serve pizza joint prepping New York-style slices and pies.",
        "details": {
          "Accessibility": {
            "Wheelchair accessible entrance": true,
            "Wheelchair accessible parking lot": false,
            "Wheelchair accessible seating": false
          }
        }
      },
      "photo_count": 22117,
      "photos_sample": [
        {
          "photo_id": "CIABIhAViB6GuQB0Czq6u1UIyD60",
          "type": "photo",
          "photo_url": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAH...",
          "photo_url_large": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAH...=w4280-h3407-k-no",
          "video_thumbnail_url": null,
          "latitude": 40.7546469,
          "longitude": -73.9868158,
          "photo_datetime_utc": "2026-05-30T00:00:00.000Z",
          "photo_timestamp": 1780099200
        }
      ],
      "place_link": "https://www.google.com/maps/place/...",
      "reviews_link": "https://search.google.com/local/reviews?placeid=ChIJifIePKtZwokRVZ-UdRGkZzs",
      "booking_link": "https://www.google.com/searchviewer/42?...",
      "reservations_link": "https://www.fooddiscoveryapp.com/new-york-city/joes-pizza",
      "order_link": "https://www.google.com/searchviewer/42?...",
      "owner_name": "Joe's Pizza Broadway",
      "owner_link": "https://maps.google.com/maps/contrib/103877821925204408966",
      "cid": "4280570365733019477",
      "global_plus_code": "87G8Q237+V5",
      "compound_plus_code": "Q237+V5 New York",
      "menu_link": null,
      "emails_and_contacts": {
        "emails": [],
        "phone_numbers": [
          "2123661182",
          "7183882216",
          "2122670860"
        ],
        "facebook": null,
        "instagram": "https://www.instagram.com/joespizzanyc",
        "linkedin": null,
        "twitter": null,
        "tiktok": null,
        "youtube": null,
        "pinterest": null,
        "snapchat": null,
        "yelp": null,
        "github": null
      }
    },
    "outputFields": [
      {
        "key": "place_id",
        "label": "Place ID"
      },
      {
        "key": "name",
        "label": "Name"
      },
      {
        "key": "type",
        "label": "Type"
      },
      {
        "key": "subtypes",
        "label": "Subtypes",
        "list": true
      },
      {
        "key": "phone_number",
        "label": "Phone Number"
      },
      {
        "key": "website",
        "label": "Website"
      },
      {
        "key": "domain",
        "label": "Domain"
      },
      {
        "key": "rating",
        "label": "Rating",
        "type": "number"
      },
      {
        "key": "review_count",
        "label": "Review Count",
        "type": "number"
      },
      {
        "key": "reviews_per_rating__1",
        "label": "Reviews Per Rating 1",
        "type": "number"
      },
      {
        "key": "reviews_per_rating__2",
        "label": "Reviews Per Rating 2",
        "type": "number"
      },
      {
        "key": "reviews_per_rating__3",
        "label": "Reviews Per Rating 3",
        "type": "number"
      },
      {
        "key": "reviews_per_rating__4",
        "label": "Reviews Per Rating 4",
        "type": "number"
      },
      {
        "key": "reviews_per_rating__5",
        "label": "Reviews Per Rating 5",
        "type": "number"
      },
      {
        "key": "price_level",
        "label": "Price Level"
      },
      {
        "key": "verified",
        "label": "Verified",
        "type": "boolean"
      },
      {
        "key": "business_status",
        "label": "Business Status"
      },
      {
        "key": "opening_status",
        "label": "Opening Status"
      },
      {
        "key": "working_hours__Monday",
        "label": "Working Hours Monday",
        "list": true
      },
      {
        "key": "opening_date",
        "label": "Opening Date"
      },
      {
        "key": "address",
        "label": "Address"
      },
      {
        "key": "street_address",
        "label": "Street Address"
      },
      {
        "key": "district",
        "label": "District"
      },
      {
        "key": "city",
        "label": "City"
      },
      {
        "key": "state",
        "label": "State"
      },
      {
        "key": "zipcode",
        "label": "Zipcode"
      },
      {
        "key": "country",
        "label": "Country"
      },
      {
        "key": "latitude",
        "label": "Latitude",
        "type": "number"
      },
      {
        "key": "longitude",
        "label": "Longitude",
        "type": "number"
      },
      {
        "key": "timezone",
        "label": "Timezone"
      },
      {
        "key": "summary",
        "label": "Summary"
      },
      {
        "key": "about__summary",
        "label": "About Summary"
      },
      {
        "key": "photo_count",
        "label": "Photo Count",
        "type": "number"
      },
      {
        "key": "photos_sample[]photo_id",
        "label": "Photos Sample: Photo ID"
      },
      {
        "key": "photos_sample[]type",
        "label": "Photos Sample: Type"
      },
      {
        "key": "photos_sample[]photo_url",
        "label": "Photos Sample: Photo URL"
      },
      {
        "key": "photos_sample[]photo_url_large",
        "label": "Photos Sample: Photo URL Large"
      },
      {
        "key": "photos_sample[]video_thumbnail_url",
        "label": "Photos Sample: Video Thumbnail URL"
      },
      {
        "key": "photos_sample[]latitude",
        "label": "Photos Sample: Latitude",
        "type": "number"
      },
      {
        "key": "photos_sample[]longitude",
        "label": "Photos Sample: Longitude",
        "type": "number"
      },
      {
        "key": "photos_sample[]photo_datetime_utc",
        "label": "Photos Sample: Photo Datetime UTC"
      },
      {
        "key": "photos_sample[]photo_timestamp",
        "label": "Photos Sample: Photo Timestamp",
        "type": "number"
      },
      {
        "key": "place_link",
        "label": "Place Link"
      },
      {
        "key": "reviews_link",
        "label": "Reviews Link"
      },
      {
        "key": "booking_link",
        "label": "Booking Link"
      },
      {
        "key": "reservations_link",
        "label": "Reservations Link"
      },
      {
        "key": "order_link",
        "label": "Order Link"
      },
      {
        "key": "owner_name",
        "label": "Owner Name"
      },
      {
        "key": "owner_link",
        "label": "Owner Link"
      },
      {
        "key": "cid",
        "label": "Cid"
      },
      {
        "key": "global_plus_code",
        "label": "Global Plus Code"
      },
      {
        "key": "compound_plus_code",
        "label": "Compound Plus Code"
      },
      {
        "key": "menu_link",
        "label": "Menu Link"
      },
      {
        "key": "emails_and_contacts__emails",
        "label": "Emails And Contacts Emails",
        "list": true
      },
      {
        "key": "emails_and_contacts__phone_numbers",
        "label": "Emails And Contacts Phone Numbers",
        "list": true
      },
      {
        "key": "emails_and_contacts__facebook",
        "label": "Emails And Contacts Facebook"
      },
      {
        "key": "emails_and_contacts__instagram",
        "label": "Emails And Contacts Instagram"
      },
      {
        "key": "emails_and_contacts__linkedin",
        "label": "Emails And Contacts Linkedin"
      },
      {
        "key": "emails_and_contacts__twitter",
        "label": "Emails And Contacts Twitter"
      },
      {
        "key": "emails_and_contacts__tiktok",
        "label": "Emails And Contacts Tiktok"
      },
      {
        "key": "emails_and_contacts__youtube",
        "label": "Emails And Contacts Youtube"
      },
      {
        "key": "emails_and_contacts__pinterest",
        "label": "Emails And Contacts Pinterest"
      },
      {
        "key": "emails_and_contacts__snapchat",
        "label": "Emails And Contacts Snapchat"
      },
      {
        "key": "emails_and_contacts__yelp",
        "label": "Emails And Contacts Yelp"
      },
      {
        "key": "emails_and_contacts__github",
        "label": "Emails And Contacts Github"
      }
    ],
    "trigger": null
  },
  {
    "key": "places_reviews",
    "path": "/v1/places/reviews",
    "method": "GET",
    "platform": "Google Places",
    "noun": "Review",
    "kind": "list",
    "listKey": "reviews",
    "idFields": [
      "review_id",
      "review_link"
    ],
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/places-reviews",
    "action": {
      "label": "Get Google Place Reviews",
      "description": "Gets user reviews for a place by place_id. Each review includes the rating, full review text, author info (with photo URL, total review count, and Local Guide level), timestamps, attached photos, and any owner response (owner_response is null when the owner has not replied, otherwise an object with text, datetime_utc, timestamp, time and language). Sort by most relevant, newest, highest ranking, or lowest ranking. Set translate_reviews=true to translate all returned reviews into the requested language, and get_sentiment=true to add AI emotion analysis to each review. Each page returns up to 10 reviews and is billed as one request, up to 10 pages per call. $0.01 per page after the free tier (20 requests/month)."
    },
    "inputFields": [
      {
        "key": "place_id",
        "label": "Place ID",
        "required": true,
        "type": "string",
        "helpText": "Google `place_id`, as returned by the Places Search endpoint (up to 200 characters).",
        "placeholder": "ChIJifIePKtZwokRVZ-UdRGkZzs"
      },
      {
        "key": "pages",
        "label": "Pages to Fetch",
        "required": false,
        "type": "integer",
        "default": "1",
        "helpText": "Number of pages to fetch and merge. Each page returns up to 10 reviews and is billed as one request (1-10).",
        "placeholder": "2"
      },
      {
        "key": "limit",
        "label": "Limit",
        "required": false,
        "type": "integer",
        "helpText": "Alternative to `pages`: maximum number of reviews, rounded up to whole pages of 10 (e.g. `limit=15` fetches 2 pages, so up to 20 reviews). Ignored when `pages` is also sent. Maximum 100 (1-100)."
      },
      {
        "key": "sort_by",
        "label": "Sort By",
        "required": false,
        "type": "string",
        "default": "most_relevant",
        "helpText": "Sort order for reviews",
        "choices": {
          "most_relevant": "Most Relevant",
          "newest": "Newest",
          "highest_ranking": "Highest Ranking",
          "lowest_ranking": "Lowest Ranking"
        },
        "placeholder": "newest"
      },
      {
        "key": "language",
        "label": "Language",
        "required": false,
        "type": "string",
        "default": "en",
        "helpText": "2-letter ISO 639-1 language code for the returned reviews. Set `translate_reviews=true` to translate the returned reviews into this language (up to 2 characters)."
      },
      {
        "key": "translate_reviews",
        "label": "Translate Reviews",
        "required": false,
        "type": "boolean",
        "helpText": "Set to `true` to translate the returned reviews into the requested `language`"
      },
      {
        "key": "country",
        "label": "Country",
        "required": false,
        "type": "string",
        "default": "us",
        "helpText": "2-letter ISO 3166-1 alpha-2 region code (up to 2 characters)."
      },
      {
        "key": "get_sentiment",
        "label": "Add Sentiment Analysis",
        "required": false,
        "type": "boolean",
        "helpText": "Set to true to add AI emotion analysis to each review. Adds a `sentiment` object containing `emotions` (joy, trust, fear, surprise, sadness, disgust, anger and anticipation, each scored 0-100), `dominant_emotion`, `emotional_intensity` (0-10), and `polarity` (positive, negative or neutral). Any review that cannot be scored returns `sentiment: null`."
      }
    ],
    "sample": {
      "reviews": [
        {
          "review_id": "Ci9DQUlRQUNvZENodHljRjlvT2pWeU1rdFZhREZPY214dmRVSlplRzQ0ZURWVk9XYxAB",
          "rating": 5,
          "review_text": "Amazing pizza, fast service. Highly recommend.",
          "review_datetime_utc": "2026-02-15T12:05:54.947Z",
          "review_timestamp": 1771157154,
          "review_time": "3 months ago",
          "review_link": "https://www.google.com/maps/reviews/...",
          "review_photos": [
            "https://lh3.googleusercontent.com/grass-cs/..."
          ],
          "review_language": "en",
          "review_text_translated_language": "en",
          "like_count": 0,
          "review_source": "Google",
          "review_source_logo": "https://www.gstatic.com/images/branding/product/1x/googleg_48dp.png",
          "author_id": "103696814314978516852",
          "author_name": "Salman Idrees",
          "author_link": "https://www.google.com/maps/contrib/103696814314978516852",
          "author_photo_url": "https://lh3.googleusercontent.com/a-/ALV-...",
          "author_review_count": 392,
          "author_photo_count": 356,
          "author_reviews_link": "https://www.google.com/maps/contrib/103696814314978516852/reviews",
          "author_is_local_guide": true,
          "author_local_guide_level": 7,
          "owner_response": null
        }
      ],
      "count": 1,
      "pages": 2,
      "sort_by": "newest"
    },
    "outputFields": [
      {
        "key": "reviews[]review_id",
        "label": "Reviews: Review ID"
      },
      {
        "key": "reviews[]rating",
        "label": "Reviews: Rating",
        "type": "number"
      },
      {
        "key": "reviews[]review_text",
        "label": "Reviews: Review Text"
      },
      {
        "key": "reviews[]review_datetime_utc",
        "label": "Reviews: Review Datetime UTC"
      },
      {
        "key": "reviews[]review_timestamp",
        "label": "Reviews: Review Timestamp",
        "type": "number"
      },
      {
        "key": "reviews[]review_time",
        "label": "Reviews: Review Time"
      },
      {
        "key": "reviews[]review_link",
        "label": "Reviews: Review Link"
      },
      {
        "key": "reviews[]review_photos",
        "label": "Reviews: Review Photos",
        "list": true
      },
      {
        "key": "reviews[]review_language",
        "label": "Reviews: Review Language"
      },
      {
        "key": "reviews[]review_text_translated_language",
        "label": "Reviews: Review Text Translated Language"
      },
      {
        "key": "reviews[]like_count",
        "label": "Reviews: Like Count",
        "type": "number"
      },
      {
        "key": "reviews[]review_source",
        "label": "Reviews: Review Source"
      },
      {
        "key": "reviews[]review_source_logo",
        "label": "Reviews: Review Source Logo"
      },
      {
        "key": "reviews[]author_id",
        "label": "Reviews: Author ID"
      },
      {
        "key": "reviews[]author_name",
        "label": "Reviews: Author Name"
      },
      {
        "key": "reviews[]author_link",
        "label": "Reviews: Author Link"
      },
      {
        "key": "reviews[]author_photo_url",
        "label": "Reviews: Author Photo URL"
      },
      {
        "key": "reviews[]author_review_count",
        "label": "Reviews: Author Review Count",
        "type": "number"
      },
      {
        "key": "reviews[]author_photo_count",
        "label": "Reviews: Author Photo Count",
        "type": "number"
      },
      {
        "key": "reviews[]author_reviews_link",
        "label": "Reviews: Author Reviews Link"
      },
      {
        "key": "reviews[]author_is_local_guide",
        "label": "Reviews: Author Is Local Guide",
        "type": "boolean"
      },
      {
        "key": "reviews[]author_local_guide_level",
        "label": "Reviews: Author Local Guide Level",
        "type": "number"
      },
      {
        "key": "reviews[]owner_response",
        "label": "Reviews: Owner Response"
      },
      {
        "key": "count",
        "label": "Count",
        "type": "number"
      },
      {
        "key": "pages",
        "label": "Pages",
        "type": "number"
      },
      {
        "key": "sort_by",
        "label": "Sort By"
      }
    ],
    "trigger": {
      "label": "New Google Place Review",
      "description": "Triggers when a place gets a new Google Maps review. Each check runs Get Google Place Reviews ($0.01 per page).",
      "inputFields": [
        {
          "key": "place_id",
          "label": "Place ID",
          "required": true,
          "type": "string",
          "helpText": "Google `place_id`, as returned by the Places Search endpoint (up to 200 characters).",
          "placeholder": "ChIJifIePKtZwokRVZ-UdRGkZzs"
        },
        {
          "key": "pages",
          "label": "Pages to Fetch",
          "required": false,
          "type": "integer",
          "default": "1",
          "helpText": "Number of pages to fetch and merge. Each page returns up to 10 reviews and is billed as one request (1-10). Every check of this trigger fetches this many pages, each billed as one request.",
          "placeholder": "2"
        },
        {
          "key": "limit",
          "label": "Limit",
          "required": false,
          "type": "integer",
          "helpText": "Alternative to `pages`: maximum number of reviews, rounded up to whole pages of 10 (e.g. `limit=15` fetches 2 pages, so up to 20 reviews). Ignored when `pages` is also sent. Maximum 100 (1-100)."
        },
        {
          "key": "sort_by",
          "label": "Sort By",
          "required": false,
          "type": "string",
          "default": "most_relevant",
          "helpText": "Sort order for reviews",
          "choices": {
            "most_relevant": "Most Relevant",
            "newest": "Newest",
            "highest_ranking": "Highest Ranking",
            "lowest_ranking": "Lowest Ranking"
          },
          "placeholder": "newest"
        },
        {
          "key": "language",
          "label": "Language",
          "required": false,
          "type": "string",
          "default": "en",
          "helpText": "2-letter ISO 639-1 language code for the returned reviews. Set `translate_reviews=true` to translate the returned reviews into this language (up to 2 characters)."
        },
        {
          "key": "translate_reviews",
          "label": "Translate Reviews",
          "required": false,
          "type": "boolean",
          "helpText": "Set to `true` to translate the returned reviews into the requested `language`"
        },
        {
          "key": "country",
          "label": "Country",
          "required": false,
          "type": "string",
          "default": "us",
          "helpText": "2-letter ISO 3166-1 alpha-2 region code (up to 2 characters)."
        },
        {
          "key": "get_sentiment",
          "label": "Add Sentiment Analysis",
          "required": false,
          "type": "boolean",
          "helpText": "Set to true to add AI emotion analysis to each review. Adds a `sentiment` object containing `emotions` (joy, trust, fear, surprise, sadness, disgust, anger and anticipation, each scored 0-100), `dominant_emotion`, `emotional_intensity` (0-10), and `polarity` (positive, negative or neutral). Any review that cannot be scored returns `sentiment: null`."
        }
      ],
      "sample": {
        "id": "Ci9DQUlRQUNvZENodHljRjlvT2pWeU1rdFZhREZPY214dmRVSlplRzQ0ZURWVk9XYxAB",
        "review_id": "Ci9DQUlRQUNvZENodHljRjlvT2pWeU1rdFZhREZPY214dmRVSlplRzQ0ZURWVk9XYxAB",
        "rating": 5,
        "review_text": "Amazing pizza, fast service. Highly recommend.",
        "review_datetime_utc": "2026-02-15T12:05:54.947Z",
        "review_timestamp": 1771157154,
        "review_time": "3 months ago",
        "review_link": "https://www.google.com/maps/reviews/...",
        "review_photos": [
          "https://lh3.googleusercontent.com/grass-cs/..."
        ],
        "review_language": "en",
        "review_text_translated_language": "en",
        "like_count": 0,
        "review_source": "Google",
        "review_source_logo": "https://www.gstatic.com/images/branding/product/1x/googleg_48dp.png",
        "author_id": "103696814314978516852",
        "author_name": "Salman Idrees",
        "author_link": "https://www.google.com/maps/contrib/103696814314978516852",
        "author_photo_url": "https://lh3.googleusercontent.com/a-/ALV-...",
        "author_review_count": 392,
        "author_photo_count": 356,
        "author_reviews_link": "https://www.google.com/maps/contrib/103696814314978516852/reviews",
        "author_is_local_guide": true,
        "author_local_guide_level": 7,
        "owner_response": null
      },
      "outputFields": [
        {
          "key": "id",
          "label": "ID",
          "primary": true
        },
        {
          "key": "review_id",
          "label": "Review ID"
        },
        {
          "key": "rating",
          "label": "Rating",
          "type": "number"
        },
        {
          "key": "review_text",
          "label": "Review Text"
        },
        {
          "key": "review_datetime_utc",
          "label": "Review Datetime UTC"
        },
        {
          "key": "review_timestamp",
          "label": "Review Timestamp",
          "type": "number"
        },
        {
          "key": "review_time",
          "label": "Review Time"
        },
        {
          "key": "review_link",
          "label": "Review Link"
        },
        {
          "key": "review_photos",
          "label": "Review Photos",
          "list": true
        },
        {
          "key": "review_language",
          "label": "Review Language"
        },
        {
          "key": "review_text_translated_language",
          "label": "Review Text Translated Language"
        },
        {
          "key": "like_count",
          "label": "Like Count",
          "type": "number"
        },
        {
          "key": "review_source",
          "label": "Review Source"
        },
        {
          "key": "review_source_logo",
          "label": "Review Source Logo"
        },
        {
          "key": "author_id",
          "label": "Author ID"
        },
        {
          "key": "author_name",
          "label": "Author Name"
        },
        {
          "key": "author_link",
          "label": "Author Link"
        },
        {
          "key": "author_photo_url",
          "label": "Author Photo URL"
        },
        {
          "key": "author_review_count",
          "label": "Author Review Count",
          "type": "number"
        },
        {
          "key": "author_photo_count",
          "label": "Author Photo Count",
          "type": "number"
        },
        {
          "key": "author_reviews_link",
          "label": "Author Reviews Link"
        },
        {
          "key": "author_is_local_guide",
          "label": "Author Is Local Guide",
          "type": "boolean"
        },
        {
          "key": "author_local_guide_level",
          "label": "Author Local Guide Level",
          "type": "number"
        },
        {
          "key": "owner_response",
          "label": "Owner Response"
        }
      ]
    }
  },
  {
    "key": "places_photos",
    "path": "/v1/places/photos",
    "method": "GET",
    "platform": "Google Places",
    "noun": "Photo",
    "kind": "list",
    "listKey": "photos",
    "idFields": [
      "photo_id",
      "photo_url"
    ],
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/places-photos",
    "action": {
      "label": "Get Google Place Photos",
      "description": "Gets photos and videos for a place by place_id. Returns photo URLs (standard and high-resolution), capture coordinates, and timestamps. Filter on the type field if you only want photos or only videos. Each page returns up to 10 items and is billed as one request, up to 10 pages per call. $0.01 per page after the free tier (20 requests/month)."
    },
    "inputFields": [
      {
        "key": "place_id",
        "label": "Place ID",
        "required": true,
        "type": "string",
        "helpText": "Google `place_id`, as returned by the Places Search endpoint (up to 200 characters).",
        "placeholder": "ChIJifIePKtZwokRVZ-UdRGkZzs"
      },
      {
        "key": "pages",
        "label": "Pages to Fetch",
        "required": false,
        "type": "integer",
        "default": "1",
        "helpText": "Number of pages to fetch and merge. Each page returns up to 10 items and is billed as one request (1-10).",
        "placeholder": "2"
      },
      {
        "key": "country",
        "label": "Country",
        "required": false,
        "type": "string",
        "default": "us",
        "helpText": "2-letter ISO 3166-1 alpha-2 region code (up to 2 characters)."
      },
      {
        "key": "language",
        "label": "Language",
        "required": false,
        "type": "string",
        "default": "en",
        "helpText": "2-letter ISO 639-1 language code (up to 2 characters)."
      }
    ],
    "sample": {
      "photos": [
        {
          "photo_id": "CIABIhAViB6GuQB0Czq6u1UIyD60",
          "type": "photo",
          "photo_url": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAH...",
          "photo_url_large": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAH...=w4280-h3407-k-no",
          "video_thumbnail_url": null,
          "latitude": 40.7546469,
          "longitude": -73.9868158,
          "photo_datetime_utc": "2026-05-30T00:00:00.000Z",
          "photo_timestamp": 1780099200
        },
        {
          "photo_id": "CIHM0ogKEICAgICGgNfJ4wE",
          "type": "video",
          "photo_url": "https://lh3.googleusercontent.com/gps-cs-s/...",
          "photo_url_large": null,
          "video_thumbnail_url": "https://lh3.googleusercontent.com/gps-cs-s/...=w640-h360-k-no",
          "latitude": 40.7546795,
          "longitude": -73.9870291,
          "photo_datetime_utc": "2021-11-16T00:00:00.000Z",
          "photo_timestamp": 1637020800
        }
      ],
      "count": 20,
      "pages": 2
    },
    "outputFields": [
      {
        "key": "photos[]photo_id",
        "label": "Photos: Photo ID"
      },
      {
        "key": "photos[]type",
        "label": "Photos: Type"
      },
      {
        "key": "photos[]photo_url",
        "label": "Photos: Photo URL"
      },
      {
        "key": "photos[]photo_url_large",
        "label": "Photos: Photo URL Large"
      },
      {
        "key": "photos[]video_thumbnail_url",
        "label": "Photos: Video Thumbnail URL"
      },
      {
        "key": "photos[]latitude",
        "label": "Photos: Latitude",
        "type": "number"
      },
      {
        "key": "photos[]longitude",
        "label": "Photos: Longitude",
        "type": "number"
      },
      {
        "key": "photos[]photo_datetime_utc",
        "label": "Photos: Photo Datetime UTC"
      },
      {
        "key": "photos[]photo_timestamp",
        "label": "Photos: Photo Timestamp",
        "type": "number"
      },
      {
        "key": "count",
        "label": "Count",
        "type": "number"
      },
      {
        "key": "pages",
        "label": "Pages",
        "type": "number"
      }
    ],
    "trigger": {
      "label": "New Google Place Photo",
      "description": "Triggers when a place gets a new Google Maps photo. Each check runs Get Google Place Photos ($0.01 per page).",
      "inputFields": [
        {
          "key": "place_id",
          "label": "Place ID",
          "required": true,
          "type": "string",
          "helpText": "Google `place_id`, as returned by the Places Search endpoint (up to 200 characters).",
          "placeholder": "ChIJifIePKtZwokRVZ-UdRGkZzs"
        },
        {
          "key": "pages",
          "label": "Pages to Fetch",
          "required": false,
          "type": "integer",
          "default": "1",
          "helpText": "Number of pages to fetch and merge. Each page returns up to 10 items and is billed as one request (1-10). Every check of this trigger fetches this many pages, each billed as one request.",
          "placeholder": "2"
        },
        {
          "key": "country",
          "label": "Country",
          "required": false,
          "type": "string",
          "default": "us",
          "helpText": "2-letter ISO 3166-1 alpha-2 region code (up to 2 characters)."
        },
        {
          "key": "language",
          "label": "Language",
          "required": false,
          "type": "string",
          "default": "en",
          "helpText": "2-letter ISO 639-1 language code (up to 2 characters)."
        }
      ],
      "sample": {
        "id": "CIABIhAViB6GuQB0Czq6u1UIyD60",
        "photo_id": "CIABIhAViB6GuQB0Czq6u1UIyD60",
        "type": "photo",
        "photo_url": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAH...",
        "photo_url_large": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAH...=w4280-h3407-k-no",
        "video_thumbnail_url": null,
        "latitude": 40.7546469,
        "longitude": -73.9868158,
        "photo_datetime_utc": "2026-05-30T00:00:00.000Z",
        "photo_timestamp": 1780099200
      },
      "outputFields": [
        {
          "key": "id",
          "label": "ID",
          "primary": true
        },
        {
          "key": "photo_id",
          "label": "Photo ID"
        },
        {
          "key": "type",
          "label": "Type"
        },
        {
          "key": "photo_url",
          "label": "Photo URL"
        },
        {
          "key": "photo_url_large",
          "label": "Photo URL Large"
        },
        {
          "key": "video_thumbnail_url",
          "label": "Video Thumbnail URL"
        },
        {
          "key": "latitude",
          "label": "Latitude",
          "type": "number"
        },
        {
          "key": "longitude",
          "label": "Longitude",
          "type": "number"
        },
        {
          "key": "photo_datetime_utc",
          "label": "Photo Datetime UTC"
        },
        {
          "key": "photo_timestamp",
          "label": "Photo Timestamp",
          "type": "number"
        }
      ]
    }
  }
];
