// Generated by scripts/generate.py from spec/openapi.json. Do not edit by hand;
// change the spec or the generator and run `npm run generate`.
module.exports = [
  ...require('./amazon'),
  ...require('./bluesky'),
  ...require('./facebook'),
  ...require('./forums'),
  ...require('./google-places'),
  ...require('./google-search'),
  ...require('./instagram'),
  ...require('./linkedin'),
  ...require('./news'),
  ...require('./reddit'),
  ...require('./threads'),
  ...require('./tiktok'),
  ...require('./trustpilot'),
  ...require('./truth-social'),
  ...require('./twitter'),
  ...require('./youtube'),
];
