// Generated by scripts/generate.py from spec/openapi.json. Do not edit by hand;
// change the spec or the generator and run `npm run generate`.
module.exports = [
  {
    "key": "linkedin_posts",
    "path": "/v1/linkedin/posts",
    "method": "GET",
    "platform": "LinkedIn",
    "noun": "Post",
    "kind": "list",
    "listKey": "posts",
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/linkedin-posts",
    "action": {
      "label": "Search LinkedIn Posts",
      "description": "Searches for LinkedIn posts by keyword. Returns post content, author information, engagement metrics (likes, comments, shares, reactions), and attached content entities (images, articles, videos, job listings). Includes a has_content_entities flag, true when the post has an attached image, article, video, or job. Results can be sorted by most recent or relevance, and limited to posts from the past 24 hours, week, or month. $0.006 per request after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "query",
        "label": "Search Query",
        "required": false,
        "type": "string",
        "helpText": "Search query (max 500 characters). Required unless at least one filter (e.g. author) is provided.",
        "placeholder": "artificial intelligence"
      },
      {
        "key": "page",
        "label": "Page Number",
        "required": false,
        "type": "integer",
        "default": "1",
        "helpText": "Page number, 1-25 (default: 1). 20 posts per page. LinkedIn's search pool is at most ~500 posts per query, so pages past the pool return an empty list. Values below 1 are treated as 1; a page above 25 returns 400 (1-25).",
        "placeholder": "1"
      },
      {
        "key": "sort_by",
        "label": "Sort By",
        "required": false,
        "type": "string",
        "default": "most_recent",
        "helpText": "Sort order for results",
        "choices": {
          "most_recent": "Most Recent",
          "relevance": "Relevance"
        },
        "placeholder": "most_recent"
      },
      {
        "key": "posted_ago",
        "label": "Posted Within",
        "required": false,
        "type": "string",
        "helpText": "Only return posts from this period: 24h (past day), 7d (past week), or 30d (past month). Works with both sort orders and every filter. Omit for all time. Any other value returns 400.",
        "choices": {
          "24h": "Last 24 hours",
          "7d": "Last 7 days",
          "30d": "Last 30 days"
        }
      },
      {
        "key": "author",
        "label": "Author",
        "required": false,
        "type": "string",
        "helpText": "Filter to posts authored by a specific person. Accepts a profile URL, public slug (e.g. williamhgates), or member URN, resolved automatically. Comma-separate for multiple (max 5 values)."
      },
      {
        "key": "mentions_member",
        "label": "Mentions Member",
        "required": false,
        "type": "string",
        "helpText": "Filter to posts that mention a specific person (profile URL, slug, or member URN). Comma-separate for multiple (max 5 values)."
      },
      {
        "key": "from_company",
        "label": "Posted by Company",
        "required": false,
        "type": "string",
        "helpText": "Filter to posts authored by a company page. Numeric LinkedIn company ID (from the Company Details endpoint). Comma-separate for multiple. Non-numeric values return 400."
      },
      {
        "key": "author_company",
        "label": "Author's Company",
        "required": false,
        "type": "string",
        "helpText": "Filter to posts written by people who work at a company. Numeric company ID, comma-separate for multiple. Non-numeric values return 400."
      },
      {
        "key": "mentions_company",
        "label": "Mentions Company",
        "required": false,
        "type": "string",
        "helpText": "Filter to posts that mention a company. Numeric company ID, comma-separate for multiple. Non-numeric values return 400."
      },
      {
        "key": "author_title",
        "label": "Author Job Title",
        "required": false,
        "type": "string",
        "helpText": "Filter by the author's job title as free text (e.g. CEO). Requires a query parameter."
      },
      {
        "key": "author_industry",
        "label": "Author Industry",
        "required": false,
        "type": "string",
        "helpText": "Filter by the author's industry. Numeric LinkedIn industry ID(s), comma-separated. Requires a query parameter. Non-numeric values return 400. Advanced."
      },
      {
        "key": "get_sentiment",
        "label": "Add Sentiment Analysis",
        "required": false,
        "type": "boolean",
        "helpText": "Set to true to add AI emotion analysis to each post. Adds a `sentiment` object containing `emotions` (joy, trust, fear, surprise, sadness, disgust, anger and anticipation, each scored 0-100), `dominant_emotion`, `emotional_intensity` (0-10), and `polarity` (positive, negative or neutral). Any post that cannot be scored returns `sentiment: null`."
      }
    ],
    "sample": {
      "count": 20,
      "page": 1,
      "posts": [
        {
          "article": null,
          "author": "Sina S. Amiri",
          "comments": 0,
          "date": "2026-04-04T21:13:18Z",
          "domain": "linkedin.com",
          "has_content_entities": false,
          "images": [],
          "job": null,
          "likes": 5,
          "reactions": {
            "interest": 1,
            "like": 4
          },
          "shares": 0,
          "snippet": "In many practices and DSOs, artificial intelligence isn’t fixing bad processes.\n\nIt’s scaling unnecessary complexity.\n\nAnd when complexity scales, inefficiencies don’t just persist.\n\nThey compound in…",
          "source": "LinkedIn",
          "title": "@Sina S. Amiri on LinkedIn",
          "url": "https://www.linkedin.com/posts/betterdentistry_dentistry-artificialintelligence-technology-activity-7446303912871071744-Z5Ju?utm_source=social_share_send&utm_medium=member_desktop_web&rcm=ACoAAGaiQmM…",
          "urn": "urn:li:activity:7446303912871071744",
          "video": null
        },
        {
          "article": null,
          "author": "Ponle Adeoye Esq.",
          "comments": 1,
          "date": "2026-04-04T21:12:53Z",
          "domain": "linkedin.com",
          "has_content_entities": false,
          "images": [],
          "job": null,
          "likes": 2,
          "reactions": {
            "like": 2
          },
          "shares": 0,
          "snippet": "AI is not replacing lawyers; it is empowering better lawyers.\n\nArtificial Intelligence (AI) is no longer a futuristic concept—it is already reshaping legal practice in profound ways. For lawyers, par…",
          "source": "LinkedIn",
          "title": "@Ponle Adeoye Esq. on LinkedIn",
          "url": "https://www.linkedin.com/posts/ponle-adeoye-esq-94072784_ai-is-not-replacing-lawyers-it-is-empowering-activity-7446303806222426112-nMY8?utm_source=social_share_send&utm_medium=member_desktop_web&rcm=…",
          "urn": "urn:li:activity:7446303806222426112",
          "video": null
        },
        {
          "article": null,
          "author": "Mohammad Gaber",
          "comments": 0,
          "date": "2026-04-04T21:12:51Z",
          "domain": "linkedin.com",
          "has_content_entities": true,
          "images": [
            "https://media.licdn.com/dms/image/v2/D4D22AQG-vPoIkN4-Wg/feedshare-shrink_800/B4DZ1aV1_1HIAc-/0/1775337169231?e=1776902400&v=beta&t=EN-mjzWKVPFAn5OjruKdJ60FUcVxdEY9WLqIwpstiI0"
          ],
          "job": null,
          "likes": 1,
          "reactions": {
            "like": 1
          },
          "shares": 0,
          "snippet": "Scientists discover that skin cells \"remember\" inflammation for life.\n\nHere’s why chronic conditions like psoriasis flare up in the same locations repeatedly.\n\nOur skin is more than just a protective…",
          "source": "LinkedIn",
          "title": "@Mohammad Gaber on LinkedIn",
          "url": "https://www.linkedin.com/posts/mohammad-gaber-90b2b8225_scientists-discover-that-skin-cells-remember-activity-7446303797724889089-e7q5?utm_source=social_share_send&utm_medium=member_desktop_web&rcm=A…",
          "urn": "urn:li:activity:7446303797724889089",
          "video": null
        }
      ]
    },
    "outputFields": [
      {
        "key": "count",
        "label": "Count",
        "type": "number"
      },
      {
        "key": "page",
        "label": "Page",
        "type": "number"
      },
      {
        "key": "posts[]article",
        "label": "Posts: Article"
      },
      {
        "key": "posts[]author",
        "label": "Posts: Author"
      },
      {
        "key": "posts[]comments",
        "label": "Posts: Comments",
        "type": "number"
      },
      {
        "key": "posts[]date",
        "label": "Posts: Date"
      },
      {
        "key": "posts[]domain",
        "label": "Posts: Domain"
      },
      {
        "key": "posts[]has_content_entities",
        "label": "Posts: Has Content Entities",
        "type": "boolean"
      },
      {
        "key": "posts[]images",
        "label": "Posts: Images",
        "list": true
      },
      {
        "key": "posts[]job",
        "label": "Posts: Job"
      },
      {
        "key": "posts[]likes",
        "label": "Posts: Likes",
        "type": "number"
      },
      {
        "key": "posts[]reactions__interest",
        "label": "Reactions Interest",
        "type": "number"
      },
      {
        "key": "posts[]reactions__like",
        "label": "Reactions Like",
        "type": "number"
      },
      {
        "key": "posts[]shares",
        "label": "Posts: Shares",
        "type": "number"
      },
      {
        "key": "posts[]snippet",
        "label": "Posts: Snippet"
      },
      {
        "key": "posts[]source",
        "label": "Posts: Source"
      },
      {
        "key": "posts[]title",
        "label": "Posts: Title"
      },
      {
        "key": "posts[]url",
        "label": "Posts: URL"
      },
      {
        "key": "posts[]urn",
        "label": "Posts: URN"
      },
      {
        "key": "posts[]video",
        "label": "Posts: Video"
      }
    ],
    "trigger": {
      "label": "New LinkedIn Post Matching Search",
      "description": "Triggers when a new LinkedIn post matches your search or filters. Each check runs Search LinkedIn Posts ($0.006 per request after the free tier (50 requests/month)).",
      "inputFields": [
        {
          "key": "query",
          "label": "Search Query",
          "required": false,
          "type": "string",
          "helpText": "Search query (max 500 characters). Required unless at least one filter (e.g. author) is provided.",
          "placeholder": "artificial intelligence"
        },
        {
          "key": "page",
          "label": "Page Number",
          "required": false,
          "type": "integer",
          "default": "1",
          "helpText": "Page number, 1-25 (default: 1). 20 posts per page. LinkedIn's search pool is at most ~500 posts per query, so pages past the pool return an empty list. Values below 1 are treated as 1; a page above 25 returns 400 (1-25).",
          "placeholder": "1"
        },
        {
          "key": "sort_by",
          "label": "Sort By",
          "required": false,
          "type": "string",
          "default": "most_recent",
          "helpText": "Sort order for results",
          "choices": {
            "most_recent": "Most Recent",
            "relevance": "Relevance"
          },
          "placeholder": "most_recent"
        },
        {
          "key": "posted_ago",
          "label": "Posted Within",
          "required": false,
          "type": "string",
          "helpText": "Only return posts from this period: 24h (past day), 7d (past week), or 30d (past month). Works with both sort orders and every filter. Omit for all time. Any other value returns 400.",
          "choices": {
            "24h": "Last 24 hours",
            "7d": "Last 7 days",
            "30d": "Last 30 days"
          }
        },
        {
          "key": "author",
          "label": "Author",
          "required": false,
          "type": "string",
          "helpText": "Filter to posts authored by a specific person. Accepts a profile URL, public slug (e.g. williamhgates), or member URN, resolved automatically. Comma-separate for multiple (max 5 values)."
        },
        {
          "key": "mentions_member",
          "label": "Mentions Member",
          "required": false,
          "type": "string",
          "helpText": "Filter to posts that mention a specific person (profile URL, slug, or member URN). Comma-separate for multiple (max 5 values)."
        },
        {
          "key": "from_company",
          "label": "Posted by Company",
          "required": false,
          "type": "string",
          "helpText": "Filter to posts authored by a company page. Numeric LinkedIn company ID (from the Company Details endpoint). Comma-separate for multiple. Non-numeric values return 400."
        },
        {
          "key": "author_company",
          "label": "Author's Company",
          "required": false,
          "type": "string",
          "helpText": "Filter to posts written by people who work at a company. Numeric company ID, comma-separate for multiple. Non-numeric values return 400."
        },
        {
          "key": "mentions_company",
          "label": "Mentions Company",
          "required": false,
          "type": "string",
          "helpText": "Filter to posts that mention a company. Numeric company ID, comma-separate for multiple. Non-numeric values return 400."
        },
        {
          "key": "author_title",
          "label": "Author Job Title",
          "required": false,
          "type": "string",
          "helpText": "Filter by the author's job title as free text (e.g. CEO). Requires a query parameter."
        },
        {
          "key": "author_industry",
          "label": "Author Industry",
          "required": false,
          "type": "string",
          "helpText": "Filter by the author's industry. Numeric LinkedIn industry ID(s), comma-separated. Requires a query parameter. Non-numeric values return 400. Advanced."
        },
        {
          "key": "get_sentiment",
          "label": "Add Sentiment Analysis",
          "required": false,
          "type": "boolean",
          "helpText": "Set to true to add AI emotion analysis to each post. Adds a `sentiment` object containing `emotions` (joy, trust, fear, surprise, sadness, disgust, anger and anticipation, each scored 0-100), `dominant_emotion`, `emotional_intensity` (0-10), and `polarity` (positive, negative or neutral). Any post that cannot be scored returns `sentiment: null`."
        }
      ],
      "sample": {
        "id": "urn:li:activity:7446303912871071744",
        "article": null,
        "author": "Sina S. Amiri",
        "comments": 0,
        "date": "2026-04-04T21:13:18Z",
        "domain": "linkedin.com",
        "has_content_entities": false,
        "images": [],
        "job": null,
        "likes": 5,
        "reactions": {
          "interest": 1,
          "like": 4
        },
        "shares": 0,
        "snippet": "In many practices and DSOs, artificial intelligence isn’t fixing bad processes.\n\nIt’s scaling unnecessary complexity.\n\nAnd when complexity scales, inefficiencies don’t just persist.\n\nThey compound in…",
        "source": "LinkedIn",
        "title": "@Sina S. Amiri on LinkedIn",
        "url": "https://www.linkedin.com/posts/betterdentistry_dentistry-artificialintelligence-technology-activity-7446303912871071744-Z5Ju?utm_source=social_share_send&utm_medium=member_desktop_web&rcm=ACoAAGaiQmM…",
        "urn": "urn:li:activity:7446303912871071744",
        "video": null
      },
      "outputFields": [
        {
          "key": "id",
          "label": "ID",
          "primary": true
        },
        {
          "key": "article",
          "label": "Article"
        },
        {
          "key": "author",
          "label": "Author"
        },
        {
          "key": "comments",
          "label": "Comments",
          "type": "number"
        },
        {
          "key": "date",
          "label": "Date"
        },
        {
          "key": "domain",
          "label": "Domain"
        },
        {
          "key": "has_content_entities",
          "label": "Has Content Entities",
          "type": "boolean"
        },
        {
          "key": "images",
          "label": "Images",
          "list": true
        },
        {
          "key": "job",
          "label": "Job"
        },
        {
          "key": "likes",
          "label": "Likes",
          "type": "number"
        },
        {
          "key": "reactions__interest",
          "label": "Reactions Interest",
          "type": "number"
        },
        {
          "key": "reactions__like",
          "label": "Reactions Like",
          "type": "number"
        },
        {
          "key": "shares",
          "label": "Shares",
          "type": "number"
        },
        {
          "key": "snippet",
          "label": "Snippet"
        },
        {
          "key": "source",
          "label": "Source"
        },
        {
          "key": "title",
          "label": "Title"
        },
        {
          "key": "url",
          "label": "URL"
        },
        {
          "key": "urn",
          "label": "URN"
        },
        {
          "key": "video",
          "label": "Video"
        }
      ]
    }
  },
  {
    "key": "linkedin_person",
    "path": "/v1/linkedin/person",
    "method": "GET",
    "platform": "LinkedIn",
    "noun": "Person",
    "kind": "detail",
    "listKey": null,
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/linkedin-person",
    "action": {
      "label": "Find LinkedIn Person",
      "description": "Gets a LinkedIn person's profile: name, headline, about, location, follower and connection counts, open-to-work status, and the experience, education, skills, certifications, languages, honors, publications, volunteering, and projects sections. Pass a profile URL, public slug, or member URN. $0.006 per request after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "url",
        "label": "URL",
        "required": true,
        "type": "string",
        "helpText": "LinkedIn profile URL, public slug, or member URN (e.g., `https://www.linkedin.com/in/reidhoffman,` reidhoffman, or ACoAAAAABL0B3SGhqeNX998wiOuk_8hYA6ojLwg). Max 500 characters.",
        "placeholder": "reidhoffman"
      }
    ],
    "sample": {
      "about": "My current priority is investing in and building with AI to benefit humanity.  Recently, I've co-founded Inflection.AI and ManasAI.co.  \n\nI am active in all facets of the consumer internet and softwa…",
      "certifications": [],
      "connections": 4324,
      "country_code": "US",
      "cover_image": "https://media.licdn.com/dms/image/v2/D4D16AQFCaHSy0bruvQ/profile-displaybackgroundimage-shrink_350_1400/B4DZ_Y6OsjI4AU-/0/1786050571454?e=1792627200&v=beta&t=KglRjOlwadeoq69TAPinbFgZm8qkRhqd60iNkhVWu…",
      "domain": "linkedin.com",
      "education": [
        {
          "degree": "Honorary Doctorate",
          "description": "",
          "end_date": {
            "month": 5,
            "year": 2024
          },
          "field_of_study": "Human Sciences",
          "school": "Università degli Studi di Perugia",
          "school_id": "2052604",
          "school_logo": "https://media.licdn.com/dms/image/v2/C4D0BAQGkG0u34ews4A/company-logo_400_400/company-logo_400_400/0/1630557917735/universit_degli_studi_di_perugia_logo?e=1792627200&v=beta&t=U_XzDzhtGBfFViGKVKb_Iwl9…",
          "school_url": "https://www.linkedin.com/school/universit-degli-studi-di-perugia/",
          "start_date": {
            "month": 5,
            "year": 2024
          }
        },
        {
          "degree": "Honorary Doctor",
          "description": "The University of Oulu is an international science university which creates new knowledge, well-being and innovations for the future through research and education. The University of Oulu, founded in…",
          "end_date": {
            "month": null,
            "year": 2020
          },
          "field_of_study": "Faculty of Information Technology and Electrical Engineering",
          "school": "University of Oulu",
          "school_id": "166661",
          "school_logo": "https://media.licdn.com/dms/image/v2/D4E0BAQHu0BWtQX586A/company-logo_400_400/company-logo_400_400/0/1691396242467/university_of_oulu_logo?e=1792627200&v=beta&t=1BVcxNj7J8DYSmbqyPYTR9UiNlZSt1nKIiXp0F…",
          "school_url": "https://www.linkedin.com/school/university-of-oulu/",
          "start_date": {
            "month": null,
            "year": 2020
          }
        }
      ],
      "experience": [
        {
          "company": "Manas AI",
          "company_id": "106067845",
          "company_logo": "https://media.licdn.com/dms/image/v2/D4D0BAQHehetLvQnNEg/company-logo_400_400/B4DZl29VWTIYAc-/0/1758637414313?e=1792627200&v=beta&t=FX55UgNxW5eKxSqFq8rtXk5mqFQAerLXnyRjSrsCx-w",
          "company_url": "https://www.linkedin.com/company/manas-ai",
          "description": "Manas AI leverages proprietary AI, generative computational chemistry, and best in class biology to cut the timeline and costs of traditional therapeutic discovery and transform the treatment of canc…",
          "employment_type": "",
          "end_date": null,
          "is_current": true,
          "location": "",
          "start_date": {
            "month": 1,
            "year": 2025
          },
          "title": "Co-Founder, Executive Board Chair"
        },
        {
          "company": "Inflection AI",
          "company_id": "79994924",
          "company_logo": "https://media.licdn.com/dms/image/v2/D560BAQHiRCagrbmSxw/company-logo_100_100/B56Z.VJKP2IoAI-/0/1784913634701/inflectionai_logo?e=1792627200&v=beta&t=nQ9rkKugHYFfrtfcb5I99iMRMaSV9T0KiJUh_y_PdpQ",
          "company_url": "https://www.linkedin.com/company/inflectionai",
          "description": "Inflection AI is a public benefit corporation leveraging our world-class large language model to build the first AI platform focused on the needs of the enterprise. \n\nI helped start Inflection AI to …",
          "employment_type": "",
          "end_date": null,
          "is_current": true,
          "location": "Palo Alto, California, United States",
          "start_date": {
            "month": 3,
            "year": 2022
          },
          "title": "Co-Founder, Board Member"
        }
      ],
      "first_name": "Reid",
      "followers": 2795262,
      "full_name": "Reid Hoffman",
      "headline": "Co-Founder, LinkedIn, Manas AI & Inflection AI. Founding Team, PayPal.  Author of Superagency.  Podcaster of Possible and Masters of Scale.",
      "honors": [
        {
          "description": "Sigillum Magnum is a silver-bronze medal realized in 1888. The medal is composed by some single medals of the Corporations which were forming the Bolognese Study.  The University of Bologna is the ol…",
          "issued_date": {
            "month": 9,
            "year": 2023
          },
          "issuer": "University of Bologna",
          "title": "Sigillum Magnum"
        },
        {
          "description": "Founded during the American Revolution by John Adams, James Bowdoin, John Hancock, and other prominent contributors to the establishment of the new nation, the Academy has a rich intellectual history…",
          "issued_date": {
            "month": 4,
            "year": 2018
          },
          "issuer": "Academy of Arts and Sciences",
          "title": "Member, Academy of Arts and Sciences"
        }
      ],
      "is_creator": true,
      "is_premium": true,
      "languages": [],
      "last_name": "Hoffman",
      "location": "United States",
      "open_to_work": false,
      "profile_picture": "https://media.licdn.com/dms/image/v2/D5603AQHW7wKzPb3DAg/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1718216236351?e=1792627200&v=beta&t=g-s9yFn1DsgD2SnGaU3wjqKWaOsQhMbn…",
      "projects": [],
      "public_identifier": "reidhoffman",
      "publications": [
        {
          "published_date": {
            "month": 1,
            "year": 2025
          },
          "publisher": "Authors Equity",
          "title": "Superagency",
          "url": "https://www.superagency.ai/"
        },
        {
          "published_date": {
            "month": 3,
            "year": 2023
          },
          "publisher": "Amazon",
          "title": "Impromptu",
          "url": "https://www.amazon.com/Impromptu-Amplifying-Our-Humanity-Through/dp/B0BYLBPW8B/"
        }
      ],
      "skills": [
        {
          "endorsements": 2,
          "name": "CEOs"
        },
        {
          "endorsements": 2,
          "name": "Founding"
        }
      ],
      "source": "LinkedIn",
      "url": "https://www.linkedin.com/in/reidhoffman",
      "urn": "ACoAAAAABL0B3SGhqeNX998wiOuk_8hYA6ojLwg",
      "volunteering": [
        {
          "end_date": null,
          "organization": "Opportunity@Work",
          "role": "Chair, Board of Directors",
          "start_date": {
            "month": 6,
            "year": 2016
          }
        },
        {
          "end_date": null,
          "organization": "Arc Institute",
          "role": "Board Member",
          "start_date": {
            "month": 12,
            "year": 2021
          }
        }
      ]
    },
    "outputFields": [
      {
        "key": "about",
        "label": "About"
      },
      {
        "key": "certifications",
        "label": "Certifications",
        "list": true
      },
      {
        "key": "connections",
        "label": "Connections",
        "type": "number"
      },
      {
        "key": "country_code",
        "label": "Country Code"
      },
      {
        "key": "cover_image",
        "label": "Cover Image"
      },
      {
        "key": "domain",
        "label": "Domain"
      },
      {
        "key": "education[]degree",
        "label": "Education: Degree"
      },
      {
        "key": "education[]description",
        "label": "Education: Description"
      },
      {
        "key": "education[]end_date__month",
        "label": "End Date Month",
        "type": "number"
      },
      {
        "key": "education[]end_date__year",
        "label": "End Date Year",
        "type": "number"
      },
      {
        "key": "education[]field_of_study",
        "label": "Education: Field Of Study"
      },
      {
        "key": "education[]school",
        "label": "Education: School"
      },
      {
        "key": "education[]school_id",
        "label": "Education: School ID"
      },
      {
        "key": "education[]school_logo",
        "label": "Education: School Logo"
      },
      {
        "key": "education[]school_url",
        "label": "Education: School URL"
      },
      {
        "key": "education[]start_date__month",
        "label": "Start Date Month",
        "type": "number"
      },
      {
        "key": "education[]start_date__year",
        "label": "Start Date Year",
        "type": "number"
      },
      {
        "key": "experience[]company",
        "label": "Experience: Company"
      },
      {
        "key": "experience[]company_id",
        "label": "Experience: Company ID"
      },
      {
        "key": "experience[]company_logo",
        "label": "Experience: Company Logo"
      },
      {
        "key": "experience[]company_url",
        "label": "Experience: Company URL"
      },
      {
        "key": "experience[]description",
        "label": "Experience: Description"
      },
      {
        "key": "experience[]employment_type",
        "label": "Experience: Employment Type"
      },
      {
        "key": "experience[]end_date",
        "label": "Experience: End Date"
      },
      {
        "key": "experience[]is_current",
        "label": "Experience: Is Current",
        "type": "boolean"
      },
      {
        "key": "experience[]location",
        "label": "Experience: Location"
      },
      {
        "key": "experience[]start_date__month",
        "label": "Start Date Month",
        "type": "number"
      },
      {
        "key": "experience[]start_date__year",
        "label": "Start Date Year",
        "type": "number"
      },
      {
        "key": "experience[]title",
        "label": "Experience: Title"
      },
      {
        "key": "first_name",
        "label": "First Name"
      },
      {
        "key": "followers",
        "label": "Followers",
        "type": "number"
      },
      {
        "key": "full_name",
        "label": "Full Name"
      },
      {
        "key": "headline",
        "label": "Headline"
      },
      {
        "key": "honors[]description",
        "label": "Honors: Description"
      },
      {
        "key": "honors[]issued_date__month",
        "label": "Issued Date Month",
        "type": "number"
      },
      {
        "key": "honors[]issued_date__year",
        "label": "Issued Date Year",
        "type": "number"
      },
      {
        "key": "honors[]issuer",
        "label": "Honors: Issuer"
      },
      {
        "key": "honors[]title",
        "label": "Honors: Title"
      },
      {
        "key": "is_creator",
        "label": "Is Creator",
        "type": "boolean"
      },
      {
        "key": "is_premium",
        "label": "Is Premium",
        "type": "boolean"
      },
      {
        "key": "languages",
        "label": "Languages",
        "list": true
      },
      {
        "key": "last_name",
        "label": "Last Name"
      },
      {
        "key": "location",
        "label": "Location"
      },
      {
        "key": "open_to_work",
        "label": "Open To Work",
        "type": "boolean"
      },
      {
        "key": "profile_picture",
        "label": "Profile Picture"
      },
      {
        "key": "projects",
        "label": "Projects",
        "list": true
      },
      {
        "key": "public_identifier",
        "label": "Public Identifier"
      },
      {
        "key": "publications[]published_date__month",
        "label": "Published Date Month",
        "type": "number"
      },
      {
        "key": "publications[]published_date__year",
        "label": "Published Date Year",
        "type": "number"
      },
      {
        "key": "publications[]publisher",
        "label": "Publications: Publisher"
      },
      {
        "key": "publications[]title",
        "label": "Publications: Title"
      },
      {
        "key": "publications[]url",
        "label": "Publications: URL"
      },
      {
        "key": "skills[]endorsements",
        "label": "Skills: Endorsements",
        "type": "number"
      },
      {
        "key": "skills[]name",
        "label": "Skills: Name"
      },
      {
        "key": "source",
        "label": "Source"
      },
      {
        "key": "url",
        "label": "URL"
      },
      {
        "key": "urn",
        "label": "URN"
      },
      {
        "key": "volunteering[]end_date",
        "label": "Volunteering: End Date"
      },
      {
        "key": "volunteering[]organization",
        "label": "Volunteering: Organization"
      },
      {
        "key": "volunteering[]role",
        "label": "Volunteering: Role"
      },
      {
        "key": "volunteering[]start_date__month",
        "label": "Start Date Month",
        "type": "number"
      },
      {
        "key": "volunteering[]start_date__year",
        "label": "Start Date Year",
        "type": "number"
      }
    ],
    "trigger": null
  },
  {
    "key": "linkedin_person_posts",
    "path": "/v1/linkedin/person/posts",
    "method": "GET",
    "platform": "LinkedIn",
    "noun": "Post",
    "kind": "list",
    "listKey": "posts",
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/linkedin-person-posts",
    "action": {
      "label": "Get LinkedIn Person Posts",
      "description": "Gets the recent posts authored by a LinkedIn person by profile URL or public slug. Returns post content, engagement metrics (likes, comments, shares, reaction breakdowns), author info, images, videos, and articles. $0.006 per request after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "url",
        "label": "URL",
        "required": true,
        "type": "string",
        "helpText": "LinkedIn profile URL or public slug, e.g. `https://www.linkedin.com/in/williamhgates` or williamhgates (max 500 characters)",
        "placeholder": "williamhgates"
      },
      {
        "key": "page",
        "label": "Page Number",
        "required": false,
        "type": "integer",
        "default": "1",
        "helpText": "Page number, 1-30 (default: 1). 20 posts per page, so up to about 600 of the person's most recent posts. Values below 1 are treated as 1; a page above 30 returns 400 (1-30).",
        "placeholder": "1"
      },
      {
        "key": "get_sentiment",
        "label": "Add Sentiment Analysis",
        "required": false,
        "type": "boolean",
        "helpText": "Set to true to add AI emotion analysis to each post. Adds a `sentiment` object containing `emotions` (joy, trust, fear, surprise, sadness, disgust, anger and anticipation, each scored 0-100), `dominant_emotion`, `emotional_intensity` (0-10), and `polarity` (positive, negative or neutral). Any post that cannot be scored returns `sentiment: null`."
      }
    ],
    "sample": {
      "count": 20,
      "page": 1,
      "posts": [
        {
          "article": null,
          "author": "Bill Gates",
          "author_description": "Chair, Gates Foundation and Founder, Breakthrough Energy",
          "author_image": "https://media.licdn.com/dms/image/...",
          "author_url": "https://www.linkedin.com/in/williamhgates",
          "comments": 368,
          "date": "2026-06-21T18:36:16Z",
          "domain": "linkedin.com",
          "images": [],
          "is_repost": false,
          "likes": 3706,
          "reactions": {
            "appreciation": 145,
            "empathy": 168,
            "like": 3290
          },
          "shares": 28,
          "source": "LinkedIn",
          "text": "I got involved in global health back in 1997...",
          "url": "https://www.linkedin.com/posts/williamhgates_activity-7474530647273934848-VLxg",
          "urn": "urn:li:activity:7474530647273934848",
          "video": {
            "duration": 83600,
            "thumbnail": "https://media.licdn.com/dms/image/..."
          }
        }
      ]
    },
    "outputFields": [
      {
        "key": "count",
        "label": "Count",
        "type": "number"
      },
      {
        "key": "page",
        "label": "Page",
        "type": "number"
      },
      {
        "key": "posts[]article",
        "label": "Posts: Article"
      },
      {
        "key": "posts[]author",
        "label": "Posts: Author"
      },
      {
        "key": "posts[]author_description",
        "label": "Posts: Author Description"
      },
      {
        "key": "posts[]author_image",
        "label": "Posts: Author Image"
      },
      {
        "key": "posts[]author_url",
        "label": "Posts: Author URL"
      },
      {
        "key": "posts[]comments",
        "label": "Posts: Comments",
        "type": "number"
      },
      {
        "key": "posts[]date",
        "label": "Posts: Date"
      },
      {
        "key": "posts[]domain",
        "label": "Posts: Domain"
      },
      {
        "key": "posts[]images",
        "label": "Posts: Images",
        "list": true
      },
      {
        "key": "posts[]is_repost",
        "label": "Posts: Is Repost",
        "type": "boolean"
      },
      {
        "key": "posts[]likes",
        "label": "Posts: Likes",
        "type": "number"
      },
      {
        "key": "posts[]reactions__appreciation",
        "label": "Reactions Appreciation",
        "type": "number"
      },
      {
        "key": "posts[]reactions__empathy",
        "label": "Reactions Empathy",
        "type": "number"
      },
      {
        "key": "posts[]reactions__like",
        "label": "Reactions Like",
        "type": "number"
      },
      {
        "key": "posts[]shares",
        "label": "Posts: Shares",
        "type": "number"
      },
      {
        "key": "posts[]source",
        "label": "Posts: Source"
      },
      {
        "key": "posts[]text",
        "label": "Posts: Text"
      },
      {
        "key": "posts[]url",
        "label": "Posts: URL"
      },
      {
        "key": "posts[]urn",
        "label": "Posts: URN"
      },
      {
        "key": "posts[]video__duration",
        "label": "Video Duration",
        "type": "number"
      },
      {
        "key": "posts[]video__thumbnail",
        "label": "Video Thumbnail"
      }
    ],
    "trigger": {
      "label": "New LinkedIn Post by Person",
      "description": "Triggers when a LinkedIn member publishes a new post. Each check runs Get LinkedIn Person Posts ($0.006 per request after the free tier (50 requests/month)).",
      "inputFields": [
        {
          "key": "url",
          "label": "URL",
          "required": true,
          "type": "string",
          "helpText": "LinkedIn profile URL or public slug, e.g. `https://www.linkedin.com/in/williamhgates` or williamhgates (max 500 characters)",
          "placeholder": "williamhgates"
        },
        {
          "key": "page",
          "label": "Page Number",
          "required": false,
          "type": "integer",
          "default": "1",
          "helpText": "Page number, 1-30 (default: 1). 20 posts per page, so up to about 600 of the person's most recent posts. Values below 1 are treated as 1; a page above 30 returns 400 (1-30).",
          "placeholder": "1"
        },
        {
          "key": "get_sentiment",
          "label": "Add Sentiment Analysis",
          "required": false,
          "type": "boolean",
          "helpText": "Set to true to add AI emotion analysis to each post. Adds a `sentiment` object containing `emotions` (joy, trust, fear, surprise, sadness, disgust, anger and anticipation, each scored 0-100), `dominant_emotion`, `emotional_intensity` (0-10), and `polarity` (positive, negative or neutral). Any post that cannot be scored returns `sentiment: null`."
        }
      ],
      "sample": {
        "id": "urn:li:activity:7474530647273934848",
        "article": null,
        "author": "Bill Gates",
        "author_description": "Chair, Gates Foundation and Founder, Breakthrough Energy",
        "author_image": "https://media.licdn.com/dms/image/...",
        "author_url": "https://www.linkedin.com/in/williamhgates",
        "comments": 368,
        "date": "2026-06-21T18:36:16Z",
        "domain": "linkedin.com",
        "images": [],
        "is_repost": false,
        "likes": 3706,
        "reactions": {
          "appreciation": 145,
          "empathy": 168,
          "like": 3290
        },
        "shares": 28,
        "source": "LinkedIn",
        "text": "I got involved in global health back in 1997...",
        "url": "https://www.linkedin.com/posts/williamhgates_activity-7474530647273934848-VLxg",
        "urn": "urn:li:activity:7474530647273934848",
        "video": {
          "duration": 83600,
          "thumbnail": "https://media.licdn.com/dms/image/..."
        }
      },
      "outputFields": [
        {
          "key": "id",
          "label": "ID",
          "primary": true
        },
        {
          "key": "article",
          "label": "Article"
        },
        {
          "key": "author",
          "label": "Author"
        },
        {
          "key": "author_description",
          "label": "Author Description"
        },
        {
          "key": "author_image",
          "label": "Author Image"
        },
        {
          "key": "author_url",
          "label": "Author URL"
        },
        {
          "key": "comments",
          "label": "Comments",
          "type": "number"
        },
        {
          "key": "date",
          "label": "Date"
        },
        {
          "key": "domain",
          "label": "Domain"
        },
        {
          "key": "images",
          "label": "Images",
          "list": true
        },
        {
          "key": "is_repost",
          "label": "Is Repost",
          "type": "boolean"
        },
        {
          "key": "likes",
          "label": "Likes",
          "type": "number"
        },
        {
          "key": "reactions__appreciation",
          "label": "Reactions Appreciation",
          "type": "number"
        },
        {
          "key": "reactions__empathy",
          "label": "Reactions Empathy",
          "type": "number"
        },
        {
          "key": "reactions__like",
          "label": "Reactions Like",
          "type": "number"
        },
        {
          "key": "shares",
          "label": "Shares",
          "type": "number"
        },
        {
          "key": "source",
          "label": "Source"
        },
        {
          "key": "text",
          "label": "Text"
        },
        {
          "key": "url",
          "label": "URL"
        },
        {
          "key": "urn",
          "label": "URN"
        },
        {
          "key": "video__duration",
          "label": "Video Duration",
          "type": "number"
        },
        {
          "key": "video__thumbnail",
          "label": "Video Thumbnail"
        }
      ]
    }
  },
  {
    "key": "linkedin_post",
    "path": "/v1/linkedin/post",
    "method": "GET",
    "platform": "LinkedIn",
    "noun": "Post",
    "kind": "detail",
    "listKey": null,
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/linkedin-post",
    "action": {
      "label": "Find LinkedIn Post",
      "description": "Gets detailed information about a specific LinkedIn post including full content, likes, comments, shares, reactions, embedded links, images, and author details. Pass the full post URL. $0.002 per request after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "url",
        "label": "URL",
        "required": true,
        "type": "string",
        "helpText": "Full URL of the LinkedIn post (max 500 characters)",
        "placeholder": "https://www.linkedin.com/feed/update/urn:li:activity:7219434359085252608"
      },
      {
        "key": "get_sentiment",
        "label": "Add Sentiment Analysis",
        "required": false,
        "type": "boolean",
        "helpText": "Set to true to add AI emotion analysis to the post. Adds a `sentiment` object containing `emotions` (joy, trust, fear, surprise, sadness, disgust, anger and anticipation, each scored 0-100), `dominant_emotion`, `emotional_intensity` (0-10), and `polarity` (positive, negative or neutral). If the post cannot be scored, `sentiment` is null."
      }
    ],
    "sample": {
      "author": "Sina S. Amiri",
      "author_description": "Advises Dental Practice Owners, DSOs, Dentistry Groups, Multi-Site Operators & Private Equity Firms • Artificial Intelligence Technology, Machine Learning & Healthcare Revenue Cycle Management Softwa…",
      "author_image": "https://media.licdn.com/dms/image/v2/D4E03AQFLMg72ZWQUlA/profile-displayphoto-scale_400_400/B4EZnwS7v5JAAg-/0/1760673120153?e=1776902400&v=beta&t=f3yYR9IcpdRvn4b53a3mfZAb3fWkYANp5GMI-ZHL-Y4",
      "author_url": "https://www.linkedin.com/in/betterdentistry?miniProfileUrn=urn%3Ali%3Afsd_profile%3AACoAAAC_snQBekHviVMycAzT65btL8X0iojQ3iw",
      "comments": 0,
      "date": "2026-04-04T21:13:18Z",
      "domain": "linkedin.com",
      "images": [],
      "is_repost": false,
      "likes": 5,
      "links": [],
      "reactions": {
        "interest": 1,
        "like": 4
      },
      "shares": 0,
      "source": "LinkedIn",
      "text": "In many practices and DSOs, artificial intelligence isn’t fixing bad processes.\n\nIt’s scaling unnecessary complexity.\n\nAnd when complexity scales, inefficiencies don’t just persist.\n\nThey compound in…",
      "url": "https://www.linkedin.com/feed/update/urn:li:activity:7446303912871071744",
      "urn": "urn:li:activity:7446303912871071744"
    },
    "outputFields": [
      {
        "key": "author",
        "label": "Author"
      },
      {
        "key": "author_description",
        "label": "Author Description"
      },
      {
        "key": "author_image",
        "label": "Author Image"
      },
      {
        "key": "author_url",
        "label": "Author URL"
      },
      {
        "key": "comments",
        "label": "Comments",
        "type": "number"
      },
      {
        "key": "date",
        "label": "Date"
      },
      {
        "key": "domain",
        "label": "Domain"
      },
      {
        "key": "images",
        "label": "Images",
        "list": true
      },
      {
        "key": "is_repost",
        "label": "Is Repost",
        "type": "boolean"
      },
      {
        "key": "likes",
        "label": "Likes",
        "type": "number"
      },
      {
        "key": "links",
        "label": "Links",
        "list": true
      },
      {
        "key": "reactions__interest",
        "label": "Reactions Interest",
        "type": "number"
      },
      {
        "key": "reactions__like",
        "label": "Reactions Like",
        "type": "number"
      },
      {
        "key": "shares",
        "label": "Shares",
        "type": "number"
      },
      {
        "key": "source",
        "label": "Source"
      },
      {
        "key": "text",
        "label": "Text"
      },
      {
        "key": "url",
        "label": "URL"
      },
      {
        "key": "urn",
        "label": "URN"
      }
    ],
    "trigger": null
  },
  {
    "key": "linkedin_companies",
    "path": "/v1/linkedin/companies",
    "method": "GET",
    "platform": "LinkedIn",
    "noun": "Company",
    "kind": "list",
    "listKey": "companies",
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/linkedin-companies",
    "action": {
      "label": "Search LinkedIn Companies",
      "description": "Searches for LinkedIn company pages by keyword. Returns company name, company ID, description, a subtitle (industry and location), follower count, logo, and page URL. Returns 10 results per page. $0.006 per request after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "query",
        "label": "Search Query",
        "required": true,
        "type": "string",
        "helpText": "Search query (max 500 characters)",
        "placeholder": "AI"
      },
      {
        "key": "page",
        "label": "Page Number",
        "required": false,
        "type": "integer",
        "default": "1",
        "helpText": "Page number for pagination (1-100). Each page returns 10 results. Values below 1 are treated as 1; a page above 100 returns 400 (1-100).",
        "placeholder": "1"
      }
    ],
    "sample": {
      "companies": [
        {
          "company_id": "24468",
          "description": "Your Go-To Hub for Everything Artificial Intelligence",
          "followers": "31K followers",
          "logo": "https://media.licdn.com/dms/image/v2/D4E0BAQGMoDjcPW6-Aw/company-logo_100_100/company-logo_100_100/0/1735190390219/venture_capitalists_logo?e=1776902400&v=beta&t=0C6Sij9VgF_2ucCgAG-mTrEssocLHNFEX74qz…",
          "name": "Artificial Intelligence",
          "subtitle": "Technology, Information and Internet • New York",
          "url": "https://www.linkedin.com/company/artificial-intelligence-facts/"
        },
        {
          "company_id": "13605190",
          "description": "Artificial Intelligence",
          "followers": "26K followers",
          "logo": "https://media.licdn.com/dms/image/v2/D560BAQHjrBrP2pygQA/company-logo_100_100/company-logo_100_100/0/1719948400529?e=1776902400&v=beta&t=eCqN7RR-IaAlwKEHBucdKh18czKQsNAXE06v5dFk3y0",
          "name": "Artificial Intelligence",
          "subtitle": "IT Services and IT Consulting • Colorado Springs, Colorado",
          "url": "https://www.linkedin.com/company/self-employed-ai/"
        },
        {
          "company_id": "107211336",
          "description": "Welcome to my AI page, where I share insights and resources related to the dynamic and rapidly evolving world of artificial intelligence. With a background in data analytics and a deep interest in le…",
          "followers": "14K followers",
          "logo": "https://media.licdn.com/dms/image/v2/D4D0BAQHYaB6zBIjiEQ/company-logo_100_100/B4DZaPkB6zGwAU-/0/1746165311082/ai_gen_ai_logo?e=1776902400&v=beta&t=aZeiHNt-0twXJWxkJMnA8IXBxXw4T6SlJBUzAfDxBlU",
          "name": "Artificial Intelligence",
          "subtitle": "Technology, Information and Internet • Sunnyvale, California",
          "url": "https://www.linkedin.com/company/ai-gen-ai/"
        }
      ],
      "count": 10,
      "page": 1
    },
    "outputFields": [
      {
        "key": "companies[]company_id",
        "label": "Companies: Company ID"
      },
      {
        "key": "companies[]description",
        "label": "Companies: Description"
      },
      {
        "key": "companies[]followers",
        "label": "Companies: Followers"
      },
      {
        "key": "companies[]logo",
        "label": "Companies: Logo"
      },
      {
        "key": "companies[]name",
        "label": "Companies: Name"
      },
      {
        "key": "companies[]subtitle",
        "label": "Companies: Subtitle"
      },
      {
        "key": "companies[]url",
        "label": "Companies: URL"
      },
      {
        "key": "count",
        "label": "Count",
        "type": "number"
      },
      {
        "key": "page",
        "label": "Page",
        "type": "number"
      }
    ],
    "trigger": {
      "label": "New LinkedIn Company Matching Search",
      "description": "Triggers when a new LinkedIn company matches your search. Each check runs Search LinkedIn Companies ($0.006 per request after the free tier (50 requests/month)).",
      "inputFields": [
        {
          "key": "query",
          "label": "Search Query",
          "required": true,
          "type": "string",
          "helpText": "Search query (max 500 characters)",
          "placeholder": "AI"
        },
        {
          "key": "page",
          "label": "Page Number",
          "required": false,
          "type": "integer",
          "default": "1",
          "helpText": "Page number for pagination (1-100). Each page returns 10 results. Values below 1 are treated as 1; a page above 100 returns 400 (1-100).",
          "placeholder": "1"
        }
      ],
      "sample": {
        "id": "24468",
        "company_id": "24468",
        "description": "Your Go-To Hub for Everything Artificial Intelligence",
        "followers": "31K followers",
        "logo": "https://media.licdn.com/dms/image/v2/D4E0BAQGMoDjcPW6-Aw/company-logo_100_100/company-logo_100_100/0/1735190390219/venture_capitalists_logo?e=1776902400&v=beta&t=0C6Sij9VgF_2ucCgAG-mTrEssocLHNFEX74qz…",
        "name": "Artificial Intelligence",
        "subtitle": "Technology, Information and Internet • New York",
        "url": "https://www.linkedin.com/company/artificial-intelligence-facts/"
      },
      "outputFields": [
        {
          "key": "id",
          "label": "ID",
          "primary": true
        },
        {
          "key": "company_id",
          "label": "Company ID"
        },
        {
          "key": "description",
          "label": "Description"
        },
        {
          "key": "followers",
          "label": "Followers"
        },
        {
          "key": "logo",
          "label": "Logo"
        },
        {
          "key": "name",
          "label": "Name"
        },
        {
          "key": "subtitle",
          "label": "Subtitle"
        },
        {
          "key": "url",
          "label": "URL"
        }
      ]
    }
  },
  {
    "key": "linkedin_company",
    "path": "/v1/linkedin/company",
    "method": "GET",
    "platform": "LinkedIn",
    "noun": "Company",
    "kind": "detail",
    "listKey": null,
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/linkedin-company",
    "action": {
      "label": "Find LinkedIn Company",
      "description": "Gets detailed information about a LinkedIn company page including description, follower count, industry, headquarters, employee count, founded year, specialities, locations, similar companies, and showcase pages. Pass the full company page URL. $0.006 per request after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "url",
        "label": "URL",
        "required": true,
        "type": "string",
        "helpText": "Full URL of the LinkedIn company page (e.g., `https://www.linkedin.com/company/google`). Max 500 characters.",
        "placeholder": "https://www.linkedin.com/company/visualsoft-uk-ltd"
      }
    ],
    "sample": {
      "call_to_action": {
        "text": "Visit website",
        "url": "https://goo.gle/3DLEokh"
      },
      "company_id": 1441,
      "cover_image": "https://media.licdn.com/dms/image/v2/D4E3DAQFmlG0pw29-sA/image-scale_191_1128/B4EZw1KzqwI0Ag-/0/1770418552101/google_cover?e=1775944800&v=beta&t=JGL-7elNtkEYBDkfyn7kC8MDAWR7fv9ubeur9jVW9vY",
      "description": "A problem isn't truly solved until it's solved for all. Googlers build products that help create opportunities for everyone, whether down the street or across the globe. Bring your insight, imaginati…",
      "domain": "linkedin.com",
      "employee_range": "10001-None",
      "employees": 339000,
      "followers": 41339226,
      "founded_year": null,
      "hashtag": "#google",
      "headquarters": {
        "address": "1600 Amphitheatre Parkway",
        "city": "Mountain View",
        "country": "US",
        "postal_code": "94043",
        "region": "CA"
      },
      "industry": "Software Development",
      "locations": [
        {
          "address": "St Giles High Street",
          "address_2": null,
          "city": "London",
          "country": "GB",
          "description": null,
          "is_headquarters": false,
          "postal_code": "WC2H 8AG",
          "region": "England"
        },
        {
          "address": "Barrow Street",
          "address_2": null,
          "city": "Dublin",
          "country": "IE",
          "description": null,
          "is_headquarters": false,
          "postal_code": null,
          "region": "County Dublin"
        },
        {
          "address": "Carrera 11A 94-45",
          "address_2": null,
          "city": "Bogota",
          "country": "CO",
          "description": null,
          "is_headquarters": false,
          "postal_code": "110221",
          "region": "Bogota, D.C."
        }
      ],
      "logo": "https://media.licdn.com/dms/image/v2/D4E0BAQGv3cqOuUMY7g/company-logo_100_100/B4EZmhegXHGcAU-/0/1759350753990/google_logo?e=1776902400&v=beta&t=LRCYpUl9rmgdri4awRP4FVlvccNARAtgcfqxtRHdedI",
      "name": "Google",
      "showcases": [
        {
          "followers": 33311,
          "name": "Android Enterprise",
          "url": "https://www.linkedin.com/showcase/androidenterprise/"
        },
        {
          "followers": 67576,
          "name": "Google Play business community",
          "url": "https://www.linkedin.com/showcase/googleplaybiz/"
        },
        {
          "followers": 53246,
          "name": "Android",
          "url": "https://www.linkedin.com/showcase/android_by_google/"
        }
      ],
      "similar_companies": [
        {
          "followers": 3874644,
          "industry": "Technology, Information and Internet",
          "logo": "https://media.licdn.com/dms/image/v2/D560BAQHlzyn1IsVxEw/company-logo_400_400/B56ZqiUJQ7I0AY-/0/1763659781488/googledevelopers_logo?e=1776902400&v=beta&t=Fxl_GUlew72MKmJOozrFlyNcOJGtK3BM0_A42gVTE8Y",
          "name": "Google for Developers",
          "url": "https://www.linkedin.com/showcase/googledevelopers/"
        },
        {
          "followers": 1079925,
          "industry": "Technology, Information and Internet",
          "logo": "https://media.licdn.com/dms/image/v2/D4E0BAQFko-zWIZk_pw/company-logo_100_100/B4EZhiRWKvHgAQ-/0/1753995371543/claude_logo?e=1776902400&v=beta&t=p62AWtHddVhCqKtOYSAlOA0EZzcpdnoz0gLsJcXy_0U",
          "name": "Claude",
          "url": "https://www.linkedin.com/showcase/claude/"
        },
        {
          "followers": 157674,
          "industry": "Non-profit Organizations",
          "logo": "https://media.licdn.com/dms/image/v2/D4D0BAQH0RfGBINXgTw/company-logo_200_200/company-logo_200_200/0/1735206950717/rozgar_organization_logo?e=1776902400&v=beta&t=4l31m7nIOQQPVQgd5yJa4kQPg7UfHV-qKRvBE…",
          "name": "Rozgar (روزگار)",
          "url": "https://www.linkedin.com/company/rozgar-organization/"
        }
      ],
      "source": "LinkedIn",
      "specialities": [
        "search",
        "ads",
        "mobile"
      ],
      "tagline": null,
      "universal_name": "google",
      "url": "https://www.linkedin.com/company/google/",
      "website": "https://goo.gle/3DLEokh"
    },
    "outputFields": [
      {
        "key": "call_to_action__text",
        "label": "Call To Action Text"
      },
      {
        "key": "call_to_action__url",
        "label": "Call To Action URL"
      },
      {
        "key": "company_id",
        "label": "Company ID",
        "type": "number"
      },
      {
        "key": "cover_image",
        "label": "Cover Image"
      },
      {
        "key": "description",
        "label": "Description"
      },
      {
        "key": "domain",
        "label": "Domain"
      },
      {
        "key": "employee_range",
        "label": "Employee Range"
      },
      {
        "key": "employees",
        "label": "Employees",
        "type": "number"
      },
      {
        "key": "followers",
        "label": "Followers",
        "type": "number"
      },
      {
        "key": "founded_year",
        "label": "Founded Year"
      },
      {
        "key": "hashtag",
        "label": "Hashtag"
      },
      {
        "key": "headquarters__address",
        "label": "Headquarters Address"
      },
      {
        "key": "headquarters__city",
        "label": "Headquarters City"
      },
      {
        "key": "headquarters__country",
        "label": "Headquarters Country"
      },
      {
        "key": "headquarters__postal_code",
        "label": "Headquarters Postal Code"
      },
      {
        "key": "headquarters__region",
        "label": "Headquarters Region"
      },
      {
        "key": "industry",
        "label": "Industry"
      },
      {
        "key": "locations[]address",
        "label": "Locations: Address"
      },
      {
        "key": "locations[]address_2",
        "label": "Locations: Address 2"
      },
      {
        "key": "locations[]city",
        "label": "Locations: City"
      },
      {
        "key": "locations[]country",
        "label": "Locations: Country"
      },
      {
        "key": "locations[]description",
        "label": "Locations: Description"
      },
      {
        "key": "locations[]is_headquarters",
        "label": "Locations: Is Headquarters",
        "type": "boolean"
      },
      {
        "key": "locations[]postal_code",
        "label": "Locations: Postal Code"
      },
      {
        "key": "locations[]region",
        "label": "Locations: Region"
      },
      {
        "key": "logo",
        "label": "Logo"
      },
      {
        "key": "name",
        "label": "Name"
      },
      {
        "key": "showcases[]followers",
        "label": "Showcases: Followers",
        "type": "number"
      },
      {
        "key": "showcases[]name",
        "label": "Showcases: Name"
      },
      {
        "key": "showcases[]url",
        "label": "Showcases: URL"
      },
      {
        "key": "similar_companies[]followers",
        "label": "Similar Companies: Followers",
        "type": "number"
      },
      {
        "key": "similar_companies[]industry",
        "label": "Similar Companies: Industry"
      },
      {
        "key": "similar_companies[]logo",
        "label": "Similar Companies: Logo"
      },
      {
        "key": "similar_companies[]name",
        "label": "Similar Companies: Name"
      },
      {
        "key": "similar_companies[]url",
        "label": "Similar Companies: URL"
      },
      {
        "key": "source",
        "label": "Source"
      },
      {
        "key": "specialities",
        "label": "Specialities",
        "list": true
      },
      {
        "key": "tagline",
        "label": "Tagline"
      },
      {
        "key": "universal_name",
        "label": "Universal Name"
      },
      {
        "key": "url",
        "label": "URL"
      },
      {
        "key": "website",
        "label": "Website"
      }
    ],
    "trigger": null
  },
  {
    "key": "linkedin_company_posts",
    "path": "/v1/linkedin/company/posts",
    "method": "GET",
    "platform": "LinkedIn",
    "noun": "Post",
    "kind": "list",
    "listKey": "posts",
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/linkedin-company-posts",
    "action": {
      "label": "Get LinkedIn Company Posts",
      "description": "Retrieves recent posts published by a specific LinkedIn company page. Returns post content, engagement metrics (likes, comments, shares, reaction breakdowns), author info, images, videos, and pagination info. Pass the full company page URL. $0.006 per request after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "url",
        "label": "URL",
        "required": true,
        "type": "string",
        "helpText": "Full URL of the LinkedIn company page (max 500 characters)",
        "placeholder": "https://www.linkedin.com/company/visualsoft-uk-ltd"
      },
      {
        "key": "page",
        "label": "Page Number",
        "required": false,
        "type": "integer",
        "default": "1",
        "helpText": "Page number, 1-50 (default: 1). 10 posts per page; LinkedIn serves a company page's newest 500 posts. Values below 1 are treated as 1; a page above 50 returns 400 (1-50).",
        "placeholder": "1"
      },
      {
        "key": "get_sentiment",
        "label": "Add Sentiment Analysis",
        "required": false,
        "type": "boolean",
        "helpText": "Set to true to add AI emotion analysis to each post. Adds a `sentiment` object containing `emotions` (joy, trust, fear, surprise, sadness, disgust, anger and anticipation, each scored 0-100), `dominant_emotion`, `emotional_intensity` (0-10), and `polarity` (positive, negative or neutral). Any post that cannot be scored returns `sentiment: null`."
      }
    ],
    "sample": {
      "count": 10,
      "page": 1,
      "posts": [
        {
          "author": "Google",
          "author_description": "41,339,226 followers",
          "author_image": "https://media.licdn.com/dms/image/v2/D4E0BAQGv3cqOuUMY7g/company-logo_100_100/B4EZmhegXHGcAU-/0/1759350753990/google_logo?e=1776902400&v=beta&t=LRCYpUl9rmgdri4awRP4FVlvccNARAtgcfqxtRHdedI",
          "author_url": "https://www.linkedin.com/company/google/posts",
          "comments": 66,
          "date": "2026-04-03T19:51:28Z",
          "domain": "linkedin.com",
          "images": [],
          "is_repost": false,
          "likes": 1320,
          "links": [
            "https://www.linkedin.com/company/googleworkspace/"
          ],
          "reactions": {
            "appreciation": 13,
            "empathy": 43,
            "entertainment": 1,
            "interest": 41,
            "like": 1195,
            "praise": 27
          },
          "shares": 38,
          "source": "LinkedIn",
          "text": "Last month, we gave Google Maps its biggest upgrade in a decade with Ask Maps and Immersive Navigation. We also made it easier to use Gemini in Google Workspace apps including Docs, Sheets, Slides an…",
          "url": "https://www.linkedin.com/feed/update/urn:li:activity:7445920930419195904",
          "urn": "urn:li:activity:7445920930419195904",
          "video": null
        },
        {
          "author": "Google",
          "author_description": "41,339,226 followers",
          "author_image": "https://media.licdn.com/dms/image/v2/D4E0BAQGv3cqOuUMY7g/company-logo_100_100/B4EZmhegXHGcAU-/0/1759350753990/google_logo?e=1776902400&v=beta&t=LRCYpUl9rmgdri4awRP4FVlvccNARAtgcfqxtRHdedI",
          "author_url": "https://www.linkedin.com/company/google/posts",
          "comments": 67,
          "date": "2026-04-02T18:10:18Z",
          "domain": "linkedin.com",
          "images": [],
          "is_repost": false,
          "likes": 678,
          "links": [],
          "reactions": {
            "appreciation": 7,
            "empathy": 30,
            "interest": 4,
            "like": 601,
            "praise": 36
          },
          "shares": 65,
          "source": "LinkedIn",
          "text": "New AI capabilities, powered by Lyria 3 and Veo 3.1, are starting to roll out to Google Vids. With these new features, you’ll be able to:\n\n✨ Generate high-quality video clips from just a simple promp…",
          "url": "https://www.linkedin.com/feed/update/urn:li:activity:7445533082427858945",
          "urn": "urn:li:activity:7445533082427858945",
          "video": {
            "duration": 26800,
            "thumbnail": "https://media.licdn.com/dms/image/v2/D5605AQHVQaAWXwPIYQ/videocover-low/B56Z1PY2eDKMBc-/0/1775153410325?e=1775944800&v=beta&t=P00Lwr88Qoi4IQoWmujZwytmDiZ345nwirC_7OdkUEk"
          }
        },
        {
          "author": "Google",
          "author_description": "41,339,226 followers",
          "author_image": "https://media.licdn.com/dms/image/v2/D4E0BAQGv3cqOuUMY7g/company-logo_100_100/B4EZmhegXHGcAU-/0/1759350753990/google_logo?e=1776902400&v=beta&t=LRCYpUl9rmgdri4awRP4FVlvccNARAtgcfqxtRHdedI",
          "author_url": "https://www.linkedin.com/company/google/posts",
          "comments": 142,
          "date": "2026-04-02T16:07:49Z",
          "domain": "linkedin.com",
          "images": [],
          "is_repost": false,
          "likes": 2030,
          "links": [],
          "reactions": {
            "appreciation": 13,
            "empathy": 145,
            "interest": 31,
            "like": 1690,
            "praise": 151
          },
          "shares": 311,
          "source": "LinkedIn",
          "text": "Today we're introducing Gemma 4 — our newest family of open models.\n\nBuilt from the same world-class research as Gemini 3, this family of models brings breakthrough intelligence directly to your own …",
          "url": "https://www.linkedin.com/feed/update/urn:li:activity:7445502258181705728",
          "urn": "urn:li:activity:7445502258181705728",
          "video": {
            "duration": 171666,
            "thumbnail": "https://media.licdn.com/dms/image/v2/D5605AQFM8Yi47O2mFA/feedshare-thumbnail_720_1280/B56Z1O8v6.I8A4-/0/1775146043433?e=1775944800&v=beta&t=pxhsAnirhuNKhU-8UF87Ng1Du6nZf7rgFVvb-SDhtbs"
          }
        }
      ],
      "total": 356
    },
    "outputFields": [
      {
        "key": "count",
        "label": "Count",
        "type": "number"
      },
      {
        "key": "page",
        "label": "Page",
        "type": "number"
      },
      {
        "key": "posts[]author",
        "label": "Posts: Author"
      },
      {
        "key": "posts[]author_description",
        "label": "Posts: Author Description"
      },
      {
        "key": "posts[]author_image",
        "label": "Posts: Author Image"
      },
      {
        "key": "posts[]author_url",
        "label": "Posts: Author URL"
      },
      {
        "key": "posts[]comments",
        "label": "Posts: Comments",
        "type": "number"
      },
      {
        "key": "posts[]date",
        "label": "Posts: Date"
      },
      {
        "key": "posts[]domain",
        "label": "Posts: Domain"
      },
      {
        "key": "posts[]images",
        "label": "Posts: Images",
        "list": true
      },
      {
        "key": "posts[]is_repost",
        "label": "Posts: Is Repost",
        "type": "boolean"
      },
      {
        "key": "posts[]likes",
        "label": "Posts: Likes",
        "type": "number"
      },
      {
        "key": "posts[]links",
        "label": "Posts: Links",
        "list": true
      },
      {
        "key": "posts[]reactions__appreciation",
        "label": "Reactions Appreciation",
        "type": "number"
      },
      {
        "key": "posts[]reactions__empathy",
        "label": "Reactions Empathy",
        "type": "number"
      },
      {
        "key": "posts[]reactions__entertainment",
        "label": "Reactions Entertainment",
        "type": "number"
      },
      {
        "key": "posts[]reactions__interest",
        "label": "Reactions Interest",
        "type": "number"
      },
      {
        "key": "posts[]reactions__like",
        "label": "Reactions Like",
        "type": "number"
      },
      {
        "key": "posts[]reactions__praise",
        "label": "Reactions Praise",
        "type": "number"
      },
      {
        "key": "posts[]shares",
        "label": "Posts: Shares",
        "type": "number"
      },
      {
        "key": "posts[]source",
        "label": "Posts: Source"
      },
      {
        "key": "posts[]text",
        "label": "Posts: Text"
      },
      {
        "key": "posts[]url",
        "label": "Posts: URL"
      },
      {
        "key": "posts[]urn",
        "label": "Posts: URN"
      },
      {
        "key": "posts[]video",
        "label": "Posts: Video"
      },
      {
        "key": "total",
        "label": "Total",
        "type": "number"
      }
    ],
    "trigger": {
      "label": "New LinkedIn Company Post",
      "description": "Triggers when a LinkedIn company page publishes a new post. Each check runs Get LinkedIn Company Posts ($0.006 per request after the free tier (50 requests/month)).",
      "inputFields": [
        {
          "key": "url",
          "label": "URL",
          "required": true,
          "type": "string",
          "helpText": "Full URL of the LinkedIn company page (max 500 characters)",
          "placeholder": "https://www.linkedin.com/company/visualsoft-uk-ltd"
        },
        {
          "key": "page",
          "label": "Page Number",
          "required": false,
          "type": "integer",
          "default": "1",
          "helpText": "Page number, 1-50 (default: 1). 10 posts per page; LinkedIn serves a company page's newest 500 posts. Values below 1 are treated as 1; a page above 50 returns 400 (1-50).",
          "placeholder": "1"
        },
        {
          "key": "get_sentiment",
          "label": "Add Sentiment Analysis",
          "required": false,
          "type": "boolean",
          "helpText": "Set to true to add AI emotion analysis to each post. Adds a `sentiment` object containing `emotions` (joy, trust, fear, surprise, sadness, disgust, anger and anticipation, each scored 0-100), `dominant_emotion`, `emotional_intensity` (0-10), and `polarity` (positive, negative or neutral). Any post that cannot be scored returns `sentiment: null`."
        }
      ],
      "sample": {
        "id": "urn:li:activity:7445920930419195904",
        "author": "Google",
        "author_description": "41,339,226 followers",
        "author_image": "https://media.licdn.com/dms/image/v2/D4E0BAQGv3cqOuUMY7g/company-logo_100_100/B4EZmhegXHGcAU-/0/1759350753990/google_logo?e=1776902400&v=beta&t=LRCYpUl9rmgdri4awRP4FVlvccNARAtgcfqxtRHdedI",
        "author_url": "https://www.linkedin.com/company/google/posts",
        "comments": 66,
        "date": "2026-04-03T19:51:28Z",
        "domain": "linkedin.com",
        "images": [],
        "is_repost": false,
        "likes": 1320,
        "links": [
          "https://www.linkedin.com/company/googleworkspace/"
        ],
        "reactions": {
          "appreciation": 13,
          "empathy": 43,
          "entertainment": 1,
          "interest": 41,
          "like": 1195,
          "praise": 27
        },
        "shares": 38,
        "source": "LinkedIn",
        "text": "Last month, we gave Google Maps its biggest upgrade in a decade with Ask Maps and Immersive Navigation. We also made it easier to use Gemini in Google Workspace apps including Docs, Sheets, Slides an…",
        "url": "https://www.linkedin.com/feed/update/urn:li:activity:7445920930419195904",
        "urn": "urn:li:activity:7445920930419195904",
        "video": null
      },
      "outputFields": [
        {
          "key": "id",
          "label": "ID",
          "primary": true
        },
        {
          "key": "author",
          "label": "Author"
        },
        {
          "key": "author_description",
          "label": "Author Description"
        },
        {
          "key": "author_image",
          "label": "Author Image"
        },
        {
          "key": "author_url",
          "label": "Author URL"
        },
        {
          "key": "comments",
          "label": "Comments",
          "type": "number"
        },
        {
          "key": "date",
          "label": "Date"
        },
        {
          "key": "domain",
          "label": "Domain"
        },
        {
          "key": "images",
          "label": "Images",
          "list": true
        },
        {
          "key": "is_repost",
          "label": "Is Repost",
          "type": "boolean"
        },
        {
          "key": "likes",
          "label": "Likes",
          "type": "number"
        },
        {
          "key": "links",
          "label": "Links",
          "list": true
        },
        {
          "key": "reactions__appreciation",
          "label": "Reactions Appreciation",
          "type": "number"
        },
        {
          "key": "reactions__empathy",
          "label": "Reactions Empathy",
          "type": "number"
        },
        {
          "key": "reactions__entertainment",
          "label": "Reactions Entertainment",
          "type": "number"
        },
        {
          "key": "reactions__interest",
          "label": "Reactions Interest",
          "type": "number"
        },
        {
          "key": "reactions__like",
          "label": "Reactions Like",
          "type": "number"
        },
        {
          "key": "reactions__praise",
          "label": "Reactions Praise",
          "type": "number"
        },
        {
          "key": "shares",
          "label": "Shares",
          "type": "number"
        },
        {
          "key": "source",
          "label": "Source"
        },
        {
          "key": "text",
          "label": "Text"
        },
        {
          "key": "url",
          "label": "URL"
        },
        {
          "key": "urn",
          "label": "URN"
        },
        {
          "key": "video",
          "label": "Video"
        }
      ]
    }
  },
  {
    "key": "linkedin_jobs",
    "path": "/v1/linkedin/jobs",
    "method": "GET",
    "platform": "LinkedIn",
    "noun": "Job",
    "kind": "list",
    "listKey": "jobs",
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/linkedin-jobs",
    "action": {
      "label": "Search LinkedIn Jobs",
      "description": "Searches for LinkedIn job listings by keyword. Returns job title, company, location, posting date, job type, experience level, workplace type, industry, salary, benefits, full description, applicants, and company logo. Supports filtering by recency, job type, company, and location. $0.006 per request after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "query",
        "label": "Search Query",
        "required": true,
        "type": "string",
        "helpText": "Search query (max 500 characters)",
        "placeholder": "software engineer"
      },
      {
        "key": "page",
        "label": "Page Number",
        "required": false,
        "type": "integer",
        "default": "1",
        "helpText": "Page number for pagination (1-40). 25 jobs per page; LinkedIn shows only the first 40 pages of results. Values below 1 are treated as 1; a page above 40 returns 400 (1-40).",
        "placeholder": "1"
      },
      {
        "key": "sort_by",
        "label": "Sort By",
        "required": false,
        "type": "string",
        "default": "relevance",
        "helpText": "Sort order for results",
        "choices": {
          "most_recent": "Most Recent",
          "relevance": "Relevance"
        },
        "placeholder": "relevance"
      },
      {
        "key": "posted_ago",
        "label": "Posted Within",
        "required": false,
        "type": "string",
        "helpText": "Filter by maximum job age. Defaults to all time when omitted.",
        "choices": {
          "1h": "Last hour",
          "24h": "Last 24 hours",
          "7d": "Last 7 days",
          "30d": "Last 30 days"
        }
      },
      {
        "key": "job_type",
        "label": "Job Type",
        "required": false,
        "type": "string",
        "helpText": "Filter by employment type. Comma-separate multiple values (e.g., `full_time,contract`). Allowed values: full_time, part_time, contract, temporary, volunteer, internship, other. Any other value returns 400."
      },
      {
        "key": "company_ids",
        "label": "Company IDs",
        "required": false,
        "type": "string",
        "helpText": "Filter by company. Comma-separated LinkedIn company IDs (get IDs from the Search Companies endpoint)."
      },
      {
        "key": "location_id",
        "label": "Location ID",
        "required": false,
        "type": "string",
        "helpText": "Filter by location. A numeric LinkedIn location ID. Non-numeric values return 400.",
        "placeholder": "103644278"
      }
    ],
    "sample": {
      "jobs": [
        {
          "title": "Senior Software Engineer",
          "url": "https://www.linkedin.com/jobs/view/4417833240/",
          "company": "Stripe",
          "company_id": "2135371",
          "company_url": "https://www.linkedin.com/company/stripe",
          "company_logo": "https://media.licdn.com/dms/image/.../company-logo.jpg",
          "location": "San Francisco, CA",
          "date": "2026-05-20T14:30:00Z",
          "job_type": "full_time",
          "experience_level": "mid_senior",
          "workplace_type": "hybrid",
          "industry": "Technology, Information and Internet",
          "job_functions": "ENG, IT",
          "description": "We are looking for a Senior Software Engineer to join our team...",
          "salary": "$180,000 - $250,000",
          "benefits": "",
          "apply_url": "https://stripe.com/jobs/listing/senior-software-engineer/1234",
          "applicants": "200+ applicants"
        }
      ],
      "page": 1,
      "count": 25
    },
    "outputFields": [
      {
        "key": "jobs[]title",
        "label": "Jobs: Title"
      },
      {
        "key": "jobs[]url",
        "label": "Jobs: URL"
      },
      {
        "key": "jobs[]company",
        "label": "Jobs: Company"
      },
      {
        "key": "jobs[]company_id",
        "label": "Jobs: Company ID"
      },
      {
        "key": "jobs[]company_url",
        "label": "Jobs: Company URL"
      },
      {
        "key": "jobs[]company_logo",
        "label": "Jobs: Company Logo"
      },
      {
        "key": "jobs[]location",
        "label": "Jobs: Location"
      },
      {
        "key": "jobs[]date",
        "label": "Jobs: Date"
      },
      {
        "key": "jobs[]job_type",
        "label": "Jobs: Job Type"
      },
      {
        "key": "jobs[]experience_level",
        "label": "Jobs: Experience Level"
      },
      {
        "key": "jobs[]workplace_type",
        "label": "Jobs: Workplace Type"
      },
      {
        "key": "jobs[]industry",
        "label": "Jobs: Industry"
      },
      {
        "key": "jobs[]job_functions",
        "label": "Jobs: Job Functions"
      },
      {
        "key": "jobs[]description",
        "label": "Jobs: Description"
      },
      {
        "key": "jobs[]salary",
        "label": "Jobs: Salary"
      },
      {
        "key": "jobs[]benefits",
        "label": "Jobs: Benefits"
      },
      {
        "key": "jobs[]apply_url",
        "label": "Jobs: Apply URL"
      },
      {
        "key": "jobs[]applicants",
        "label": "Jobs: Applicants"
      },
      {
        "key": "page",
        "label": "Page",
        "type": "number"
      },
      {
        "key": "count",
        "label": "Count",
        "type": "number"
      }
    ],
    "trigger": {
      "label": "New LinkedIn Job Matching Search",
      "description": "Triggers when a new LinkedIn job listing matches your search. Each check runs Search LinkedIn Jobs ($0.006 per request after the free tier (50 requests/month)).",
      "inputFields": [
        {
          "key": "query",
          "label": "Search Query",
          "required": true,
          "type": "string",
          "helpText": "Search query (max 500 characters)",
          "placeholder": "software engineer"
        },
        {
          "key": "page",
          "label": "Page Number",
          "required": false,
          "type": "integer",
          "default": "1",
          "helpText": "Page number for pagination (1-40). 25 jobs per page; LinkedIn shows only the first 40 pages of results. Values below 1 are treated as 1; a page above 40 returns 400 (1-40).",
          "placeholder": "1"
        },
        {
          "key": "sort_by",
          "label": "Sort By",
          "required": false,
          "type": "string",
          "default": "most_recent",
          "helpText": "Sort order for results",
          "choices": {
            "most_recent": "Most Recent",
            "relevance": "Relevance"
          },
          "placeholder": "relevance"
        },
        {
          "key": "posted_ago",
          "label": "Posted Within",
          "required": false,
          "type": "string",
          "helpText": "Filter by maximum job age. Defaults to all time when omitted.",
          "choices": {
            "1h": "Last hour",
            "24h": "Last 24 hours",
            "7d": "Last 7 days",
            "30d": "Last 30 days"
          }
        },
        {
          "key": "job_type",
          "label": "Job Type",
          "required": false,
          "type": "string",
          "helpText": "Filter by employment type. Comma-separate multiple values (e.g., `full_time,contract`). Allowed values: full_time, part_time, contract, temporary, volunteer, internship, other. Any other value returns 400."
        },
        {
          "key": "company_ids",
          "label": "Company IDs",
          "required": false,
          "type": "string",
          "helpText": "Filter by company. Comma-separated LinkedIn company IDs (get IDs from the Search Companies endpoint)."
        },
        {
          "key": "location_id",
          "label": "Location ID",
          "required": false,
          "type": "string",
          "helpText": "Filter by location. A numeric LinkedIn location ID. Non-numeric values return 400.",
          "placeholder": "103644278"
        }
      ],
      "sample": {
        "id": "https://www.linkedin.com/jobs/view/4417833240/",
        "title": "Senior Software Engineer",
        "url": "https://www.linkedin.com/jobs/view/4417833240/",
        "company": "Stripe",
        "company_id": "2135371",
        "company_url": "https://www.linkedin.com/company/stripe",
        "company_logo": "https://media.licdn.com/dms/image/.../company-logo.jpg",
        "location": "San Francisco, CA",
        "date": "2026-05-20T14:30:00Z",
        "job_type": "full_time",
        "experience_level": "mid_senior",
        "workplace_type": "hybrid",
        "industry": "Technology, Information and Internet",
        "job_functions": "ENG, IT",
        "description": "We are looking for a Senior Software Engineer to join our team...",
        "salary": "$180,000 - $250,000",
        "benefits": "",
        "apply_url": "https://stripe.com/jobs/listing/senior-software-engineer/1234",
        "applicants": "200+ applicants"
      },
      "outputFields": [
        {
          "key": "id",
          "label": "ID",
          "primary": true
        },
        {
          "key": "title",
          "label": "Title"
        },
        {
          "key": "url",
          "label": "URL"
        },
        {
          "key": "company",
          "label": "Company"
        },
        {
          "key": "company_id",
          "label": "Company ID"
        },
        {
          "key": "company_url",
          "label": "Company URL"
        },
        {
          "key": "company_logo",
          "label": "Company Logo"
        },
        {
          "key": "location",
          "label": "Location"
        },
        {
          "key": "date",
          "label": "Date"
        },
        {
          "key": "job_type",
          "label": "Job Type"
        },
        {
          "key": "experience_level",
          "label": "Experience Level"
        },
        {
          "key": "workplace_type",
          "label": "Workplace Type"
        },
        {
          "key": "industry",
          "label": "Industry"
        },
        {
          "key": "job_functions",
          "label": "Job Functions"
        },
        {
          "key": "description",
          "label": "Description"
        },
        {
          "key": "salary",
          "label": "Salary"
        },
        {
          "key": "benefits",
          "label": "Benefits"
        },
        {
          "key": "apply_url",
          "label": "Apply URL"
        },
        {
          "key": "applicants",
          "label": "Applicants"
        }
      ]
    }
  },
  {
    "key": "linkedin_job",
    "path": "/v1/linkedin/job",
    "method": "GET",
    "platform": "LinkedIn",
    "noun": "Job",
    "kind": "detail",
    "listKey": null,
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/linkedin-job",
    "action": {
      "label": "Find LinkedIn Job",
      "description": "Gets detailed information about a specific LinkedIn job listing by URL or numeric job ID. Returns job title, company, location, posting date, job type, experience level, workplace type, industry, salary, benefits, full description, applicants, apply URL, and company logo. $0.002 per request after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "url",
        "label": "URL",
        "required": true,
        "type": "string",
        "helpText": "LinkedIn job URL (e.g., `https://linkedin.com/jobs/view/1234567890`) or numeric job ID. Max 500 characters.",
        "placeholder": "https://linkedin.com/jobs/view/4417833240"
      }
    ],
    "sample": {
      "title": "Senior Software Engineer",
      "url": "https://www.linkedin.com/jobs/view/4417833240/",
      "company": "Stripe",
      "company_id": "2135371",
      "company_url": "https://www.linkedin.com/company/stripe",
      "company_logo": "https://media.licdn.com/dms/image/.../company-logo.jpg",
      "location": "San Francisco, CA",
      "date": "2026-05-20T14:30:00Z",
      "job_type": "full_time",
      "experience_level": "mid_senior",
      "workplace_type": "hybrid",
      "industry": "Technology, Information and Internet",
      "job_functions": "ENG, IT",
      "description": "We are looking for a Senior Software Engineer to join our team...",
      "salary": "$180,000 - $250,000",
      "benefits": "",
      "apply_url": "https://stripe.com/jobs/listing/senior-software-engineer/1234",
      "applicants": "200+ applicants"
    },
    "outputFields": [
      {
        "key": "title",
        "label": "Title"
      },
      {
        "key": "url",
        "label": "URL"
      },
      {
        "key": "company",
        "label": "Company"
      },
      {
        "key": "company_id",
        "label": "Company ID"
      },
      {
        "key": "company_url",
        "label": "Company URL"
      },
      {
        "key": "company_logo",
        "label": "Company Logo"
      },
      {
        "key": "location",
        "label": "Location"
      },
      {
        "key": "date",
        "label": "Date"
      },
      {
        "key": "job_type",
        "label": "Job Type"
      },
      {
        "key": "experience_level",
        "label": "Experience Level"
      },
      {
        "key": "workplace_type",
        "label": "Workplace Type"
      },
      {
        "key": "industry",
        "label": "Industry"
      },
      {
        "key": "job_functions",
        "label": "Job Functions"
      },
      {
        "key": "description",
        "label": "Description"
      },
      {
        "key": "salary",
        "label": "Salary"
      },
      {
        "key": "benefits",
        "label": "Benefits"
      },
      {
        "key": "apply_url",
        "label": "Apply URL"
      },
      {
        "key": "applicants",
        "label": "Applicants"
      }
    ],
    "trigger": null
  }
];
