// Generated by scripts/generate.py from spec/openapi.json. Do not edit by hand;
// change the spec or the generator and run `npm run generate`.
module.exports = [
  {
    "key": "reddit_posts",
    "path": "/v1/reddit/posts",
    "method": "GET",
    "platform": "Reddit",
    "noun": "Post",
    "kind": "list",
    "listKey": "posts",
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/reddit-posts",
    "action": {
      "label": "Search Reddit Posts",
      "description": "Searches for Reddit posts by keyword across all subreddits. Returns post title, URL, author, subreddit, content snippet (the post body, or the title when the post has no body), upvotes, upvote ratio, comment count, and crosspost count. Supports sort by hot, top, most recent, or relevance, and an optional time window (posted_ago) from the past hour to the past year. Each page returns up to 20 posts, and pages 1 to 12 cover up to 250 posts per query. $0.003 per request after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "query",
        "label": "Search Query",
        "required": true,
        "type": "string",
        "helpText": "Search query (max 500 characters). Reddit search operators are supported, including AND, OR, NOT, exclusion with -, grouping with ( ), and fields such as subreddit: and author:.",
        "placeholder": "programming"
      },
      {
        "key": "page",
        "label": "Page Number",
        "required": false,
        "type": "integer",
        "default": "1",
        "helpText": "Page number for pagination (1-12). Each page returns up to 20 posts (1-12).",
        "placeholder": "1"
      },
      {
        "key": "sort_by",
        "label": "Sort By",
        "required": false,
        "type": "string",
        "default": "most_recent",
        "helpText": "Sort order for results",
        "choices": {
          "most_recent": "Most Recent",
          "relevance": "Relevance",
          "hot": "Hot",
          "top": "Top"
        },
        "placeholder": "hot"
      },
      {
        "key": "posted_ago",
        "label": "Posted Within",
        "required": false,
        "type": "string",
        "helpText": "Only return posts from this period: 1h (past hour), 24h (past day), 7d (past week), 30d (past month), or 12m (past year). Works with every sort_by, e.g. sort_by=relevance with posted_ago=24h returns the most relevant posts of the past day. Omit for all time. Any other value returns 400.",
        "choices": {
          "1h": "Last hour",
          "24h": "Last 24 hours",
          "7d": "Last 7 days",
          "30d": "Last 30 days",
          "12m": "Last 12 months"
        }
      },
      {
        "key": "get_sentiment",
        "label": "Add Sentiment Analysis",
        "required": false,
        "type": "boolean",
        "helpText": "Set to true to add AI emotion analysis to each post. Adds a `sentiment` object containing `emotions` (joy, trust, fear, surprise, sadness, disgust, anger and anticipation, each scored 0-100), `dominant_emotion`, `emotional_intensity` (0-10), and `polarity` (positive, negative or neutral). Any post that cannot be scored returns `sentiment: null`."
      }
    ],
    "sample": {
      "count": 20,
      "page": 1,
      "posts": [
        {
          "author": "Even_Drawer_421",
          "date": "2026-04-04T21:10:56Z",
          "domain": "reddit.com",
          "snippet": "Hey! I'm considering doing my masters in Computer Science at Georgia Tech (in-person) and I was wondering how the classes / research community is like in GT? I would be doing the robotics / perceptio…",
          "source": "Reddit",
          "subreddit": "GatechClasses",
          "title": "Current GT MSCS students (Robotics/Perception): What are classes, labs, and recruiting like?",
          "upvotes": 14,
          "upvote_ratio": 0.92,
          "comments": 6,
          "crossposts": 0,
          "url": "https://www.reddit.com/r/GatechClasses/comments/1sckutj/current_gt_mscs_students_roboticsperception_what/"
        },
        {
          "author": "Efficient_Log_2007",
          "date": "2026-04-04T21:09:22Z",
          "domain": "reddit.com",
          "snippet": "Inspired by the best TV shows of 2026 post earlier. I am looking for some book recommendations. I am currently reading Artificial Wisdom. Set in 2050, the climate crisis has reached peak levels, one …",
          "source": "Reddit",
          "subreddit": "AskIreland",
          "title": "What's Ireland Reading Right Now.",
          "upvotes": 42,
          "upvote_ratio": 0.95,
          "comments": 38,
          "crossposts": 0,
          "url": "https://www.reddit.com/r/AskIreland/comments/1scktgg/whats_ireland_reading_right_now/"
        },
        {
          "author": "Pretty-Release5924",
          "date": "2026-04-04T20:58:45Z",
          "domain": "reddit.com",
          "snippet": "Please give feedback on my resume. May 2026 Grad. 900+ application, 1 interview only",
          "source": "Reddit",
          "subreddit": "cscareeradvice",
          "title": "Please give feedback on my resume. May 2026 Grad. 900+ application, 1 interview only",
          "upvotes": 87,
          "upvote_ratio": 0.88,
          "comments": 124,
          "crossposts": 1,
          "url": "https://www.reddit.com/r/cscareeradvice/comments/1sckjsy/please_give_feedback_on_my_resume_may_2026_grad/"
        }
      ]
    },
    "outputFields": [
      {
        "key": "count",
        "label": "Count",
        "type": "number"
      },
      {
        "key": "page",
        "label": "Page",
        "type": "number"
      },
      {
        "key": "posts[]author",
        "label": "Posts: Author"
      },
      {
        "key": "posts[]date",
        "label": "Posts: Date"
      },
      {
        "key": "posts[]domain",
        "label": "Posts: Domain"
      },
      {
        "key": "posts[]snippet",
        "label": "Posts: Snippet"
      },
      {
        "key": "posts[]source",
        "label": "Posts: Source"
      },
      {
        "key": "posts[]subreddit",
        "label": "Posts: Subreddit"
      },
      {
        "key": "posts[]title",
        "label": "Posts: Title"
      },
      {
        "key": "posts[]upvotes",
        "label": "Posts: Upvotes",
        "type": "number"
      },
      {
        "key": "posts[]upvote_ratio",
        "label": "Posts: Upvote Ratio",
        "type": "number"
      },
      {
        "key": "posts[]comments",
        "label": "Posts: Comments",
        "type": "number"
      },
      {
        "key": "posts[]crossposts",
        "label": "Posts: Crossposts",
        "type": "number"
      },
      {
        "key": "posts[]url",
        "label": "Posts: URL"
      }
    ],
    "trigger": {
      "label": "New Reddit Post Matching Search",
      "description": "Triggers when a new Reddit post matches your search. Each check runs Search Reddit Posts ($0.003 per request after the free tier (50 requests/month)).",
      "inputFields": [
        {
          "key": "query",
          "label": "Search Query",
          "required": true,
          "type": "string",
          "helpText": "Search query (max 500 characters). Reddit search operators are supported, including AND, OR, NOT, exclusion with -, grouping with ( ), and fields such as subreddit: and author:.",
          "placeholder": "programming"
        },
        {
          "key": "page",
          "label": "Page Number",
          "required": false,
          "type": "integer",
          "default": "1",
          "helpText": "Page number for pagination (1-12). Each page returns up to 20 posts (1-12).",
          "placeholder": "1"
        },
        {
          "key": "sort_by",
          "label": "Sort By",
          "required": false,
          "type": "string",
          "default": "most_recent",
          "helpText": "Sort order for results",
          "choices": {
            "most_recent": "Most Recent",
            "relevance": "Relevance",
            "hot": "Hot",
            "top": "Top"
          },
          "placeholder": "hot"
        },
        {
          "key": "posted_ago",
          "label": "Posted Within",
          "required": false,
          "type": "string",
          "helpText": "Only return posts from this period: 1h (past hour), 24h (past day), 7d (past week), 30d (past month), or 12m (past year). Works with every sort_by, e.g. sort_by=relevance with posted_ago=24h returns the most relevant posts of the past day. Omit for all time. Any other value returns 400.",
          "choices": {
            "1h": "Last hour",
            "24h": "Last 24 hours",
            "7d": "Last 7 days",
            "30d": "Last 30 days",
            "12m": "Last 12 months"
          }
        },
        {
          "key": "get_sentiment",
          "label": "Add Sentiment Analysis",
          "required": false,
          "type": "boolean",
          "helpText": "Set to true to add AI emotion analysis to each post. Adds a `sentiment` object containing `emotions` (joy, trust, fear, surprise, sadness, disgust, anger and anticipation, each scored 0-100), `dominant_emotion`, `emotional_intensity` (0-10), and `polarity` (positive, negative or neutral). Any post that cannot be scored returns `sentiment: null`."
        }
      ],
      "sample": {
        "id": "https://www.reddit.com/r/GatechClasses/comments/1sckutj/current_gt_mscs_students_roboticsperception_what/",
        "author": "Even_Drawer_421",
        "date": "2026-04-04T21:10:56Z",
        "domain": "reddit.com",
        "snippet": "Hey! I'm considering doing my masters in Computer Science at Georgia Tech (in-person) and I was wondering how the classes / research community is like in GT? I would be doing the robotics / perceptio…",
        "source": "Reddit",
        "subreddit": "GatechClasses",
        "title": "Current GT MSCS students (Robotics/Perception): What are classes, labs, and recruiting like?",
        "upvotes": 14,
        "upvote_ratio": 0.92,
        "comments": 6,
        "crossposts": 0,
        "url": "https://www.reddit.com/r/GatechClasses/comments/1sckutj/current_gt_mscs_students_roboticsperception_what/"
      },
      "outputFields": [
        {
          "key": "id",
          "label": "ID",
          "primary": true
        },
        {
          "key": "author",
          "label": "Author"
        },
        {
          "key": "date",
          "label": "Date"
        },
        {
          "key": "domain",
          "label": "Domain"
        },
        {
          "key": "snippet",
          "label": "Snippet"
        },
        {
          "key": "source",
          "label": "Source"
        },
        {
          "key": "subreddit",
          "label": "Subreddit"
        },
        {
          "key": "title",
          "label": "Title"
        },
        {
          "key": "upvotes",
          "label": "Upvotes",
          "type": "number"
        },
        {
          "key": "upvote_ratio",
          "label": "Upvote Ratio",
          "type": "number"
        },
        {
          "key": "comments",
          "label": "Comments",
          "type": "number"
        },
        {
          "key": "crossposts",
          "label": "Crossposts",
          "type": "number"
        },
        {
          "key": "url",
          "label": "URL"
        }
      ]
    }
  },
  {
    "key": "reddit_comments",
    "path": "/v1/reddit/comments",
    "method": "GET",
    "platform": "Reddit",
    "noun": "Comment",
    "kind": "list",
    "listKey": "posts",
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/reddit-comments",
    "action": {
      "label": "Search Reddit Comments",
      "description": "Searches for Reddit comments by keyword across all subreddits. Returns comment text, a link for the parent post, subreddit, author, comment upvotes, and parent post engagement metrics. Supports fetching multiple pages in a single API call (billed per page). AutoModerator comments are filtered out, and comments are matched against your query text, so a page can return fewer results than the page size. The url field points at the parent post and can be an off-site link when the post links to another domain. upvotes is null when the comment score is hidden, and post_upvotes / post_comments are null when the parent post's metrics are unavailable. $0.003 per page after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "query",
        "label": "Search Query",
        "required": true,
        "type": "string",
        "helpText": "Search query (max 500 characters)",
        "placeholder": "python"
      },
      {
        "key": "pages",
        "label": "Pages to Fetch",
        "required": false,
        "type": "integer",
        "default": "1",
        "helpText": "Number of pages to fetch and merge (1-10). Billed per page (1-10).",
        "placeholder": "2"
      },
      {
        "key": "sort_by",
        "label": "Sort By",
        "required": false,
        "type": "string",
        "default": "most_recent",
        "helpText": "Sort order for results",
        "choices": {
          "most_recent": "Most Recent",
          "relevance": "Relevance",
          "top": "Top"
        },
        "placeholder": "relevance"
      },
      {
        "key": "get_sentiment",
        "label": "Add Sentiment Analysis",
        "required": false,
        "type": "boolean",
        "helpText": "Set to true to add AI emotion analysis to each comment (returned in the `posts` array). Adds a `sentiment` object containing `emotions` (joy, trust, fear, surprise, sadness, disgust, anger and anticipation, each scored 0-100), `dominant_emotion`, `emotional_intensity` (0-10), and `polarity` (positive, negative or neutral). Any comment that cannot be scored returns `sentiment: null`."
      }
    ],
    "sample": {
      "count": 18,
      "pages": 1,
      "posts": [
        {
          "author": "Lawsoffire",
          "date": "2026-04-04T21:12:30Z",
          "domain": "reddit.com",
          "snippet": "In the context of a post-2023 world, I really don't feel that a program doing what its programmed to, but now the input and output is somewhat dynamic qualifies on anywhere near the same linguistic s…",
          "source": "Reddit (Comment)",
          "subreddit": "pcgaming",
          "title": "Lawsoffire on pcgaming",
          "type": "comment",
          "upvotes": 87,
          "post_upvotes": 2341,
          "post_comments": 312,
          "url": "https://www.gamespot.com/articles/nothing-in-our-games-will-be-ai-generated-ever-says-warframe-director/1100-6539194/"
        },
        {
          "author": "LiquidAether",
          "date": "2026-04-04T21:07:13Z",
          "domain": "reddit.com",
          "snippet": "LLMs are basically unrelated to actual artificial intelligence. And breakthroughs in that direction will have to come from a different source.",
          "source": "Reddit (Comment)",
          "subreddit": "movies",
          "title": "LiquidAether on movies",
          "type": "comment",
          "upvotes": 42,
          "post_upvotes": 1850,
          "post_comments": 274,
          "url": "https://www.reddit.com/r/movies/comments/1scjg3o/movie_plots_that_are_uncomfortably_close_to/"
        },
        {
          "author": "sajberhippien",
          "date": "2026-04-04T21:01:44Z",
          "domain": "reddit.com",
          "snippet": "> There is actually value in not claiming every stupid automation is in some way artificial intelligence. Windmills are automation, and noone is claiming a windmill is artificial intelligence. But th…",
          "source": "Reddit (Comment)",
          "subreddit": "gaming",
          "title": "sajberhippien on gaming",
          "type": "comment",
          "upvotes": 56,
          "post_upvotes": 4120,
          "post_comments": 489,
          "url": "https://www.engadget.com/gaming/take-two-laid-off-the-head-its-ai-division-and-an-undisclosed-number-of-staff-182824338.html"
        }
      ]
    },
    "outputFields": [
      {
        "key": "count",
        "label": "Count",
        "type": "number"
      },
      {
        "key": "pages",
        "label": "Pages",
        "type": "number"
      },
      {
        "key": "posts[]author",
        "label": "Posts: Author"
      },
      {
        "key": "posts[]date",
        "label": "Posts: Date"
      },
      {
        "key": "posts[]domain",
        "label": "Posts: Domain"
      },
      {
        "key": "posts[]snippet",
        "label": "Posts: Snippet"
      },
      {
        "key": "posts[]source",
        "label": "Posts: Source"
      },
      {
        "key": "posts[]subreddit",
        "label": "Posts: Subreddit"
      },
      {
        "key": "posts[]title",
        "label": "Posts: Title"
      },
      {
        "key": "posts[]type",
        "label": "Posts: Type"
      },
      {
        "key": "posts[]upvotes",
        "label": "Posts: Upvotes",
        "type": "number"
      },
      {
        "key": "posts[]post_upvotes",
        "label": "Posts: Post Upvotes",
        "type": "number"
      },
      {
        "key": "posts[]post_comments",
        "label": "Posts: Post Comments",
        "type": "number"
      },
      {
        "key": "posts[]url",
        "label": "Posts: URL"
      }
    ],
    "trigger": {
      "label": "New Reddit Comment Matching Search",
      "description": "Triggers when a new Reddit comment matches your search. Each check runs Search Reddit Comments ($0.003 per page after the free tier (50 requests/month)).",
      "inputFields": [
        {
          "key": "query",
          "label": "Search Query",
          "required": true,
          "type": "string",
          "helpText": "Search query (max 500 characters)",
          "placeholder": "python"
        },
        {
          "key": "pages",
          "label": "Pages to Fetch",
          "required": false,
          "type": "integer",
          "default": "1",
          "helpText": "Number of pages to fetch and merge (1-10). Billed per page (1-10). Every check of this trigger fetches this many pages, each billed as one request.",
          "placeholder": "2"
        },
        {
          "key": "sort_by",
          "label": "Sort By",
          "required": false,
          "type": "string",
          "default": "most_recent",
          "helpText": "Sort order for results",
          "choices": {
            "most_recent": "Most Recent",
            "relevance": "Relevance",
            "top": "Top"
          },
          "placeholder": "relevance"
        },
        {
          "key": "get_sentiment",
          "label": "Add Sentiment Analysis",
          "required": false,
          "type": "boolean",
          "helpText": "Set to true to add AI emotion analysis to each comment (returned in the `posts` array). Adds a `sentiment` object containing `emotions` (joy, trust, fear, surprise, sadness, disgust, anger and anticipation, each scored 0-100), `dominant_emotion`, `emotional_intensity` (0-10), and `polarity` (positive, negative or neutral). Any comment that cannot be scored returns `sentiment: null`."
        }
      ],
      "sample": {
        "id": "https://www.gamespot.com/articles/nothing-in-our-games-will-be-ai-generated-ever-says-warframe-director/1100-6539194/",
        "author": "Lawsoffire",
        "date": "2026-04-04T21:12:30Z",
        "domain": "reddit.com",
        "snippet": "In the context of a post-2023 world, I really don't feel that a program doing what its programmed to, but now the input and output is somewhat dynamic qualifies on anywhere near the same linguistic s…",
        "source": "Reddit (Comment)",
        "subreddit": "pcgaming",
        "title": "Lawsoffire on pcgaming",
        "type": "comment",
        "upvotes": 87,
        "post_upvotes": 2341,
        "post_comments": 312,
        "url": "https://www.gamespot.com/articles/nothing-in-our-games-will-be-ai-generated-ever-says-warframe-director/1100-6539194/"
      },
      "outputFields": [
        {
          "key": "id",
          "label": "ID",
          "primary": true
        },
        {
          "key": "author",
          "label": "Author"
        },
        {
          "key": "date",
          "label": "Date"
        },
        {
          "key": "domain",
          "label": "Domain"
        },
        {
          "key": "snippet",
          "label": "Snippet"
        },
        {
          "key": "source",
          "label": "Source"
        },
        {
          "key": "subreddit",
          "label": "Subreddit"
        },
        {
          "key": "title",
          "label": "Title"
        },
        {
          "key": "type",
          "label": "Type"
        },
        {
          "key": "upvotes",
          "label": "Upvotes",
          "type": "number"
        },
        {
          "key": "post_upvotes",
          "label": "Post Upvotes",
          "type": "number"
        },
        {
          "key": "post_comments",
          "label": "Post Comments",
          "type": "number"
        },
        {
          "key": "url",
          "label": "URL"
        }
      ]
    }
  },
  {
    "key": "reddit_users",
    "path": "/v1/reddit/users",
    "method": "GET",
    "platform": "Reddit",
    "noun": "User",
    "kind": "list",
    "listKey": "users",
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/reddit-users",
    "action": {
      "label": "Search Reddit Users",
      "description": "Searches for Reddit users by keyword. Returns username, user ID, bio, profile avatar, link karma, comment karma, total karma, verified-email status, premium status, moderator status, and account creation date. $0.003 per request after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "query",
        "label": "Search Query",
        "required": true,
        "type": "string",
        "helpText": "Search query (max 500 characters)",
        "placeholder": "programming"
      }
    ],
    "sample": {
      "count": 25,
      "users": [
        {
          "comment_karma": 3156,
          "created_at": "2015-08-17T17:08:41Z",
          "description": "",
          "has_verified_email": true,
          "icon_img": "https://styles.redditmedia.com/t5_d8pfe/styles/profileIcon_03ih1ceg0yue1.png?width=256&height=256&crop=256:256,smart&s=31b8c0af470109f1823913bd19667c22e9b2b945",
          "is_gold": false,
          "is_mod": false,
          "link_karma": 2209,
          "total_karma": 5365,
          "url": "https://reddit.com/user/programming_bassist",
          "user_id": "pmlju",
          "username": "programming_bassist"
        },
        {
          "comment_karma": 0,
          "created_at": null,
          "description": "",
          "has_verified_email": false,
          "icon_img": "",
          "is_gold": false,
          "is_mod": false,
          "link_karma": 0,
          "total_karma": 0,
          "url": "https://reddit.com/user/programming_student2",
          "user_id": "",
          "username": "programming_student2"
        },
        {
          "comment_karma": 63416,
          "created_at": "2024-07-18T17:38:13Z",
          "description": "Gods eyes are mirrors. I think I was put on this earth to help people understand that life is not the way that it seems. Locate the Opposites and find the Balance in between.",
          "has_verified_email": true,
          "icon_img": "https://i.redd.it/snoovatar/avatars/6820ff18-cbad-403a-945b-f21d4c59d388-headshot.png",
          "is_gold": false,
          "is_mod": false,
          "link_karma": 6721,
          "total_karma": 70137,
          "url": "https://reddit.com/user/sum1sum1sum1sum1",
          "user_id": "mdpr8sah",
          "username": "sum1sum1sum1sum1"
        }
      ]
    },
    "outputFields": [
      {
        "key": "count",
        "label": "Count",
        "type": "number"
      },
      {
        "key": "users[]comment_karma",
        "label": "Users: Comment Karma",
        "type": "number"
      },
      {
        "key": "users[]created_at",
        "label": "Users: Created At"
      },
      {
        "key": "users[]description",
        "label": "Users: Description"
      },
      {
        "key": "users[]has_verified_email",
        "label": "Users: Has Verified Email",
        "type": "boolean"
      },
      {
        "key": "users[]icon_img",
        "label": "Users: Icon Img"
      },
      {
        "key": "users[]is_gold",
        "label": "Users: Is Gold",
        "type": "boolean"
      },
      {
        "key": "users[]is_mod",
        "label": "Users: Is Mod",
        "type": "boolean"
      },
      {
        "key": "users[]link_karma",
        "label": "Users: Link Karma",
        "type": "number"
      },
      {
        "key": "users[]total_karma",
        "label": "Users: Total Karma",
        "type": "number"
      },
      {
        "key": "users[]url",
        "label": "Users: URL"
      },
      {
        "key": "users[]user_id",
        "label": "Users: User ID"
      },
      {
        "key": "users[]username",
        "label": "Users: Username"
      }
    ],
    "trigger": {
      "label": "New Reddit User Matching Search",
      "description": "Triggers when a new Reddit user matches your search. Each check runs Search Reddit Users ($0.003 per request after the free tier (50 requests/month)).",
      "inputFields": [
        {
          "key": "query",
          "label": "Search Query",
          "required": true,
          "type": "string",
          "helpText": "Search query (max 500 characters)",
          "placeholder": "programming"
        }
      ],
      "sample": {
        "id": "pmlju",
        "comment_karma": 3156,
        "created_at": "2015-08-17T17:08:41Z",
        "description": "",
        "has_verified_email": true,
        "icon_img": "https://styles.redditmedia.com/t5_d8pfe/styles/profileIcon_03ih1ceg0yue1.png?width=256&height=256&crop=256:256,smart&s=31b8c0af470109f1823913bd19667c22e9b2b945",
        "is_gold": false,
        "is_mod": false,
        "link_karma": 2209,
        "total_karma": 5365,
        "url": "https://reddit.com/user/programming_bassist",
        "user_id": "pmlju",
        "username": "programming_bassist"
      },
      "outputFields": [
        {
          "key": "id",
          "label": "ID",
          "primary": true
        },
        {
          "key": "comment_karma",
          "label": "Comment Karma",
          "type": "number"
        },
        {
          "key": "created_at",
          "label": "Created At"
        },
        {
          "key": "description",
          "label": "Description"
        },
        {
          "key": "has_verified_email",
          "label": "Has Verified Email",
          "type": "boolean"
        },
        {
          "key": "icon_img",
          "label": "Icon Img"
        },
        {
          "key": "is_gold",
          "label": "Is Gold",
          "type": "boolean"
        },
        {
          "key": "is_mod",
          "label": "Is Mod",
          "type": "boolean"
        },
        {
          "key": "link_karma",
          "label": "Link Karma",
          "type": "number"
        },
        {
          "key": "total_karma",
          "label": "Total Karma",
          "type": "number"
        },
        {
          "key": "url",
          "label": "URL"
        },
        {
          "key": "user_id",
          "label": "User ID"
        },
        {
          "key": "username",
          "label": "Username"
        }
      ]
    }
  }
];
