// Generated by scripts/generate.py from spec/openapi.json. Do not edit by hand;
// change the spec or the generator and run `npm run generate`.
module.exports = [
  {
    "key": "threads_posts",
    "path": "/v1/threads/posts",
    "method": "GET",
    "platform": "Threads",
    "noun": "Post",
    "kind": "list",
    "listKey": "posts",
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/threads-posts",
    "action": {
      "label": "Search Threads Posts",
      "description": "Searches for Threads posts by keyword. Returns post text, engagement metrics (likes, replies, reposts, quotes), author metadata, hashtags, mentions, and a direct link to each post. Set get_sentiment=true to add AI emotion analysis (+$0.001/request). $0.006 per request after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "query",
        "label": "Search Query",
        "required": true,
        "type": "string",
        "helpText": "Search keyword (max 500 characters)",
        "placeholder": "technology"
      },
      {
        "key": "get_sentiment",
        "label": "Add Sentiment Analysis",
        "required": false,
        "type": "boolean",
        "helpText": "Set to true to add AI emotion analysis to each result (+$0.001/request)"
      }
    ],
    "sample": {
      "count": 25,
      "posts": [
        {
          "title": "@mosseri on Threads",
          "url": "https://www.threads.com/@mosseri/post/DGx1a2bcdef",
          "date": "2026-06-20T14:12:05Z",
          "author": "mosseri",
          "source": "Threads",
          "domain": "threads.com",
          "snippet": "We're rolling out a few new things on Threads this week.",
          "likes": 8421,
          "replies": 342,
          "reposts": 517,
          "quotes": 88,
          "reshares": 40,
          "author_name": "Adam Mosseri",
          "author_verified": true,
          "is_reply": false,
          "media_type": "text",
          "image_url": "",
          "video_url": "",
          "hashtags": [],
          "mentions": [],
          "carousel_media": [],
          "link_preview": null,
          "quoted_post": null,
          "post_id": "3921002011550001234",
          "code": "DGx1a2bcdef"
        }
      ]
    },
    "outputFields": [
      {
        "key": "count",
        "label": "Count",
        "type": "number"
      },
      {
        "key": "posts[]title",
        "label": "Posts: Title"
      },
      {
        "key": "posts[]url",
        "label": "Posts: URL"
      },
      {
        "key": "posts[]date",
        "label": "Posts: Date"
      },
      {
        "key": "posts[]author",
        "label": "Posts: Author"
      },
      {
        "key": "posts[]source",
        "label": "Posts: Source"
      },
      {
        "key": "posts[]domain",
        "label": "Posts: Domain"
      },
      {
        "key": "posts[]snippet",
        "label": "Posts: Snippet"
      },
      {
        "key": "posts[]likes",
        "label": "Posts: Likes",
        "type": "number"
      },
      {
        "key": "posts[]replies",
        "label": "Posts: Replies",
        "type": "number"
      },
      {
        "key": "posts[]reposts",
        "label": "Posts: Reposts",
        "type": "number"
      },
      {
        "key": "posts[]quotes",
        "label": "Posts: Quotes",
        "type": "number"
      },
      {
        "key": "posts[]reshares",
        "label": "Posts: Reshares",
        "type": "number"
      },
      {
        "key": "posts[]author_name",
        "label": "Posts: Author Name"
      },
      {
        "key": "posts[]author_verified",
        "label": "Posts: Author Verified",
        "type": "boolean"
      },
      {
        "key": "posts[]is_reply",
        "label": "Posts: Is Reply",
        "type": "boolean"
      },
      {
        "key": "posts[]media_type",
        "label": "Posts: Media Type"
      },
      {
        "key": "posts[]image_url",
        "label": "Posts: Image URL"
      },
      {
        "key": "posts[]video_url",
        "label": "Posts: Video URL"
      },
      {
        "key": "posts[]hashtags",
        "label": "Posts: Hashtags",
        "list": true
      },
      {
        "key": "posts[]mentions",
        "label": "Posts: Mentions",
        "list": true
      },
      {
        "key": "posts[]carousel_media",
        "label": "Posts: Carousel Media",
        "list": true
      },
      {
        "key": "posts[]link_preview",
        "label": "Posts: Link Preview"
      },
      {
        "key": "posts[]quoted_post",
        "label": "Posts: Quoted Post"
      },
      {
        "key": "posts[]post_id",
        "label": "Posts: Post ID"
      },
      {
        "key": "posts[]code",
        "label": "Posts: Code"
      }
    ],
    "trigger": {
      "label": "New Threads Post Matching Search",
      "description": "Triggers when a new Threads post matches your search. Each check runs Search Threads Posts ($0.006 per request).",
      "inputFields": [
        {
          "key": "query",
          "label": "Search Query",
          "required": true,
          "type": "string",
          "helpText": "Search keyword (max 500 characters)",
          "placeholder": "technology"
        },
        {
          "key": "get_sentiment",
          "label": "Add Sentiment Analysis",
          "required": false,
          "type": "boolean",
          "helpText": "Set to true to add AI emotion analysis to each result (+$0.001/request)"
        }
      ],
      "sample": {
        "id": "3921002011550001234",
        "title": "@mosseri on Threads",
        "url": "https://www.threads.com/@mosseri/post/DGx1a2bcdef",
        "date": "2026-06-20T14:12:05Z",
        "author": "mosseri",
        "source": "Threads",
        "domain": "threads.com",
        "snippet": "We're rolling out a few new things on Threads this week.",
        "likes": 8421,
        "replies": 342,
        "reposts": 517,
        "quotes": 88,
        "reshares": 40,
        "author_name": "Adam Mosseri",
        "author_verified": true,
        "is_reply": false,
        "media_type": "text",
        "image_url": "",
        "video_url": "",
        "hashtags": [],
        "mentions": [],
        "carousel_media": [],
        "link_preview": null,
        "quoted_post": null,
        "post_id": "3921002011550001234",
        "code": "DGx1a2bcdef"
      },
      "outputFields": [
        {
          "key": "id",
          "label": "ID",
          "primary": true
        },
        {
          "key": "title",
          "label": "Title"
        },
        {
          "key": "url",
          "label": "URL"
        },
        {
          "key": "date",
          "label": "Date"
        },
        {
          "key": "author",
          "label": "Author"
        },
        {
          "key": "source",
          "label": "Source"
        },
        {
          "key": "domain",
          "label": "Domain"
        },
        {
          "key": "snippet",
          "label": "Snippet"
        },
        {
          "key": "likes",
          "label": "Likes",
          "type": "number"
        },
        {
          "key": "replies",
          "label": "Replies",
          "type": "number"
        },
        {
          "key": "reposts",
          "label": "Reposts",
          "type": "number"
        },
        {
          "key": "quotes",
          "label": "Quotes",
          "type": "number"
        },
        {
          "key": "reshares",
          "label": "Reshares",
          "type": "number"
        },
        {
          "key": "author_name",
          "label": "Author Name"
        },
        {
          "key": "author_verified",
          "label": "Author Verified",
          "type": "boolean"
        },
        {
          "key": "is_reply",
          "label": "Is Reply",
          "type": "boolean"
        },
        {
          "key": "media_type",
          "label": "Media Type"
        },
        {
          "key": "image_url",
          "label": "Image URL"
        },
        {
          "key": "video_url",
          "label": "Video URL"
        },
        {
          "key": "hashtags",
          "label": "Hashtags",
          "list": true
        },
        {
          "key": "mentions",
          "label": "Mentions",
          "list": true
        },
        {
          "key": "carousel_media",
          "label": "Carousel Media",
          "list": true
        },
        {
          "key": "link_preview",
          "label": "Link Preview"
        },
        {
          "key": "quoted_post",
          "label": "Quoted Post"
        },
        {
          "key": "post_id",
          "label": "Post ID"
        },
        {
          "key": "code",
          "label": "Code"
        }
      ]
    }
  },
  {
    "key": "threads_users",
    "path": "/v1/threads/users",
    "method": "GET",
    "platform": "Threads",
    "noun": "User",
    "kind": "list",
    "listKey": "users",
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/threads-users",
    "action": {
      "label": "Search Threads Users",
      "description": "Searches for Threads users by keyword. Returns username, full name, user ID, verification status, privacy status, profile picture URL, and a direct profile link. $0.006 per request after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "query",
        "label": "Search Query",
        "required": true,
        "type": "string",
        "helpText": "Search keyword (max 500 characters)",
        "placeholder": "technology"
      }
    ],
    "sample": {
      "count": 24,
      "users": [
        {
          "username": "natgeo",
          "full_name": "National Geographic",
          "user_id": "787132",
          "is_verified": true,
          "is_private": false,
          "profile_pic_url": "https://scontent.cdninstagram.com/v/t51.2885-19/natgeo.jpg",
          "url": "https://www.threads.com/@natgeo"
        }
      ]
    },
    "outputFields": [
      {
        "key": "count",
        "label": "Count",
        "type": "number"
      },
      {
        "key": "users[]username",
        "label": "Users: Username"
      },
      {
        "key": "users[]full_name",
        "label": "Users: Full Name"
      },
      {
        "key": "users[]user_id",
        "label": "Users: User ID"
      },
      {
        "key": "users[]is_verified",
        "label": "Users: Is Verified",
        "type": "boolean"
      },
      {
        "key": "users[]is_private",
        "label": "Users: Is Private",
        "type": "boolean"
      },
      {
        "key": "users[]profile_pic_url",
        "label": "Users: Profile Pic URL"
      },
      {
        "key": "users[]url",
        "label": "Users: URL"
      }
    ],
    "trigger": {
      "label": "New Threads User Matching Search",
      "description": "Triggers when a new Threads user matches your search. Each check runs Search Threads Users ($0.006 per request).",
      "inputFields": [
        {
          "key": "query",
          "label": "Search Query",
          "required": true,
          "type": "string",
          "helpText": "Search keyword (max 500 characters)",
          "placeholder": "technology"
        }
      ],
      "sample": {
        "id": "787132",
        "username": "natgeo",
        "full_name": "National Geographic",
        "user_id": "787132",
        "is_verified": true,
        "is_private": false,
        "profile_pic_url": "https://scontent.cdninstagram.com/v/t51.2885-19/natgeo.jpg",
        "url": "https://www.threads.com/@natgeo"
      },
      "outputFields": [
        {
          "key": "id",
          "label": "ID",
          "primary": true
        },
        {
          "key": "username",
          "label": "Username"
        },
        {
          "key": "full_name",
          "label": "Full Name"
        },
        {
          "key": "user_id",
          "label": "User ID"
        },
        {
          "key": "is_verified",
          "label": "Is Verified",
          "type": "boolean"
        },
        {
          "key": "is_private",
          "label": "Is Private",
          "type": "boolean"
        },
        {
          "key": "profile_pic_url",
          "label": "Profile Pic URL"
        },
        {
          "key": "url",
          "label": "URL"
        }
      ]
    }
  },
  {
    "key": "threads_user",
    "path": "/v1/threads/user",
    "method": "GET",
    "platform": "Threads",
    "noun": "User",
    "kind": "detail",
    "listKey": null,
    "unwrapKey": "user",
    "docs": "https://apidirect.io/docs/threads-user",
    "action": {
      "label": "Find Threads User",
      "description": "Looks up a single Threads user by username. Returns biography, follower count, verification status, privacy status, profile picture, bio links, and the topic tags shown on the profile. $0.006 per request after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "username",
        "label": "Username",
        "required": true,
        "type": "string",
        "helpText": "Threads username, with or without leading @ (max 100 characters)",
        "placeholder": "zuck"
      }
    ],
    "sample": {
      "username": "mosseri",
      "full_name": "Adam Mosseri",
      "user_id": "1099735954",
      "biography": "Head of Instagram and Threads.",
      "follower_count": 1875432,
      "is_verified": true,
      "is_private": false,
      "profile_pic_url": "https://scontent.cdninstagram.com/v/t51.2885-19/mosseri.jpg",
      "profile_pic_url_hd": "https://scontent.cdninstagram.com/v/t51.2885-19/mosseri_640.jpg",
      "bio_links": [
        {
          "url": "https://about.instagram.com/blog",
          "title": "Instagram Blog"
        }
      ],
      "profile_tags": [],
      "url": "https://www.threads.com/@mosseri"
    },
    "outputFields": [
      {
        "key": "username",
        "label": "Username"
      },
      {
        "key": "full_name",
        "label": "Full Name"
      },
      {
        "key": "user_id",
        "label": "User ID"
      },
      {
        "key": "biography",
        "label": "Biography"
      },
      {
        "key": "follower_count",
        "label": "Follower Count",
        "type": "number"
      },
      {
        "key": "is_verified",
        "label": "Is Verified",
        "type": "boolean"
      },
      {
        "key": "is_private",
        "label": "Is Private",
        "type": "boolean"
      },
      {
        "key": "profile_pic_url",
        "label": "Profile Pic URL"
      },
      {
        "key": "profile_pic_url_hd",
        "label": "Profile Pic URL Hd"
      },
      {
        "key": "bio_links[]url",
        "label": "Bio Links: URL"
      },
      {
        "key": "bio_links[]title",
        "label": "Bio Links: Title"
      },
      {
        "key": "profile_tags",
        "label": "Profile Tags",
        "list": true
      },
      {
        "key": "url",
        "label": "URL"
      }
    ],
    "trigger": null
  },
  {
    "key": "threads_user_posts",
    "path": "/v1/threads/user/posts",
    "method": "GET",
    "platform": "Threads",
    "noun": "Post",
    "kind": "list",
    "listKey": "posts",
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/threads-user-posts",
    "action": {
      "label": "Get Threads User Posts",
      "description": "Gets a single Threads user's recent posts (their feed) by username. Returns post text, engagement metrics (likes, replies, reposts, quotes), author metadata, hashtags, mentions, and media details. Set get_sentiment=true to add AI emotion analysis (+$0.001/request). $0.006 per request after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "username",
        "label": "Username",
        "required": true,
        "type": "string",
        "helpText": "Threads username, with or without leading @ (max 100 characters)",
        "placeholder": "mrbeast"
      },
      {
        "key": "get_sentiment",
        "label": "Add Sentiment Analysis",
        "required": false,
        "type": "boolean",
        "helpText": "Set to true to add AI emotion analysis to each result (+$0.001/request)"
      }
    ],
    "sample": {
      "count": 12,
      "posts": [
        {
          "title": "@natgeo on Threads",
          "url": "https://www.threads.com/@natgeo/post/DGw9k2aQ1rT",
          "date": "2026-06-19T17:40:11Z",
          "author": "natgeo",
          "source": "Threads",
          "domain": "threads.com",
          "snippet": "A curious fox pauses in the first snow of the season.",
          "likes": 2210,
          "replies": 54,
          "reposts": 133,
          "quotes": 7,
          "reshares": 12,
          "author_name": "National Geographic",
          "author_verified": true,
          "is_reply": false,
          "is_pinned": false,
          "media_type": "image",
          "image_url": "https://scontent.cdninstagram.com/v/t51.82787-15/fox.jpg",
          "video_url": "",
          "hashtags": [],
          "mentions": [],
          "carousel_media": [],
          "link_preview": null,
          "quoted_post": null,
          "post_id": "3919887766554430021",
          "code": "DGw9k2aQ1rT"
        }
      ]
    },
    "outputFields": [
      {
        "key": "count",
        "label": "Count",
        "type": "number"
      },
      {
        "key": "posts[]title",
        "label": "Posts: Title"
      },
      {
        "key": "posts[]url",
        "label": "Posts: URL"
      },
      {
        "key": "posts[]date",
        "label": "Posts: Date"
      },
      {
        "key": "posts[]author",
        "label": "Posts: Author"
      },
      {
        "key": "posts[]source",
        "label": "Posts: Source"
      },
      {
        "key": "posts[]domain",
        "label": "Posts: Domain"
      },
      {
        "key": "posts[]snippet",
        "label": "Posts: Snippet"
      },
      {
        "key": "posts[]likes",
        "label": "Posts: Likes",
        "type": "number"
      },
      {
        "key": "posts[]replies",
        "label": "Posts: Replies",
        "type": "number"
      },
      {
        "key": "posts[]reposts",
        "label": "Posts: Reposts",
        "type": "number"
      },
      {
        "key": "posts[]quotes",
        "label": "Posts: Quotes",
        "type": "number"
      },
      {
        "key": "posts[]reshares",
        "label": "Posts: Reshares",
        "type": "number"
      },
      {
        "key": "posts[]author_name",
        "label": "Posts: Author Name"
      },
      {
        "key": "posts[]author_verified",
        "label": "Posts: Author Verified",
        "type": "boolean"
      },
      {
        "key": "posts[]is_reply",
        "label": "Posts: Is Reply",
        "type": "boolean"
      },
      {
        "key": "posts[]is_pinned",
        "label": "Posts: Is Pinned",
        "type": "boolean"
      },
      {
        "key": "posts[]media_type",
        "label": "Posts: Media Type"
      },
      {
        "key": "posts[]image_url",
        "label": "Posts: Image URL"
      },
      {
        "key": "posts[]video_url",
        "label": "Posts: Video URL"
      },
      {
        "key": "posts[]hashtags",
        "label": "Posts: Hashtags",
        "list": true
      },
      {
        "key": "posts[]mentions",
        "label": "Posts: Mentions",
        "list": true
      },
      {
        "key": "posts[]carousel_media",
        "label": "Posts: Carousel Media",
        "list": true
      },
      {
        "key": "posts[]link_preview",
        "label": "Posts: Link Preview"
      },
      {
        "key": "posts[]quoted_post",
        "label": "Posts: Quoted Post"
      },
      {
        "key": "posts[]post_id",
        "label": "Posts: Post ID"
      },
      {
        "key": "posts[]code",
        "label": "Posts: Code"
      }
    ],
    "trigger": {
      "label": "New Threads Post by User",
      "description": "Triggers when a Threads user publishes a new post. Each check runs Get Threads User Posts ($0.006 per request).",
      "inputFields": [
        {
          "key": "username",
          "label": "Username",
          "required": true,
          "type": "string",
          "helpText": "Threads username, with or without leading @ (max 100 characters)",
          "placeholder": "mrbeast"
        },
        {
          "key": "get_sentiment",
          "label": "Add Sentiment Analysis",
          "required": false,
          "type": "boolean",
          "helpText": "Set to true to add AI emotion analysis to each result (+$0.001/request)"
        }
      ],
      "sample": {
        "id": "3919887766554430021",
        "title": "@natgeo on Threads",
        "url": "https://www.threads.com/@natgeo/post/DGw9k2aQ1rT",
        "date": "2026-06-19T17:40:11Z",
        "author": "natgeo",
        "source": "Threads",
        "domain": "threads.com",
        "snippet": "A curious fox pauses in the first snow of the season.",
        "likes": 2210,
        "replies": 54,
        "reposts": 133,
        "quotes": 7,
        "reshares": 12,
        "author_name": "National Geographic",
        "author_verified": true,
        "is_reply": false,
        "is_pinned": false,
        "media_type": "image",
        "image_url": "https://scontent.cdninstagram.com/v/t51.82787-15/fox.jpg",
        "video_url": "",
        "hashtags": [],
        "mentions": [],
        "carousel_media": [],
        "link_preview": null,
        "quoted_post": null,
        "post_id": "3919887766554430021",
        "code": "DGw9k2aQ1rT"
      },
      "outputFields": [
        {
          "key": "id",
          "label": "ID",
          "primary": true
        },
        {
          "key": "title",
          "label": "Title"
        },
        {
          "key": "url",
          "label": "URL"
        },
        {
          "key": "date",
          "label": "Date"
        },
        {
          "key": "author",
          "label": "Author"
        },
        {
          "key": "source",
          "label": "Source"
        },
        {
          "key": "domain",
          "label": "Domain"
        },
        {
          "key": "snippet",
          "label": "Snippet"
        },
        {
          "key": "likes",
          "label": "Likes",
          "type": "number"
        },
        {
          "key": "replies",
          "label": "Replies",
          "type": "number"
        },
        {
          "key": "reposts",
          "label": "Reposts",
          "type": "number"
        },
        {
          "key": "quotes",
          "label": "Quotes",
          "type": "number"
        },
        {
          "key": "reshares",
          "label": "Reshares",
          "type": "number"
        },
        {
          "key": "author_name",
          "label": "Author Name"
        },
        {
          "key": "author_verified",
          "label": "Author Verified",
          "type": "boolean"
        },
        {
          "key": "is_reply",
          "label": "Is Reply",
          "type": "boolean"
        },
        {
          "key": "is_pinned",
          "label": "Is Pinned",
          "type": "boolean"
        },
        {
          "key": "media_type",
          "label": "Media Type"
        },
        {
          "key": "image_url",
          "label": "Image URL"
        },
        {
          "key": "video_url",
          "label": "Video URL"
        },
        {
          "key": "hashtags",
          "label": "Hashtags",
          "list": true
        },
        {
          "key": "mentions",
          "label": "Mentions",
          "list": true
        },
        {
          "key": "carousel_media",
          "label": "Carousel Media",
          "list": true
        },
        {
          "key": "link_preview",
          "label": "Link Preview"
        },
        {
          "key": "quoted_post",
          "label": "Quoted Post"
        },
        {
          "key": "post_id",
          "label": "Post ID"
        },
        {
          "key": "code",
          "label": "Code"
        }
      ]
    }
  }
];
