// Generated by scripts/generate.py from spec/openapi.json. Do not edit by hand;
// change the spec or the generator and run `npm run generate`.
module.exports = [
  {
    "key": "tiktok_videos",
    "path": "/v1/tiktok/videos",
    "method": "GET",
    "platform": "TikTok",
    "noun": "Video",
    "kind": "list",
    "listKey": "videos",
    "idFields": [
      "url"
    ],
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/tiktok-videos",
    "action": {
      "label": "Search TikTok Videos",
      "description": "Searches for TikTok videos by keyword. Returns video caption, a link to the video on TikTok, publish date, engagement metrics (plays, likes, comments, shares, downloads), duration, cover image, music track, and creator metadata (username, display name, avatar). Supports region filtering, publish-time filtering, and sorting by relevance, recency, or likes. Supports fetching multiple pages in a single API call (billed per page). Set get_sentiment=true to add AI emotion analysis to each video. $0.006 per page after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "query",
        "label": "Search Query",
        "required": true,
        "type": "string",
        "helpText": "Search query (max 500 characters)",
        "placeholder": "cooking"
      },
      {
        "key": "pages",
        "label": "Pages to Fetch",
        "required": false,
        "type": "integer",
        "default": "1",
        "helpText": "Number of pages to fetch and merge (1-10). Each page returns up to 30 videos. Billed per page (1-10).",
        "placeholder": "2"
      },
      {
        "key": "region",
        "label": "Region",
        "required": false,
        "type": "string",
        "helpText": "2-letter region code to filter by (e.g., us, gb, jp, de, fr) (up to 2 characters).",
        "placeholder": "us"
      },
      {
        "key": "publish_time",
        "label": "Published Within (Days)",
        "required": false,
        "type": "integer",
        "default": "0",
        "helpText": "Filter by publish time in days: 0 = all time, 1 = last day, 7 = last week, 30 = last month, 90 = last 3 months, 180 = last 6 months. Any other number returns 400; a non-numeric value falls back to 0.",
        "choices": {
          "0": "Any time",
          "1": "Last day",
          "7": "Last week",
          "30": "Last month",
          "90": "Last 3 months",
          "180": "Last 6 months"
        }
      },
      {
        "key": "sort_by",
        "label": "Sort By",
        "required": false,
        "type": "string",
        "default": "relevance",
        "helpText": "Sort order for results. Any unrecognised value falls back to relevance.",
        "choices": {
          "relevance": "Relevance",
          "most_recent": "Most Recent",
          "most_liked": "Most Liked"
        },
        "placeholder": "relevance"
      },
      {
        "key": "get_sentiment",
        "label": "Add Sentiment Analysis",
        "required": false,
        "type": "boolean",
        "helpText": "Set to true to add AI emotion analysis to each video. Adds a `sentiment` object containing `emotions` (joy, trust, fear, surprise, sadness, disgust, anger and anticipation, each scored 0-100), `dominant_emotion`, `emotional_intensity` (0-10), and `polarity` (positive, negative or neutral). Any video that cannot be scored returns `sentiment: null`."
      }
    ],
    "sample": {
      "count": 28,
      "pages": 1,
      "videos": [
        {
          "author": "meatlicious_",
          "author_avatar": "https://p16-common-sign.tiktokcdn-eu.com/tos-maliva-avt-0068/010a3f86b6a359c85257cd91a8b6c170~tplv-tiktokx-cropcenter-q:300:300:q70.jpeg?dr=9605&idc=no1a&ps=87d6e48a&refresh_token=f51134e7&s=SEARCH&s…",
          "author_name": "Meatlicious",
          "comments": 1209,
          "cover": "https://p16-common-sign.tiktokcdn-eu.com/tos-useast5-p-0068-tx/owf2ARfGkTxlIAEYTnNFPIADEbAImQjafgkAAH~tplv-tiktokx-origin.image?biz_tag=musically_video.video_cover&dr=1347&idc=no1a&ps=933b5bde&refres…",
          "date": "2026-04-01T14:13:11Z",
          "domain": "tiktok.com",
          "downloads": 1883,
          "duration": 40,
          "is_ad": false,
          "likes": 228556,
          "music_author": "Meatlicious",
          "music_title": "original sound - meatlicious_",
          "play_count": 2868457,
          "shares": 5514,
          "snippet": "This was hard I hope you enjoy this amazing Buldak Ramen fried chicken! A while back I left my job to try doing content full time, and I really thought it was going to work out. I spent a ton of time…",
          "source": "TikTok",
          "title": "This was hard I hope you enjoy this amazing Buldak Ramen fried chicken! A while back I left my job to try doing content full time, and I really thought it was going to work out. I spent a ton of time…",
          "url": "https://www.tiktok.com/@meatlicious_/video/7623793631043800334"
        },
        {
          "author": "on_todays_bake",
          "author_avatar": "https://p16-common-sign.tiktokcdn-eu.com/tos-no1a-avt-0068c001-no/9002654119dc69d555eb419dae433438~tplv-tiktokx-cropcenter-q:300:300:q70.jpeg?dr=9605&idc=no1a&ps=87d6e48a&refresh_token=17b545d7&s=SEA…",
          "author_name": "Ontodaysbake",
          "comments": 1199,
          "cover": "https://p16-common-sign.tiktokcdn-eu.com/tos-no1a-p-0037-no/o0gvvmqRnG6hfAGJfXgArsgWmrYOf7cev4IjoQ~tplv-tiktokx-origin.image?biz_tag=musically_video.video_cover&dr=1347&idc=no1a&ps=933b5bde&refresh_t…",
          "date": "2026-03-19T12:27:12Z",
          "domain": "tiktok.com",
          "downloads": 1441,
          "duration": 61,
          "is_ad": false,
          "likes": 731247,
          "music_author": "The Black Eyed Peas",
          "music_title": "Boom Boom Pow",
          "play_count": 10090197,
          "shares": 90816,
          "snippet": "Hassle back potatoes with creamy Cajun chicken and airfried brocollini . Easy, healthy comfort meal  Potato recipe 6 medium potatoes 3 tbsp butter (melted) 2 tbsp olive oil 4–5 cloves garlic (minced)…",
          "source": "TikTok",
          "title": "Hassle back potatoes with creamy Cajun chicken and airfried brocollini . Easy, healthy comfort meal  Potato recipe 6 medium potatoes 3 tbsp butter (melted) 2 tbsp olive oil 4–5 cloves garlic (minced)…",
          "url": "https://www.tiktok.com/@on_todays_bake/video/7618942237535194390"
        },
        {
          "author": "angeliiicahernandez",
          "author_avatar": "https://p16-common-sign.tiktokcdn-eu.com/tos-maliva-avt-0068/1d8018ad790b189ab64bca7e52c47fa4~tplv-tiktokx-cropcenter-q:300:300:q70.jpeg?dr=9605&idc=no1a&ps=87d6e48a&refresh_token=bd137c5b&s=SEARCH&s…",
          "author_name": "Angelica",
          "comments": 282,
          "cover": "https://p16-common-sign.tiktokcdn-eu.com/tos-useast5-p-0068-tx/oAfRIELGs3daGy3TNmBMQ1SZgCFfDpAbyxDSRE~tplv-tiktokx-origin.image?biz_tag=musically_video.video_cover&dr=1347&idc=no1a&ps=933b5bde&refres…",
          "date": "2026-03-29T23:21:23Z",
          "domain": "tiktok.com",
          "downloads": 36,
          "duration": 12,
          "is_ad": false,
          "likes": 19816,
          "music_author": "Gabriel🧃🪄",
          "music_title": "original sound - juan.gabriel.vallejo18",
          "play_count": 293923,
          "shares": 519,
          "snippet": "I’ve been influenced @RabeyaKhatun — I’m usually so stressed coming home from running my own restaurant that cooking for 1 person feels overwhelming… this has been changing my life.  Barely any prep,…",
          "source": "TikTok",
          "title": "I’ve been influenced @RabeyaKhatun — I’m usually so stressed coming home from running my own restaurant that cooking for 1 person feels overwhelming… this has been changing my life.  Barely any prep,…",
          "url": "https://www.tiktok.com/@angeliiicahernandez/video/7622821573313006861"
        }
      ]
    },
    "outputFields": [
      {
        "key": "count",
        "label": "Count",
        "type": "number"
      },
      {
        "key": "pages",
        "label": "Pages",
        "type": "number"
      },
      {
        "key": "videos[]author",
        "label": "Videos: Author"
      },
      {
        "key": "videos[]author_avatar",
        "label": "Videos: Author Avatar"
      },
      {
        "key": "videos[]author_name",
        "label": "Videos: Author Name"
      },
      {
        "key": "videos[]comments",
        "label": "Videos: Comments",
        "type": "number"
      },
      {
        "key": "videos[]cover",
        "label": "Videos: Cover"
      },
      {
        "key": "videos[]date",
        "label": "Videos: Date"
      },
      {
        "key": "videos[]domain",
        "label": "Videos: Domain"
      },
      {
        "key": "videos[]downloads",
        "label": "Videos: Downloads",
        "type": "number"
      },
      {
        "key": "videos[]duration",
        "label": "Videos: Duration",
        "type": "number"
      },
      {
        "key": "videos[]is_ad",
        "label": "Videos: Is Ad",
        "type": "boolean"
      },
      {
        "key": "videos[]likes",
        "label": "Videos: Likes",
        "type": "number"
      },
      {
        "key": "videos[]music_author",
        "label": "Videos: Music Author"
      },
      {
        "key": "videos[]music_title",
        "label": "Videos: Music Title"
      },
      {
        "key": "videos[]play_count",
        "label": "Videos: Play Count",
        "type": "number"
      },
      {
        "key": "videos[]shares",
        "label": "Videos: Shares",
        "type": "number"
      },
      {
        "key": "videos[]snippet",
        "label": "Videos: Snippet"
      },
      {
        "key": "videos[]source",
        "label": "Videos: Source"
      },
      {
        "key": "videos[]title",
        "label": "Videos: Title"
      },
      {
        "key": "videos[]url",
        "label": "Videos: URL"
      }
    ],
    "trigger": {
      "label": "New TikTok Video Matching Search",
      "description": "Triggers when a new TikTok video matches your search. Each check runs Search TikTok Videos ($0.006 per page).",
      "inputFields": [
        {
          "key": "query",
          "label": "Search Query",
          "required": true,
          "type": "string",
          "helpText": "Search query (max 500 characters)",
          "placeholder": "cooking"
        },
        {
          "key": "pages",
          "label": "Pages to Fetch",
          "required": false,
          "type": "integer",
          "default": "1",
          "helpText": "Number of pages to fetch and merge (1-10). Each page returns up to 30 videos. Billed per page (1-10). Every check of this trigger fetches this many pages, each billed as one request.",
          "placeholder": "2"
        },
        {
          "key": "region",
          "label": "Region",
          "required": false,
          "type": "string",
          "helpText": "2-letter region code to filter by (e.g., us, gb, jp, de, fr) (up to 2 characters).",
          "placeholder": "us"
        },
        {
          "key": "publish_time",
          "label": "Published Within (Days)",
          "required": false,
          "type": "integer",
          "default": "0",
          "helpText": "Filter by publish time in days: 0 = all time, 1 = last day, 7 = last week, 30 = last month, 90 = last 3 months, 180 = last 6 months. Any other number returns 400; a non-numeric value falls back to 0.",
          "choices": {
            "0": "Any time",
            "1": "Last day",
            "7": "Last week",
            "30": "Last month",
            "90": "Last 3 months",
            "180": "Last 6 months"
          }
        },
        {
          "key": "sort_by",
          "label": "Sort By",
          "required": false,
          "type": "string",
          "default": "most_recent",
          "helpText": "Sort order for results. Any unrecognised value falls back to relevance.",
          "choices": {
            "relevance": "Relevance",
            "most_recent": "Most Recent",
            "most_liked": "Most Liked"
          },
          "placeholder": "relevance"
        },
        {
          "key": "get_sentiment",
          "label": "Add Sentiment Analysis",
          "required": false,
          "type": "boolean",
          "helpText": "Set to true to add AI emotion analysis to each video. Adds a `sentiment` object containing `emotions` (joy, trust, fear, surprise, sadness, disgust, anger and anticipation, each scored 0-100), `dominant_emotion`, `emotional_intensity` (0-10), and `polarity` (positive, negative or neutral). Any video that cannot be scored returns `sentiment: null`."
        }
      ],
      "sample": {
        "id": "https://www.tiktok.com/@meatlicious_/video/7623793631043800334",
        "author": "meatlicious_",
        "author_avatar": "https://p16-common-sign.tiktokcdn-eu.com/tos-maliva-avt-0068/010a3f86b6a359c85257cd91a8b6c170~tplv-tiktokx-cropcenter-q:300:300:q70.jpeg?dr=9605&idc=no1a&ps=87d6e48a&refresh_token=f51134e7&s=SEARCH&s…",
        "author_name": "Meatlicious",
        "comments": 1209,
        "cover": "https://p16-common-sign.tiktokcdn-eu.com/tos-useast5-p-0068-tx/owf2ARfGkTxlIAEYTnNFPIADEbAImQjafgkAAH~tplv-tiktokx-origin.image?biz_tag=musically_video.video_cover&dr=1347&idc=no1a&ps=933b5bde&refres…",
        "date": "2026-04-01T14:13:11Z",
        "domain": "tiktok.com",
        "downloads": 1883,
        "duration": 40,
        "is_ad": false,
        "likes": 228556,
        "music_author": "Meatlicious",
        "music_title": "original sound - meatlicious_",
        "play_count": 2868457,
        "shares": 5514,
        "snippet": "This was hard I hope you enjoy this amazing Buldak Ramen fried chicken! A while back I left my job to try doing content full time, and I really thought it was going to work out. I spent a ton of time…",
        "source": "TikTok",
        "title": "This was hard I hope you enjoy this amazing Buldak Ramen fried chicken! A while back I left my job to try doing content full time, and I really thought it was going to work out. I spent a ton of time…",
        "url": "https://www.tiktok.com/@meatlicious_/video/7623793631043800334"
      },
      "outputFields": [
        {
          "key": "id",
          "label": "ID",
          "primary": true
        },
        {
          "key": "author",
          "label": "Author"
        },
        {
          "key": "author_avatar",
          "label": "Author Avatar"
        },
        {
          "key": "author_name",
          "label": "Author Name"
        },
        {
          "key": "comments",
          "label": "Comments",
          "type": "number"
        },
        {
          "key": "cover",
          "label": "Cover"
        },
        {
          "key": "date",
          "label": "Date"
        },
        {
          "key": "domain",
          "label": "Domain"
        },
        {
          "key": "downloads",
          "label": "Downloads",
          "type": "number"
        },
        {
          "key": "duration",
          "label": "Duration",
          "type": "number"
        },
        {
          "key": "is_ad",
          "label": "Is Ad",
          "type": "boolean"
        },
        {
          "key": "likes",
          "label": "Likes",
          "type": "number"
        },
        {
          "key": "music_author",
          "label": "Music Author"
        },
        {
          "key": "music_title",
          "label": "Music Title"
        },
        {
          "key": "play_count",
          "label": "Play Count",
          "type": "number"
        },
        {
          "key": "shares",
          "label": "Shares",
          "type": "number"
        },
        {
          "key": "snippet",
          "label": "Snippet"
        },
        {
          "key": "source",
          "label": "Source"
        },
        {
          "key": "title",
          "label": "Title"
        },
        {
          "key": "url",
          "label": "URL"
        }
      ]
    }
  },
  {
    "key": "tiktok_users",
    "path": "/v1/tiktok/users",
    "method": "GET",
    "platform": "TikTok",
    "noun": "User",
    "kind": "list",
    "listKey": "users",
    "idFields": [
      "user_id",
      "username",
      "url"
    ],
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/tiktok-users",
    "action": {
      "label": "Search TikTok Users",
      "description": "Searches for TikTok users by keyword. Returns username, numeric user ID, display name, bio, follower count, following count, total likes received, video count, verification status, private-account flag, avatar URL, and a link to the profile. Supports fetching multiple pages in a single API call (billed per page). $0.006 per page after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "query",
        "label": "Search Query",
        "required": true,
        "type": "string",
        "helpText": "Search query (max 500 characters)",
        "placeholder": "cooking"
      },
      {
        "key": "pages",
        "label": "Pages to Fetch",
        "required": false,
        "type": "integer",
        "default": "1",
        "helpText": "Number of pages to fetch and merge (1-10). Each page returns up to 30 users. Billed per page (1-10).",
        "placeholder": "1"
      }
    ],
    "sample": {
      "count": 30,
      "pages": 1,
      "users": [
        {
          "avatar": "https://p19-common-sign.tiktokcdn-us.com/tos-maliva-avt-0068/86b185f619e7db818b1724e6ce6c858d~tplv-tiktokx-cropcenter-q:100:100:q70.webp?biz_tag=musically_user.user_cover&dr=8835&idc=useast5&ps=87d6e…",
          "bio": "✌️im staying unknown till I hit 10.k ✌️",
          "followers": 137,
          "following": 1,
          "is_private": false,
          "likes": 7,
          "nickname": "🍑dance🍑",
          "url": "https://www.tiktok.com/@dancing.in.my.oodie_0",
          "user_id": "7042766232437277701",
          "username": "dancing.in.my.oodie_0",
          "verified": false,
          "video_count": 1
        },
        {
          "avatar": "https://p16-common-sign.tiktokcdn-us.com/tos-maliva-avt-0068/0a19e0f79882165fb48a0fc44c5aee0d~tplv-tiktokx-cropcenter-q:100:100:q70.webp?biz_tag=musically_user.user_cover&dr=8835&idc=useast5&ps=87d6e…",
          "bio": "welcoom to my tik tok acount",
          "followers": 5096,
          "following": 4362,
          "is_private": false,
          "likes": 4742,
          "nickname": "dance",
          "url": "https://www.tiktok.com/@dancekabyle5",
          "user_id": "6970594515879330822",
          "username": "dancekabyle5",
          "verified": false,
          "video_count": 18
        },
        {
          "avatar": "https://p19-common-sign.tiktokcdn-us.com/musically-maliva-obj/1594805258216454~tplv-tiktokx-cropcenter-q:100:100:q70.webp?biz_tag=musically_user.user_cover&dr=8835&idc=useast5&ps=87d6e48a&refresh_tok…",
          "bio": "No bio yet",
          "followers": 482,
          "following": 5,
          "is_private": false,
          "likes": 149,
          "nickname": "user71837325066",
          "url": "https://www.tiktok.com/@danyancatsq_20k",
          "user_id": "7011581515725784065",
          "username": "danyancatsq_20k",
          "verified": false,
          "video_count": 2
        }
      ]
    },
    "outputFields": [
      {
        "key": "count",
        "label": "Count",
        "type": "number"
      },
      {
        "key": "pages",
        "label": "Pages",
        "type": "number"
      },
      {
        "key": "users[]avatar",
        "label": "Users: Avatar"
      },
      {
        "key": "users[]bio",
        "label": "Users: Bio"
      },
      {
        "key": "users[]followers",
        "label": "Users: Followers",
        "type": "number"
      },
      {
        "key": "users[]following",
        "label": "Users: Following",
        "type": "number"
      },
      {
        "key": "users[]is_private",
        "label": "Users: Is Private",
        "type": "boolean"
      },
      {
        "key": "users[]likes",
        "label": "Users: Likes",
        "type": "number"
      },
      {
        "key": "users[]nickname",
        "label": "Users: Nickname"
      },
      {
        "key": "users[]url",
        "label": "Users: URL"
      },
      {
        "key": "users[]user_id",
        "label": "Users: User ID"
      },
      {
        "key": "users[]username",
        "label": "Users: Username"
      },
      {
        "key": "users[]verified",
        "label": "Users: Verified",
        "type": "boolean"
      },
      {
        "key": "users[]video_count",
        "label": "Users: Video Count",
        "type": "number"
      }
    ],
    "trigger": {
      "label": "New TikTok User Matching Search",
      "description": "Triggers when a new TikTok user matches your search. Each check runs Search TikTok Users ($0.006 per page).",
      "inputFields": [
        {
          "key": "query",
          "label": "Search Query",
          "required": true,
          "type": "string",
          "helpText": "Search query (max 500 characters)",
          "placeholder": "cooking"
        },
        {
          "key": "pages",
          "label": "Pages to Fetch",
          "required": false,
          "type": "integer",
          "default": "1",
          "helpText": "Number of pages to fetch and merge (1-10). Each page returns up to 30 users. Billed per page (1-10). Every check of this trigger fetches this many pages, each billed as one request.",
          "placeholder": "1"
        }
      ],
      "sample": {
        "id": "7042766232437277701",
        "avatar": "https://p19-common-sign.tiktokcdn-us.com/tos-maliva-avt-0068/86b185f619e7db818b1724e6ce6c858d~tplv-tiktokx-cropcenter-q:100:100:q70.webp?biz_tag=musically_user.user_cover&dr=8835&idc=useast5&ps=87d6e…",
        "bio": "✌️im staying unknown till I hit 10.k ✌️",
        "followers": 137,
        "following": 1,
        "is_private": false,
        "likes": 7,
        "nickname": "🍑dance🍑",
        "url": "https://www.tiktok.com/@dancing.in.my.oodie_0",
        "user_id": "7042766232437277701",
        "username": "dancing.in.my.oodie_0",
        "verified": false,
        "video_count": 1
      },
      "outputFields": [
        {
          "key": "id",
          "label": "ID",
          "primary": true
        },
        {
          "key": "avatar",
          "label": "Avatar"
        },
        {
          "key": "bio",
          "label": "Bio"
        },
        {
          "key": "followers",
          "label": "Followers",
          "type": "number"
        },
        {
          "key": "following",
          "label": "Following",
          "type": "number"
        },
        {
          "key": "is_private",
          "label": "Is Private",
          "type": "boolean"
        },
        {
          "key": "likes",
          "label": "Likes",
          "type": "number"
        },
        {
          "key": "nickname",
          "label": "Nickname"
        },
        {
          "key": "url",
          "label": "URL"
        },
        {
          "key": "user_id",
          "label": "User ID"
        },
        {
          "key": "username",
          "label": "Username"
        },
        {
          "key": "verified",
          "label": "Verified",
          "type": "boolean"
        },
        {
          "key": "video_count",
          "label": "Video Count",
          "type": "number"
        }
      ]
    }
  },
  {
    "key": "tiktok_user",
    "path": "/v1/tiktok/user",
    "method": "GET",
    "platform": "TikTok",
    "noun": "User",
    "kind": "detail",
    "listKey": null,
    "idFields": null,
    "unwrapKey": "user",
    "docs": "https://apidirect.io/docs/tiktok-user",
    "action": {
      "label": "Find TikTok User",
      "description": "Looks up a single TikTok user by username, numeric user ID, or profile URL. Returns bio, bio link, follower / following counts, total likes, video count, verification status, join date, and linked Instagram, X/Twitter, and YouTube accounts. Provide exactly one of username, user_id, or url. $0.006 per request after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "username",
        "label": "Username",
        "required": false,
        "type": "string",
        "helpText": "TikTok username, with or without leading @ (max 100 characters). Provide exactly one of username, user_id, or url.",
        "placeholder": "gordonramsayofficial"
      },
      {
        "key": "user_id",
        "label": "User ID",
        "required": false,
        "type": "string",
        "helpText": "Numeric TikTok user ID, as returned by Search Users. Digits only, max 20 characters, and not all zeros. Provide exactly one of username, user_id, or url."
      },
      {
        "key": "url",
        "label": "URL",
        "required": false,
        "type": "string",
        "helpText": "TikTok profile URL, e.g. `https://www.tiktok.com/@tiktok` (max 500 characters). Must include the tiktok.com/@username segment. Provide exactly one of username, user_id, or url.",
        "placeholder": "https://www.tiktok.com/@gordonramsayofficial"
      }
    ],
    "sample": {
      "username": "gordonramsayofficial",
      "nickname": "Gordon Ramsay",
      "user_id": "6747935906352907269",
      "sec_uid": "MS4wLjABAAAAv3zolJLlWp-WbKXqSZwVSflDdwcbjPADRG-dhb68k30dQjkFpkRs4HiMvWeeIyVv",
      "bio": "I cook sometimes too.....",
      "bio_link": "GordonRamsay.com/",
      "verified": true,
      "is_private": false,
      "followers": 40817126,
      "following": 573,
      "likes": 728577233,
      "video_count": 839,
      "videos_liked": 0,
      "avatar": "https://p19-common-sign.tiktokcdn-us.com/.../photo.webp",
      "avatar_hd": "https://p19-common-sign.tiktokcdn-us.com/.../photo_1080.webp",
      "date_joined": "2019-10-18T17:42:11Z",
      "date_joined_timestamp": 1571420531,
      "instagram_username": "",
      "twitter_id": "",
      "youtube_channel_id": "",
      "youtube_channel_title": "",
      "url": "https://www.tiktok.com/@gordonramsayofficial"
    },
    "outputFields": [
      {
        "key": "username",
        "label": "Username"
      },
      {
        "key": "nickname",
        "label": "Nickname"
      },
      {
        "key": "user_id",
        "label": "User ID"
      },
      {
        "key": "sec_uid",
        "label": "Sec Uid"
      },
      {
        "key": "bio",
        "label": "Bio"
      },
      {
        "key": "bio_link",
        "label": "Bio Link"
      },
      {
        "key": "verified",
        "label": "Verified",
        "type": "boolean"
      },
      {
        "key": "is_private",
        "label": "Is Private",
        "type": "boolean"
      },
      {
        "key": "followers",
        "label": "Followers",
        "type": "number"
      },
      {
        "key": "following",
        "label": "Following",
        "type": "number"
      },
      {
        "key": "likes",
        "label": "Likes",
        "type": "number"
      },
      {
        "key": "video_count",
        "label": "Video Count",
        "type": "number"
      },
      {
        "key": "videos_liked",
        "label": "Videos Liked",
        "type": "number"
      },
      {
        "key": "avatar",
        "label": "Avatar"
      },
      {
        "key": "avatar_hd",
        "label": "Avatar Hd"
      },
      {
        "key": "date_joined",
        "label": "Date Joined"
      },
      {
        "key": "date_joined_timestamp",
        "label": "Date Joined Timestamp",
        "type": "number"
      },
      {
        "key": "instagram_username",
        "label": "Instagram Username"
      },
      {
        "key": "twitter_id",
        "label": "Twitter ID"
      },
      {
        "key": "youtube_channel_id",
        "label": "Youtube Channel ID"
      },
      {
        "key": "youtube_channel_title",
        "label": "Youtube Channel Title"
      },
      {
        "key": "url",
        "label": "URL"
      }
    ],
    "trigger": null
  },
  {
    "key": "tiktok_video",
    "path": "/v1/tiktok/video",
    "method": "GET",
    "platform": "TikTok",
    "noun": "Video",
    "kind": "detail",
    "listKey": null,
    "idFields": null,
    "unwrapKey": "video",
    "docs": "https://apidirect.io/docs/tiktok-video",
    "action": {
      "label": "Find TikTok Video",
      "description": "Looks up a single TikTok video by URL or numeric video ID. Returns the caption, play / like / comment / share / save counts, watermark-free playback and download URLs, cover images, music track info, and author details. Provide exactly one of url or video_id. $0.006 per request after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "url",
        "label": "URL",
        "required": false,
        "type": "string",
        "helpText": "TikTok video URL, e.g. `https://www.tiktok.com/@tiktok/video/7516594811734854943` (max 500 characters). Must contain tiktok.com/. Provide exactly one of url or video_id.",
        "placeholder": "https://www.tiktok.com/@tiktok/video/7516594811734854943"
      },
      {
        "key": "video_id",
        "label": "Video ID",
        "required": false,
        "type": "string",
        "helpText": "Numeric TikTok video ID: the number at the end of a video URL. Digits only, max 25 characters, and not all zeros. Provide exactly one of url or video_id.",
        "placeholder": "7516594811734854943"
      }
    ],
    "sample": {
      "video_id": "7516594811734854943",
      "url": "https://www.tiktok.com/@tiktok/video/7516594811734854943",
      "title": "🌈🐬🦄 life after @Zara Larsson Symphony vocals 🌈🐬🦄",
      "region": "US",
      "date": "2025-06-16T17:07:10Z",
      "date_timestamp": 1750093630,
      "duration": 66,
      "play_count": 18912653,
      "likes": 879920,
      "comments": 4382,
      "shares": 17420,
      "downloads": 1003,
      "saves": 38685,
      "is_ad": true,
      "cover": "https://p16-common-sign.tiktokcdn-us.com/.../cover.jpeg",
      "dynamic_cover": "https://p16-common-sign.tiktokcdn-us.com/.../dynamic.image",
      "origin_cover": "https://p16-common-sign.tiktokcdn-us.com/.../origin.webp",
      "video_url": "https://v16m.tiktokcdn-us.com/.../video.mp4",
      "video_url_hd": "https://v16.tokcdn.com/.../7516594811734854943_original.mp4",
      "video_url_watermarked": "https://v16m.tiktokcdn-us.com/.../video_wm.mp4",
      "size": 7786703,
      "size_hd": 38711004,
      "size_watermarked": 7988034,
      "author": "tiktok",
      "author_name": "TikTok",
      "author_id": "107955",
      "author_avatar": "https://p19-common-sign.tiktokcdn-us.com/.../avatar.jpeg",
      "author_url": "https://www.tiktok.com/@tiktok",
      "music_id": "7516599978421209887",
      "music_title": "original sound - tiktok",
      "music_author": "TikTok",
      "music_url": "https://v16-ies-music.tiktokcdn-us.com/.../audio.mp3",
      "music_cover": "https://p16-common-sign.tiktokcdn-us.com/.../music.jpeg",
      "music_album": "",
      "music_original": true,
      "music_duration": 66,
      "mentioned_user_ids": [
        "205879097384816641"
      ]
    },
    "outputFields": [
      {
        "key": "video_id",
        "label": "Video ID"
      },
      {
        "key": "url",
        "label": "URL"
      },
      {
        "key": "title",
        "label": "Title"
      },
      {
        "key": "region",
        "label": "Region"
      },
      {
        "key": "date",
        "label": "Date"
      },
      {
        "key": "date_timestamp",
        "label": "Date Timestamp",
        "type": "number"
      },
      {
        "key": "duration",
        "label": "Duration",
        "type": "number"
      },
      {
        "key": "play_count",
        "label": "Play Count",
        "type": "number"
      },
      {
        "key": "likes",
        "label": "Likes",
        "type": "number"
      },
      {
        "key": "comments",
        "label": "Comments",
        "type": "number"
      },
      {
        "key": "shares",
        "label": "Shares",
        "type": "number"
      },
      {
        "key": "downloads",
        "label": "Downloads",
        "type": "number"
      },
      {
        "key": "saves",
        "label": "Saves",
        "type": "number"
      },
      {
        "key": "is_ad",
        "label": "Is Ad",
        "type": "boolean"
      },
      {
        "key": "cover",
        "label": "Cover"
      },
      {
        "key": "dynamic_cover",
        "label": "Dynamic Cover"
      },
      {
        "key": "origin_cover",
        "label": "Origin Cover"
      },
      {
        "key": "video_url",
        "label": "Video URL"
      },
      {
        "key": "video_url_hd",
        "label": "Video URL Hd"
      },
      {
        "key": "video_url_watermarked",
        "label": "Video URL Watermarked"
      },
      {
        "key": "size",
        "label": "Size",
        "type": "number"
      },
      {
        "key": "size_hd",
        "label": "Size Hd",
        "type": "number"
      },
      {
        "key": "size_watermarked",
        "label": "Size Watermarked",
        "type": "number"
      },
      {
        "key": "author",
        "label": "Author"
      },
      {
        "key": "author_name",
        "label": "Author Name"
      },
      {
        "key": "author_id",
        "label": "Author ID"
      },
      {
        "key": "author_avatar",
        "label": "Author Avatar"
      },
      {
        "key": "author_url",
        "label": "Author URL"
      },
      {
        "key": "music_id",
        "label": "Music ID"
      },
      {
        "key": "music_title",
        "label": "Music Title"
      },
      {
        "key": "music_author",
        "label": "Music Author"
      },
      {
        "key": "music_url",
        "label": "Music URL"
      },
      {
        "key": "music_cover",
        "label": "Music Cover"
      },
      {
        "key": "music_album",
        "label": "Music Album"
      },
      {
        "key": "music_original",
        "label": "Music Original",
        "type": "boolean"
      },
      {
        "key": "music_duration",
        "label": "Music Duration",
        "type": "number"
      },
      {
        "key": "mentioned_user_ids",
        "label": "Mentioned User IDs",
        "list": true
      }
    ],
    "trigger": null
  }
];
