// Generated by scripts/generate.py from spec/openapi.json. Do not edit by hand;
// change the spec or the generator and run `npm run generate`.
module.exports = [
  {
    "key": "trustpilot_company_reviews",
    "path": "/v1/trustpilot/company/reviews",
    "method": "GET",
    "platform": "Trustpilot",
    "noun": "Review",
    "kind": "list",
    "listKey": "reviews",
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/trustpilot-company-reviews",
    "action": {
      "label": "Get Trustpilot Company Reviews",
      "description": "Gets a company's Trustpilot reviews and full profile by website domain. Each page returns up to 20 reviews; one call fetches up to 10 pages. $0.005 per page after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "domain",
        "label": "Domain",
        "required": true,
        "type": "string",
        "helpText": "Company website domain (e.g. gossby.com) or its Trustpilot review-page URL (max 500 characters)",
        "placeholder": "gossby.com"
      },
      {
        "key": "pages",
        "label": "Pages to Fetch",
        "required": false,
        "type": "integer",
        "default": "1",
        "helpText": "Number of pages to fetch, 1-10 (default: 1). Each page returns up to 20 reviews and is billed as one request (1-10).",
        "placeholder": "2"
      },
      {
        "key": "sort_by",
        "label": "Sort By",
        "required": false,
        "type": "string",
        "default": "most_relevant",
        "helpText": "most_relevant (default), newest",
        "choices": {
          "most_relevant": "Most Relevant",
          "newest": "Newest"
        },
        "placeholder": "newest"
      },
      {
        "key": "rating",
        "label": "Rating",
        "required": false,
        "type": "string",
        "helpText": "Only reviews with these star ratings, comma-separated 1-5 (e.g. 1,2 or 5)"
      },
      {
        "key": "posted_ago",
        "label": "Posted Within",
        "required": false,
        "type": "string",
        "helpText": "Only reviews from this period: 30d, 3m, 6m, 12m (default: all time)",
        "choices": {
          "30d": "Last 30 days",
          "3m": "Last 3 months",
          "6m": "Last 6 months",
          "12m": "Last 12 months"
        }
      },
      {
        "key": "language",
        "label": "Language",
        "required": false,
        "type": "string",
        "helpText": "2-letter ISO 639-1 language code (e.g. en, de). Default: all languages"
      },
      {
        "key": "verified",
        "label": "Verified",
        "required": false,
        "type": "boolean",
        "helpText": "Set to true to return only verified reviews"
      },
      {
        "key": "with_replies",
        "label": "Include Replies",
        "required": false,
        "type": "boolean",
        "helpText": "Set to true to return only reviews the company has replied to"
      },
      {
        "key": "query",
        "label": "Search Query",
        "required": false,
        "type": "string",
        "helpText": "Only reviews matching this keyword or phrase (max 500 characters)"
      },
      {
        "key": "get_sentiment",
        "label": "Add Sentiment Analysis",
        "required": false,
        "type": "boolean",
        "helpText": "Set to true to add AI emotion analysis to each review. Adds a `sentiment` object containing `emotions` (joy, trust, fear, surprise, sadness, disgust, anger and anticipation, each scored 0-100), `dominant_emotion`, `emotional_intensity` (0-10), and `polarity` (positive, negative or neutral). Any review that cannot be scored returns `sentiment: null`."
      }
    ],
    "sample": {
      "company": {
        "business_unit_id": "5dc962f10fdaf000012b2f08",
        "name": "Gossby",
        "domain": "gossby.com",
        "website": "https://gossby.com",
        "url": "https://www.trustpilot.com/review/gossby.com",
        "logo": "https://s3-eu-west-1.amazonaws.com/tpd/logos/5dc962f10fdaf000012b2f08/0x0.png",
        "rating": 4.2,
        "stars": 4.0,
        "review_count": 37687,
        "review_count_last_12_months": 1313,
        "reviews_per_rating": {
          "1": 3934,
          "2": 1110,
          "3": 1516,
          "4": 2829,
          "5": 28298
        },
        "categories": [
          "Gift Shop",
          "Clothing Store",
          "Hobby Store"
        ],
        "category_path": [
          "Shopping & Fashion",
          "Clothing & Underwear",
          "Clothing Store"
        ],
        "is_claimed": true,
        "claimed_date": "2019-11-15T04:26:53.000Z",
        "is_closed": false,
        "is_temporarily_closed": false,
        "is_collecting_reviews": false,
        "verification": {
          "verified_payment_method": false,
          "verified_user_identity": true,
          "verified_by_google": true
        },
        "reply_behavior": {
          "reply_percentage": 98.7012987012987,
          "average_days_to_reply": 0.25,
          "negative_reviews_with_replies": 228,
          "total_negative_reviews": 231,
          "last_reply_to_negative": "2026-09-06T01:30:03Z"
        },
        "email": "support@gossby.com",
        "phone_number": "(585) 366 8846",
        "address": "6901 Riverport Dr",
        "city": "Louisville",
        "zipcode": "40258",
        "country": "US",
        "locations_count": 0,
        "topics": [
          "Order",
          "Delivery service",
          "Product"
        ]
      },
      "reviews": [
        {
          "review_id": "6a9e02811b7c1d51f71113ca",
          "review_link": "https://www.trustpilot.com/reviews/6a9e02811b7c1d51f71113ca",
          "rating": 5,
          "title": "5 stars all around",
          "review_text": "There are lots of great products. I had trouble narrowing it down. I like the preview option to see what the personalization would look like. The product was delivered faster than I expected and look…",
          "review_language": "en",
          "review_datetime_utc": "2026-09-07T02:17:05.000Z",
          "review_timestamp": 1788747425,
          "experience_date": "2026-09-06",
          "updated_datetime_utc": null,
          "is_verified": false,
          "verification_level": "not-verified",
          "like_count": 0,
          "author_id": "6a9e0193452b16209f5549a1",
          "author_name": "Ash",
          "author_country": "US",
          "author_review_count": 1,
          "author_link": "https://www.trustpilot.com/users/6a9e0193452b16209f5549a1",
          "owner_response": null
        },
        {
          "review_id": "6a9db9402386d1ebd2295f29",
          "review_link": "https://www.trustpilot.com/reviews/6a9db9402386d1ebd2295f29",
          "rating": 5,
          "title": "I love the You and Me & the Dog mug",
          "review_text": "I love the You and Me & the Dog mug. The amount of design options is great, nice colors and sizes. The only problem I had was when I ordered blue trim I didn’t realize it only came in the smaller siz…",
          "review_language": "en",
          "review_datetime_utc": "2026-09-06T21:04:32.000Z",
          "review_timestamp": 1788728672,
          "experience_date": "2026-09-06",
          "updated_datetime_utc": null,
          "is_verified": false,
          "verification_level": "invited",
          "like_count": 0,
          "author_id": "5693f8c70000ff0001fb4ce3",
          "author_name": "Darleen",
          "author_country": "US",
          "author_review_count": 5,
          "author_link": "https://www.trustpilot.com/users/5693f8c70000ff0001fb4ce3",
          "owner_response": null
        }
      ],
      "count": 2,
      "pages": 2,
      "sort_by": "newest"
    },
    "outputFields": [
      {
        "key": "company__business_unit_id",
        "label": "Company Business Unit ID"
      },
      {
        "key": "company__name",
        "label": "Company Name"
      },
      {
        "key": "company__domain",
        "label": "Company Domain"
      },
      {
        "key": "company__website",
        "label": "Company Website"
      },
      {
        "key": "company__url",
        "label": "Company URL"
      },
      {
        "key": "company__logo",
        "label": "Company Logo"
      },
      {
        "key": "company__rating",
        "label": "Company Rating",
        "type": "number"
      },
      {
        "key": "company__stars",
        "label": "Company Stars",
        "type": "number"
      },
      {
        "key": "company__review_count",
        "label": "Company Review Count",
        "type": "number"
      },
      {
        "key": "company__review_count_last_12_months",
        "label": "Company Review Count Last 12 Months",
        "type": "number"
      },
      {
        "key": "company__reviews_per_rating__1",
        "label": "Reviews Per Rating 1",
        "type": "number"
      },
      {
        "key": "company__reviews_per_rating__2",
        "label": "Reviews Per Rating 2",
        "type": "number"
      },
      {
        "key": "company__reviews_per_rating__3",
        "label": "Reviews Per Rating 3",
        "type": "number"
      },
      {
        "key": "company__reviews_per_rating__4",
        "label": "Reviews Per Rating 4",
        "type": "number"
      },
      {
        "key": "company__reviews_per_rating__5",
        "label": "Reviews Per Rating 5",
        "type": "number"
      },
      {
        "key": "company__categories",
        "label": "Company Categories",
        "list": true
      },
      {
        "key": "company__category_path",
        "label": "Company Category Path",
        "list": true
      },
      {
        "key": "company__is_claimed",
        "label": "Company Is Claimed",
        "type": "boolean"
      },
      {
        "key": "company__claimed_date",
        "label": "Company Claimed Date"
      },
      {
        "key": "company__is_closed",
        "label": "Company Is Closed",
        "type": "boolean"
      },
      {
        "key": "company__is_temporarily_closed",
        "label": "Company Is Temporarily Closed",
        "type": "boolean"
      },
      {
        "key": "company__is_collecting_reviews",
        "label": "Company Is Collecting Reviews",
        "type": "boolean"
      },
      {
        "key": "company__verification__verified_payment_method",
        "label": "Verification Verified Payment Method",
        "type": "boolean"
      },
      {
        "key": "company__verification__verified_user_identity",
        "label": "Verification Verified User Identity",
        "type": "boolean"
      },
      {
        "key": "company__verification__verified_by_google",
        "label": "Verification Verified By Google",
        "type": "boolean"
      },
      {
        "key": "company__reply_behavior__reply_percentage",
        "label": "Reply Behavior Reply Percentage",
        "type": "number"
      },
      {
        "key": "company__reply_behavior__average_days_to_reply",
        "label": "Reply Behavior Average Days To Reply",
        "type": "number"
      },
      {
        "key": "company__reply_behavior__negative_reviews_with_replies",
        "label": "Reply Behavior Negative Reviews With Replies",
        "type": "number"
      },
      {
        "key": "company__reply_behavior__total_negative_reviews",
        "label": "Reply Behavior Total Negative Reviews",
        "type": "number"
      },
      {
        "key": "company__reply_behavior__last_reply_to_negative",
        "label": "Reply Behavior Last Reply To Negative"
      },
      {
        "key": "company__email",
        "label": "Company Email"
      },
      {
        "key": "company__phone_number",
        "label": "Company Phone Number"
      },
      {
        "key": "company__address",
        "label": "Company Address"
      },
      {
        "key": "company__city",
        "label": "Company City"
      },
      {
        "key": "company__zipcode",
        "label": "Company Zipcode"
      },
      {
        "key": "company__country",
        "label": "Company Country"
      },
      {
        "key": "company__locations_count",
        "label": "Company Locations Count",
        "type": "number"
      },
      {
        "key": "company__topics",
        "label": "Company Topics",
        "list": true
      },
      {
        "key": "reviews[]review_id",
        "label": "Reviews: Review ID"
      },
      {
        "key": "reviews[]review_link",
        "label": "Reviews: Review Link"
      },
      {
        "key": "reviews[]rating",
        "label": "Reviews: Rating",
        "type": "number"
      },
      {
        "key": "reviews[]title",
        "label": "Reviews: Title"
      },
      {
        "key": "reviews[]review_text",
        "label": "Reviews: Review Text"
      },
      {
        "key": "reviews[]review_language",
        "label": "Reviews: Review Language"
      },
      {
        "key": "reviews[]review_datetime_utc",
        "label": "Reviews: Review Datetime UTC"
      },
      {
        "key": "reviews[]review_timestamp",
        "label": "Reviews: Review Timestamp",
        "type": "number"
      },
      {
        "key": "reviews[]experience_date",
        "label": "Reviews: Experience Date"
      },
      {
        "key": "reviews[]updated_datetime_utc",
        "label": "Reviews: Updated Datetime UTC"
      },
      {
        "key": "reviews[]is_verified",
        "label": "Reviews: Is Verified",
        "type": "boolean"
      },
      {
        "key": "reviews[]verification_level",
        "label": "Reviews: Verification Level"
      },
      {
        "key": "reviews[]like_count",
        "label": "Reviews: Like Count",
        "type": "number"
      },
      {
        "key": "reviews[]author_id",
        "label": "Reviews: Author ID"
      },
      {
        "key": "reviews[]author_name",
        "label": "Reviews: Author Name"
      },
      {
        "key": "reviews[]author_country",
        "label": "Reviews: Author Country"
      },
      {
        "key": "reviews[]author_review_count",
        "label": "Reviews: Author Review Count",
        "type": "number"
      },
      {
        "key": "reviews[]author_link",
        "label": "Reviews: Author Link"
      },
      {
        "key": "reviews[]owner_response",
        "label": "Reviews: Owner Response"
      },
      {
        "key": "count",
        "label": "Count",
        "type": "number"
      },
      {
        "key": "pages",
        "label": "Pages",
        "type": "number"
      },
      {
        "key": "sort_by",
        "label": "Sort By"
      }
    ],
    "trigger": {
      "label": "New Trustpilot Company Review",
      "description": "Triggers when a company gets a new Trustpilot review. Each check runs Get Trustpilot Company Reviews ($0.005 per page).",
      "inputFields": [
        {
          "key": "domain",
          "label": "Domain",
          "required": true,
          "type": "string",
          "helpText": "Company website domain (e.g. gossby.com) or its Trustpilot review-page URL (max 500 characters)",
          "placeholder": "gossby.com"
        },
        {
          "key": "pages",
          "label": "Pages to Fetch",
          "required": false,
          "type": "integer",
          "default": "1",
          "helpText": "Number of pages to fetch, 1-10 (default: 1). Each page returns up to 20 reviews and is billed as one request (1-10). Every check of this trigger fetches this many pages, each billed as one request.",
          "placeholder": "2"
        },
        {
          "key": "sort_by",
          "label": "Sort By",
          "required": false,
          "type": "string",
          "default": "most_relevant",
          "helpText": "most_relevant (default), newest",
          "choices": {
            "most_relevant": "Most Relevant",
            "newest": "Newest"
          },
          "placeholder": "newest"
        },
        {
          "key": "rating",
          "label": "Rating",
          "required": false,
          "type": "string",
          "helpText": "Only reviews with these star ratings, comma-separated 1-5 (e.g. 1,2 or 5)"
        },
        {
          "key": "posted_ago",
          "label": "Posted Within",
          "required": false,
          "type": "string",
          "helpText": "Only reviews from this period: 30d, 3m, 6m, 12m (default: all time)",
          "choices": {
            "30d": "Last 30 days",
            "3m": "Last 3 months",
            "6m": "Last 6 months",
            "12m": "Last 12 months"
          }
        },
        {
          "key": "language",
          "label": "Language",
          "required": false,
          "type": "string",
          "helpText": "2-letter ISO 639-1 language code (e.g. en, de). Default: all languages"
        },
        {
          "key": "verified",
          "label": "Verified",
          "required": false,
          "type": "boolean",
          "helpText": "Set to true to return only verified reviews"
        },
        {
          "key": "with_replies",
          "label": "Include Replies",
          "required": false,
          "type": "boolean",
          "helpText": "Set to true to return only reviews the company has replied to"
        },
        {
          "key": "query",
          "label": "Search Query",
          "required": false,
          "type": "string",
          "helpText": "Only reviews matching this keyword or phrase (max 500 characters)"
        },
        {
          "key": "get_sentiment",
          "label": "Add Sentiment Analysis",
          "required": false,
          "type": "boolean",
          "helpText": "Set to true to add AI emotion analysis to each review. Adds a `sentiment` object containing `emotions` (joy, trust, fear, surprise, sadness, disgust, anger and anticipation, each scored 0-100), `dominant_emotion`, `emotional_intensity` (0-10), and `polarity` (positive, negative or neutral). Any review that cannot be scored returns `sentiment: null`."
        }
      ],
      "sample": {
        "id": "6a9e02811b7c1d51f71113ca",
        "review_id": "6a9e02811b7c1d51f71113ca",
        "review_link": "https://www.trustpilot.com/reviews/6a9e02811b7c1d51f71113ca",
        "rating": 5,
        "title": "5 stars all around",
        "review_text": "There are lots of great products. I had trouble narrowing it down. I like the preview option to see what the personalization would look like. The product was delivered faster than I expected and look…",
        "review_language": "en",
        "review_datetime_utc": "2026-09-07T02:17:05.000Z",
        "review_timestamp": 1788747425,
        "experience_date": "2026-09-06",
        "updated_datetime_utc": null,
        "is_verified": false,
        "verification_level": "not-verified",
        "like_count": 0,
        "author_id": "6a9e0193452b16209f5549a1",
        "author_name": "Ash",
        "author_country": "US",
        "author_review_count": 1,
        "author_link": "https://www.trustpilot.com/users/6a9e0193452b16209f5549a1",
        "owner_response": null
      },
      "outputFields": [
        {
          "key": "id",
          "label": "ID",
          "primary": true
        },
        {
          "key": "review_id",
          "label": "Review ID"
        },
        {
          "key": "review_link",
          "label": "Review Link"
        },
        {
          "key": "rating",
          "label": "Rating",
          "type": "number"
        },
        {
          "key": "title",
          "label": "Title"
        },
        {
          "key": "review_text",
          "label": "Review Text"
        },
        {
          "key": "review_language",
          "label": "Review Language"
        },
        {
          "key": "review_datetime_utc",
          "label": "Review Datetime UTC"
        },
        {
          "key": "review_timestamp",
          "label": "Review Timestamp",
          "type": "number"
        },
        {
          "key": "experience_date",
          "label": "Experience Date"
        },
        {
          "key": "updated_datetime_utc",
          "label": "Updated Datetime UTC"
        },
        {
          "key": "is_verified",
          "label": "Is Verified",
          "type": "boolean"
        },
        {
          "key": "verification_level",
          "label": "Verification Level"
        },
        {
          "key": "like_count",
          "label": "Like Count",
          "type": "number"
        },
        {
          "key": "author_id",
          "label": "Author ID"
        },
        {
          "key": "author_name",
          "label": "Author Name"
        },
        {
          "key": "author_country",
          "label": "Author Country"
        },
        {
          "key": "author_review_count",
          "label": "Author Review Count",
          "type": "number"
        },
        {
          "key": "author_link",
          "label": "Author Link"
        },
        {
          "key": "owner_response",
          "label": "Owner Response"
        }
      ]
    }
  },
  {
    "key": "trustpilot_companies",
    "path": "/v1/trustpilot/companies",
    "method": "GET",
    "platform": "Trustpilot",
    "noun": "Company",
    "kind": "list",
    "listKey": "companies",
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/trustpilot-companies",
    "action": {
      "label": "Search Trustpilot Companies",
      "description": "Searches Trustpilot companies by name or keyword. Returns 10 matches per page, plus the categories that match the query. $0.005 per request after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "query",
        "label": "Search Query",
        "required": true,
        "type": "string",
        "helpText": "Company name or keyword (max 500 characters)",
        "placeholder": "amazon"
      },
      {
        "key": "page",
        "label": "Page Number",
        "required": false,
        "type": "integer",
        "default": "1",
        "helpText": "Page number, 1-500 (default: 1). Each page returns up to 10 results (1-500)."
      },
      {
        "key": "min_rating",
        "label": "Minimum Rating",
        "required": false,
        "type": "string",
        "helpText": "Only companies with at least this TrustScore: 3, 4, 4.5",
        "choices": {
          "3": "3+",
          "4": "4+",
          "4.5": "4.5+"
        }
      },
      {
        "key": "min_review_count",
        "label": "Minimum Review Count",
        "required": false,
        "type": "string",
        "helpText": "Only companies with at least this many reviews: 25, 50, 100, 250, 500",
        "choices": {
          "25": "25+",
          "50": "50+",
          "100": "100+",
          "250": "250+",
          "500": "500+"
        }
      }
    ],
    "sample": {
      "companies": [
        {
          "business_unit_id": "46ad346800006400050092d0",
          "name": "Amazon",
          "domain": "www.amazon.com",
          "website": "https://www.amazon.com",
          "url": "https://www.trustpilot.com/review/www.amazon.com",
          "logo": null,
          "rating": 1.6,
          "stars": 1.5,
          "review_count": 48972,
          "categories": [
            {
              "category_id": "book_store",
              "name": "Book Store",
              "is_primary": false
            },
            {
              "category_id": "clothing_store",
              "name": "Clothing Store",
              "is_primary": false
            },
            {
              "category_id": "shoe_store",
              "name": "Shoe Store",
              "is_primary": false
            }
          ],
          "city": null,
          "country": "United Kingdom",
          "address": null,
          "zipcode": null,
          "is_recommended": false
        },
        {
          "business_unit_id": "46d72ac0000064000500e9bb",
          "name": "Amazon",
          "domain": "www.amazon.fr",
          "website": "https://www.amazon.fr",
          "url": "https://www.trustpilot.com/review/www.amazon.fr",
          "logo": null,
          "rating": 1.6,
          "stars": 1.5,
          "review_count": 19281,
          "categories": [
            {
              "category_id": "events_entertainment",
              "name": "Events & Entertainment",
              "is_primary": false
            }
          ],
          "city": null,
          "country": "France",
          "address": null,
          "zipcode": null,
          "is_recommended": false
        }
      ],
      "count": 10,
      "page": 1,
      "total_pages": 56,
      "total_results": 557,
      "query": "amazon",
      "categories": [
        {
          "category_id": "book_store",
          "name": "Book Store"
        },
        {
          "category_id": "e_commerce_agency",
          "name": "e-Commerce Agency"
        },
        {
          "category_id": "e_commerce_service",
          "name": "e-Commerce Service"
        }
      ]
    },
    "outputFields": [
      {
        "key": "companies[]business_unit_id",
        "label": "Companies: Business Unit ID"
      },
      {
        "key": "companies[]name",
        "label": "Companies: Name"
      },
      {
        "key": "companies[]domain",
        "label": "Companies: Domain"
      },
      {
        "key": "companies[]website",
        "label": "Companies: Website"
      },
      {
        "key": "companies[]url",
        "label": "Companies: URL"
      },
      {
        "key": "companies[]logo",
        "label": "Companies: Logo"
      },
      {
        "key": "companies[]rating",
        "label": "Companies: Rating",
        "type": "number"
      },
      {
        "key": "companies[]stars",
        "label": "Companies: Stars",
        "type": "number"
      },
      {
        "key": "companies[]review_count",
        "label": "Companies: Review Count",
        "type": "number"
      },
      {
        "key": "companies[]categories[]category_id",
        "label": "Categories: Category ID"
      },
      {
        "key": "companies[]categories[]name",
        "label": "Categories: Name"
      },
      {
        "key": "companies[]categories[]is_primary",
        "label": "Categories: Is Primary",
        "type": "boolean"
      },
      {
        "key": "companies[]city",
        "label": "Companies: City"
      },
      {
        "key": "companies[]country",
        "label": "Companies: Country"
      },
      {
        "key": "companies[]address",
        "label": "Companies: Address"
      },
      {
        "key": "companies[]zipcode",
        "label": "Companies: Zipcode"
      },
      {
        "key": "companies[]is_recommended",
        "label": "Companies: Is Recommended",
        "type": "boolean"
      },
      {
        "key": "count",
        "label": "Count",
        "type": "number"
      },
      {
        "key": "page",
        "label": "Page",
        "type": "number"
      },
      {
        "key": "total_pages",
        "label": "Total Pages",
        "type": "number"
      },
      {
        "key": "total_results",
        "label": "Total Results",
        "type": "number"
      },
      {
        "key": "query",
        "label": "Query"
      },
      {
        "key": "categories[]category_id",
        "label": "Categories: Category ID"
      },
      {
        "key": "categories[]name",
        "label": "Categories: Name"
      }
    ],
    "trigger": {
      "label": "New Trustpilot Company Matching Search",
      "description": "Triggers when a new Trustpilot company matches your search. Each check runs Search Trustpilot Companies ($0.005 per request).",
      "inputFields": [
        {
          "key": "query",
          "label": "Search Query",
          "required": true,
          "type": "string",
          "helpText": "Company name or keyword (max 500 characters)",
          "placeholder": "amazon"
        },
        {
          "key": "page",
          "label": "Page Number",
          "required": false,
          "type": "integer",
          "default": "1",
          "helpText": "Page number, 1-500 (default: 1). Each page returns up to 10 results (1-500)."
        },
        {
          "key": "min_rating",
          "label": "Minimum Rating",
          "required": false,
          "type": "string",
          "helpText": "Only companies with at least this TrustScore: 3, 4, 4.5",
          "choices": {
            "3": "3+",
            "4": "4+",
            "4.5": "4.5+"
          }
        },
        {
          "key": "min_review_count",
          "label": "Minimum Review Count",
          "required": false,
          "type": "string",
          "helpText": "Only companies with at least this many reviews: 25, 50, 100, 250, 500",
          "choices": {
            "25": "25+",
            "50": "50+",
            "100": "100+",
            "250": "250+",
            "500": "500+"
          }
        }
      ],
      "sample": {
        "id": "46ad346800006400050092d0",
        "business_unit_id": "46ad346800006400050092d0",
        "name": "Amazon",
        "domain": "www.amazon.com",
        "website": "https://www.amazon.com",
        "url": "https://www.trustpilot.com/review/www.amazon.com",
        "logo": null,
        "rating": 1.6,
        "stars": 1.5,
        "review_count": 48972,
        "categories": [
          {
            "category_id": "book_store",
            "name": "Book Store",
            "is_primary": false
          },
          {
            "category_id": "clothing_store",
            "name": "Clothing Store",
            "is_primary": false
          },
          {
            "category_id": "shoe_store",
            "name": "Shoe Store",
            "is_primary": false
          }
        ],
        "city": null,
        "country": "United Kingdom",
        "address": null,
        "zipcode": null,
        "is_recommended": false
      },
      "outputFields": [
        {
          "key": "id",
          "label": "ID",
          "primary": true
        },
        {
          "key": "business_unit_id",
          "label": "Business Unit ID"
        },
        {
          "key": "name",
          "label": "Name"
        },
        {
          "key": "domain",
          "label": "Domain"
        },
        {
          "key": "website",
          "label": "Website"
        },
        {
          "key": "url",
          "label": "URL"
        },
        {
          "key": "logo",
          "label": "Logo"
        },
        {
          "key": "rating",
          "label": "Rating",
          "type": "number"
        },
        {
          "key": "stars",
          "label": "Stars",
          "type": "number"
        },
        {
          "key": "review_count",
          "label": "Review Count",
          "type": "number"
        },
        {
          "key": "categories[]category_id",
          "label": "Categories: Category ID"
        },
        {
          "key": "categories[]name",
          "label": "Categories: Name"
        },
        {
          "key": "categories[]is_primary",
          "label": "Categories: Is Primary",
          "type": "boolean"
        },
        {
          "key": "city",
          "label": "City"
        },
        {
          "key": "country",
          "label": "Country"
        },
        {
          "key": "address",
          "label": "Address"
        },
        {
          "key": "zipcode",
          "label": "Zipcode"
        },
        {
          "key": "is_recommended",
          "label": "Is Recommended",
          "type": "boolean"
        }
      ]
    }
  },
  {
    "key": "trustpilot_category_companies",
    "path": "/v1/trustpilot/category/companies",
    "method": "GET",
    "platform": "Trustpilot",
    "noun": "Company",
    "kind": "list",
    "listKey": "companies",
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/trustpilot-category-companies",
    "action": {
      "label": "Get Trustpilot Category Companies",
      "description": "Lists the companies in a Trustpilot category, ranked, 20 per page, along with the category's size and subcategories. $0.005 per request after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "category_id",
        "label": "Category ID",
        "required": true,
        "type": "string",
        "helpText": "Category slug, e.g. bank or electronics_technology. See Category IDs ([docs](https://apidirect.io/docs/trustpilot-category-ids)). A trustpilot.com/categories/... URL also works",
        "placeholder": "electronics_technology"
      },
      {
        "key": "page",
        "label": "Page Number",
        "required": false,
        "type": "integer",
        "default": "1",
        "helpText": "Page number, 1-500 (default: 1). Each page returns up to 20 companies (1-500)."
      },
      {
        "key": "sort_by",
        "label": "Sort By",
        "required": false,
        "type": "string",
        "default": "recommended",
        "helpText": "recommended (default), recently_reviewed",
        "choices": {
          "recommended": "Recommended",
          "recently_reviewed": "Recently Reviewed"
        }
      },
      {
        "key": "country",
        "label": "Country",
        "required": false,
        "type": "string",
        "helpText": "2-letter ISO 3166-1 country code (e.g. us, gb, de). Default: all countries",
        "placeholder": "us"
      },
      {
        "key": "min_rating",
        "label": "Minimum Rating",
        "required": false,
        "type": "string",
        "helpText": "Only companies with at least this TrustScore: 3, 3.5, 4, 4.5",
        "choices": {
          "3": "3+",
          "3.5": "3.5+",
          "4": "4+",
          "4.5": "4.5+"
        },
        "placeholder": "4"
      },
      {
        "key": "claimed",
        "label": "Claimed",
        "required": false,
        "type": "boolean",
        "helpText": "Set to true to return only companies that have claimed their Trustpilot profile"
      }
    ],
    "sample": {
      "companies": [
        {
          "business_unit_id": "4bdc9828000064000505dc60",
          "name": "Flashbay",
          "domain": "www.flashbay.com",
          "website": "https://www.flashbay.com",
          "url": "https://www.trustpilot.com/review/www.flashbay.com",
          "logo": "https://s3-eu-west-1.amazonaws.com/tpd/screenshotlogo-domain/4bdc9828000064000505dc60/198x149.png",
          "rating": 5.0,
          "stars": 5.0,
          "review_count": 19329,
          "categories": [
            {
              "category_id": "gift_shop",
              "name": "Gift Shop",
              "is_primary": false
            },
            {
              "category_id": "hobby_store",
              "name": "Hobby Store",
              "is_primary": false
            },
            {
              "category_id": "business_to_business_service",
              "name": "Business to Business Service",
              "is_primary": false
            }
          ],
          "city": null,
          "country": "United States",
          "address": "Flashbay Inc. 569 Clyde Avenue, Unit 500, Mountain View, CA 94043",
          "zipcode": null,
          "is_recommended": true
        },
        {
          "business_unit_id": "4bdc7d56000064000505cb54",
          "name": "TadiBrothers",
          "domain": "www.tadibrothers.com",
          "website": "https://www.tadibrothers.com",
          "url": "https://www.trustpilot.com/review/www.tadibrothers.com",
          "logo": "https://s3-eu-west-1.amazonaws.com/tpd/screenshotlogo-domain/4bdc7d56000064000505cb54/198x149.png",
          "rating": 5.0,
          "stars": 5.0,
          "review_count": 3685,
          "categories": [
            {
              "category_id": "electronics_store",
              "name": "Electronics Store",
              "is_primary": true
            },
            {
              "category_id": "auto_repair_shop",
              "name": "Auto Repair Shop",
              "is_primary": false
            },
            {
              "category_id": "truck_parts_supplier",
              "name": "Truck Parts Supplier",
              "is_primary": false
            }
          ],
          "city": "Reseda",
          "country": "United States",
          "address": "6924 Canby Ave, #107",
          "zipcode": "91335",
          "is_recommended": true
        }
      ],
      "count": 20,
      "page": 1,
      "total_pages": 500,
      "total_companies": 10000,
      "category": {
        "category_id": "electronics_technology",
        "name": "Electronics & Technology",
        "business_count": 59806,
        "parent_id": null,
        "url": "https://www.trustpilot.com/categories/electronics_technology",
        "subcategories": [
          {
            "category_id": "appliances_electronics",
            "name": "Appliances & Electronics",
            "business_count": 5569
          },
          {
            "category_id": "audio_visual",
            "name": "Audio & Visual",
            "business_count": 1807
          },
          {
            "category_id": "computers_phones",
            "name": "Computers & Phones",
            "business_count": 8342
          }
        ]
      }
    },
    "outputFields": [
      {
        "key": "companies[]business_unit_id",
        "label": "Companies: Business Unit ID"
      },
      {
        "key": "companies[]name",
        "label": "Companies: Name"
      },
      {
        "key": "companies[]domain",
        "label": "Companies: Domain"
      },
      {
        "key": "companies[]website",
        "label": "Companies: Website"
      },
      {
        "key": "companies[]url",
        "label": "Companies: URL"
      },
      {
        "key": "companies[]logo",
        "label": "Companies: Logo"
      },
      {
        "key": "companies[]rating",
        "label": "Companies: Rating",
        "type": "number"
      },
      {
        "key": "companies[]stars",
        "label": "Companies: Stars",
        "type": "number"
      },
      {
        "key": "companies[]review_count",
        "label": "Companies: Review Count",
        "type": "number"
      },
      {
        "key": "companies[]categories[]category_id",
        "label": "Categories: Category ID"
      },
      {
        "key": "companies[]categories[]name",
        "label": "Categories: Name"
      },
      {
        "key": "companies[]categories[]is_primary",
        "label": "Categories: Is Primary",
        "type": "boolean"
      },
      {
        "key": "companies[]city",
        "label": "Companies: City"
      },
      {
        "key": "companies[]country",
        "label": "Companies: Country"
      },
      {
        "key": "companies[]address",
        "label": "Companies: Address"
      },
      {
        "key": "companies[]zipcode",
        "label": "Companies: Zipcode"
      },
      {
        "key": "companies[]is_recommended",
        "label": "Companies: Is Recommended",
        "type": "boolean"
      },
      {
        "key": "count",
        "label": "Count",
        "type": "number"
      },
      {
        "key": "page",
        "label": "Page",
        "type": "number"
      },
      {
        "key": "total_pages",
        "label": "Total Pages",
        "type": "number"
      },
      {
        "key": "total_companies",
        "label": "Total Companies",
        "type": "number"
      },
      {
        "key": "category__category_id",
        "label": "Category Category ID"
      },
      {
        "key": "category__name",
        "label": "Category Name"
      },
      {
        "key": "category__business_count",
        "label": "Category Business Count",
        "type": "number"
      },
      {
        "key": "category__parent_id",
        "label": "Category Parent ID"
      },
      {
        "key": "category__url",
        "label": "Category URL"
      },
      {
        "key": "category__subcategories[]category_id",
        "label": "Subcategories: Category ID"
      },
      {
        "key": "category__subcategories[]name",
        "label": "Subcategories: Name"
      },
      {
        "key": "category__subcategories[]business_count",
        "label": "Subcategories: Business Count",
        "type": "number"
      }
    ],
    "trigger": {
      "label": "New Trustpilot Company in Category",
      "description": "Triggers when a new company appears in a Trustpilot category. Each check runs Get Trustpilot Category Companies ($0.005 per request).",
      "inputFields": [
        {
          "key": "category_id",
          "label": "Category ID",
          "required": true,
          "type": "string",
          "helpText": "Category slug, e.g. bank or electronics_technology. See Category IDs ([docs](https://apidirect.io/docs/trustpilot-category-ids)). A trustpilot.com/categories/... URL also works",
          "placeholder": "electronics_technology"
        },
        {
          "key": "page",
          "label": "Page Number",
          "required": false,
          "type": "integer",
          "default": "1",
          "helpText": "Page number, 1-500 (default: 1). Each page returns up to 20 companies (1-500)."
        },
        {
          "key": "sort_by",
          "label": "Sort By",
          "required": false,
          "type": "string",
          "default": "recommended",
          "helpText": "recommended (default), recently_reviewed",
          "choices": {
            "recommended": "Recommended",
            "recently_reviewed": "Recently Reviewed"
          }
        },
        {
          "key": "country",
          "label": "Country",
          "required": false,
          "type": "string",
          "helpText": "2-letter ISO 3166-1 country code (e.g. us, gb, de). Default: all countries",
          "placeholder": "us"
        },
        {
          "key": "min_rating",
          "label": "Minimum Rating",
          "required": false,
          "type": "string",
          "helpText": "Only companies with at least this TrustScore: 3, 3.5, 4, 4.5",
          "choices": {
            "3": "3+",
            "3.5": "3.5+",
            "4": "4+",
            "4.5": "4.5+"
          },
          "placeholder": "4"
        },
        {
          "key": "claimed",
          "label": "Claimed",
          "required": false,
          "type": "boolean",
          "helpText": "Set to true to return only companies that have claimed their Trustpilot profile"
        }
      ],
      "sample": {
        "id": "4bdc9828000064000505dc60",
        "business_unit_id": "4bdc9828000064000505dc60",
        "name": "Flashbay",
        "domain": "www.flashbay.com",
        "website": "https://www.flashbay.com",
        "url": "https://www.trustpilot.com/review/www.flashbay.com",
        "logo": "https://s3-eu-west-1.amazonaws.com/tpd/screenshotlogo-domain/4bdc9828000064000505dc60/198x149.png",
        "rating": 5.0,
        "stars": 5.0,
        "review_count": 19329,
        "categories": [
          {
            "category_id": "gift_shop",
            "name": "Gift Shop",
            "is_primary": false
          },
          {
            "category_id": "hobby_store",
            "name": "Hobby Store",
            "is_primary": false
          },
          {
            "category_id": "business_to_business_service",
            "name": "Business to Business Service",
            "is_primary": false
          }
        ],
        "city": null,
        "country": "United States",
        "address": "Flashbay Inc. 569 Clyde Avenue, Unit 500, Mountain View, CA 94043",
        "zipcode": null,
        "is_recommended": true
      },
      "outputFields": [
        {
          "key": "id",
          "label": "ID",
          "primary": true
        },
        {
          "key": "business_unit_id",
          "label": "Business Unit ID"
        },
        {
          "key": "name",
          "label": "Name"
        },
        {
          "key": "domain",
          "label": "Domain"
        },
        {
          "key": "website",
          "label": "Website"
        },
        {
          "key": "url",
          "label": "URL"
        },
        {
          "key": "logo",
          "label": "Logo"
        },
        {
          "key": "rating",
          "label": "Rating",
          "type": "number"
        },
        {
          "key": "stars",
          "label": "Stars",
          "type": "number"
        },
        {
          "key": "review_count",
          "label": "Review Count",
          "type": "number"
        },
        {
          "key": "categories[]category_id",
          "label": "Categories: Category ID"
        },
        {
          "key": "categories[]name",
          "label": "Categories: Name"
        },
        {
          "key": "categories[]is_primary",
          "label": "Categories: Is Primary",
          "type": "boolean"
        },
        {
          "key": "city",
          "label": "City"
        },
        {
          "key": "country",
          "label": "Country"
        },
        {
          "key": "address",
          "label": "Address"
        },
        {
          "key": "zipcode",
          "label": "Zipcode"
        },
        {
          "key": "is_recommended",
          "label": "Is Recommended",
          "type": "boolean"
        }
      ]
    }
  },
  {
    "key": "trustpilot_category_newest",
    "path": "/v1/trustpilot/category/newest",
    "method": "GET",
    "platform": "Trustpilot",
    "noun": "Company",
    "kind": "list",
    "listKey": "companies",
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/trustpilot-category-newest",
    "action": {
      "label": "Get Newest Trustpilot Companies in Category",
      "description": "Gets the newest companies added to a Trustpilot category — the short list shown on the category page, plus the category's size and subcategories. $0.005 per request after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "category_id",
        "label": "Category ID",
        "required": true,
        "type": "string",
        "helpText": "Category slug, e.g. bank. See Category IDs ([docs](https://apidirect.io/docs/trustpilot-category-ids)). A trustpilot.com/categories/... URL also works",
        "placeholder": "bank"
      }
    ],
    "sample": {
      "companies": [
        {
          "business_unit_id": "6a7e73aed75f36cab8924224",
          "name": "Lutonsavings",
          "domain": "www.lutonsavings.com",
          "website": null,
          "url": "https://www.trustpilot.com/review/www.lutonsavings.com",
          "logo": null,
          "rating": 2.9,
          "stars": 3.0,
          "review_count": 2,
          "categories": [
            {
              "category_id": "savings_bank",
              "name": "Savings Bank",
              "is_primary": true
            },
            {
              "category_id": "bank",
              "name": "Bank",
              "is_primary": false
            },
            {
              "category_id": "non_bank_finance",
              "name": "Non-Bank Financial Service",
              "is_primary": false
            }
          ],
          "city": "",
          "country": "United States",
          "address": null,
          "zipcode": null,
          "is_recommended": null
        },
        {
          "business_unit_id": "6a8bf26af4ba0eb8dbbfe55c",
          "name": "Trustbankonline",
          "domain": "trustbankonline.com",
          "website": null,
          "url": "https://www.trustpilot.com/review/trustbankonline.com",
          "logo": null,
          "rating": 3.2,
          "stars": 3.0,
          "review_count": 1,
          "categories": [
            {
              "category_id": "financial_institution",
              "name": "Financial Institution",
              "is_primary": false
            },
            {
              "category_id": "cryptocurrency_service",
              "name": "Cryptocurrency Service",
              "is_primary": true
            },
            {
              "category_id": "bank",
              "name": "Bank",
              "is_primary": false
            }
          ],
          "city": "",
          "country": "United States",
          "address": null,
          "zipcode": null,
          "is_recommended": null
        }
      ],
      "count": 10,
      "category": {
        "category_id": "bank",
        "name": "Bank",
        "business_count": 1861,
        "parent_id": "banking_money",
        "url": "https://www.trustpilot.com/categories/bank",
        "subcategories": []
      }
    },
    "outputFields": [
      {
        "key": "companies[]business_unit_id",
        "label": "Companies: Business Unit ID"
      },
      {
        "key": "companies[]name",
        "label": "Companies: Name"
      },
      {
        "key": "companies[]domain",
        "label": "Companies: Domain"
      },
      {
        "key": "companies[]website",
        "label": "Companies: Website"
      },
      {
        "key": "companies[]url",
        "label": "Companies: URL"
      },
      {
        "key": "companies[]logo",
        "label": "Companies: Logo"
      },
      {
        "key": "companies[]rating",
        "label": "Companies: Rating",
        "type": "number"
      },
      {
        "key": "companies[]stars",
        "label": "Companies: Stars",
        "type": "number"
      },
      {
        "key": "companies[]review_count",
        "label": "Companies: Review Count",
        "type": "number"
      },
      {
        "key": "companies[]categories[]category_id",
        "label": "Categories: Category ID"
      },
      {
        "key": "companies[]categories[]name",
        "label": "Categories: Name"
      },
      {
        "key": "companies[]categories[]is_primary",
        "label": "Categories: Is Primary",
        "type": "boolean"
      },
      {
        "key": "companies[]city",
        "label": "Companies: City"
      },
      {
        "key": "companies[]country",
        "label": "Companies: Country"
      },
      {
        "key": "companies[]address",
        "label": "Companies: Address"
      },
      {
        "key": "companies[]zipcode",
        "label": "Companies: Zipcode"
      },
      {
        "key": "companies[]is_recommended",
        "label": "Companies: Is Recommended"
      },
      {
        "key": "count",
        "label": "Count",
        "type": "number"
      },
      {
        "key": "category__category_id",
        "label": "Category Category ID"
      },
      {
        "key": "category__name",
        "label": "Category Name"
      },
      {
        "key": "category__business_count",
        "label": "Category Business Count",
        "type": "number"
      },
      {
        "key": "category__parent_id",
        "label": "Category Parent ID"
      },
      {
        "key": "category__url",
        "label": "Category URL"
      },
      {
        "key": "category__subcategories",
        "label": "Category Subcategories",
        "list": true
      }
    ],
    "trigger": {
      "label": "Newly Listed Trustpilot Company in Category",
      "description": "Triggers when a company is newly listed in a Trustpilot category. Each check runs Get Newest Trustpilot Companies in Category ($0.005 per request).",
      "inputFields": [
        {
          "key": "category_id",
          "label": "Category ID",
          "required": true,
          "type": "string",
          "helpText": "Category slug, e.g. bank. See Category IDs ([docs](https://apidirect.io/docs/trustpilot-category-ids)). A trustpilot.com/categories/... URL also works",
          "placeholder": "bank"
        }
      ],
      "sample": {
        "id": "6a7e73aed75f36cab8924224",
        "business_unit_id": "6a7e73aed75f36cab8924224",
        "name": "Lutonsavings",
        "domain": "www.lutonsavings.com",
        "website": null,
        "url": "https://www.trustpilot.com/review/www.lutonsavings.com",
        "logo": null,
        "rating": 2.9,
        "stars": 3.0,
        "review_count": 2,
        "categories": [
          {
            "category_id": "savings_bank",
            "name": "Savings Bank",
            "is_primary": true
          },
          {
            "category_id": "bank",
            "name": "Bank",
            "is_primary": false
          },
          {
            "category_id": "non_bank_finance",
            "name": "Non-Bank Financial Service",
            "is_primary": false
          }
        ],
        "city": "",
        "country": "United States",
        "address": null,
        "zipcode": null,
        "is_recommended": null
      },
      "outputFields": [
        {
          "key": "id",
          "label": "ID",
          "primary": true
        },
        {
          "key": "business_unit_id",
          "label": "Business Unit ID"
        },
        {
          "key": "name",
          "label": "Name"
        },
        {
          "key": "domain",
          "label": "Domain"
        },
        {
          "key": "website",
          "label": "Website"
        },
        {
          "key": "url",
          "label": "URL"
        },
        {
          "key": "logo",
          "label": "Logo"
        },
        {
          "key": "rating",
          "label": "Rating",
          "type": "number"
        },
        {
          "key": "stars",
          "label": "Stars",
          "type": "number"
        },
        {
          "key": "review_count",
          "label": "Review Count",
          "type": "number"
        },
        {
          "key": "categories[]category_id",
          "label": "Categories: Category ID"
        },
        {
          "key": "categories[]name",
          "label": "Categories: Name"
        },
        {
          "key": "categories[]is_primary",
          "label": "Categories: Is Primary",
          "type": "boolean"
        },
        {
          "key": "city",
          "label": "City"
        },
        {
          "key": "country",
          "label": "Country"
        },
        {
          "key": "address",
          "label": "Address"
        },
        {
          "key": "zipcode",
          "label": "Zipcode"
        },
        {
          "key": "is_recommended",
          "label": "Is Recommended"
        }
      ]
    }
  },
  {
    "key": "trustpilot_category",
    "path": "/v1/trustpilot/category",
    "method": "GET",
    "platform": "Trustpilot",
    "noun": "Category",
    "kind": "detail",
    "listKey": null,
    "unwrapKey": "category",
    "docs": "https://apidirect.io/docs/trustpilot-category",
    "action": {
      "label": "Find Trustpilot Category",
      "description": "Gets a Trustpilot category's display name, business count, parent, and subcategories. Works at any level of the taxonomy. $0.005 per request after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "category_id",
        "label": "Category ID",
        "required": true,
        "type": "string",
        "helpText": "Category slug, e.g. electronics_technology. See Category IDs ([docs](https://apidirect.io/docs/trustpilot-category-ids)). A trustpilot.com/categories/... URL also works",
        "placeholder": "electronics_technology"
      }
    ],
    "sample": {
      "category_id": "electronics_technology",
      "name": "Electronics & Technology",
      "business_count": 59806,
      "parent_id": null,
      "url": "https://www.trustpilot.com/categories/electronics_technology",
      "subcategories": [
        {
          "category_id": "appliances_electronics",
          "name": "Appliances & Electronics",
          "business_count": 5569
        },
        {
          "category_id": "audio_visual",
          "name": "Audio & Visual",
          "business_count": 1807
        },
        {
          "category_id": "computers_phones",
          "name": "Computers & Phones",
          "business_count": 8342
        }
      ]
    },
    "outputFields": [
      {
        "key": "category_id",
        "label": "Category ID"
      },
      {
        "key": "name",
        "label": "Name"
      },
      {
        "key": "business_count",
        "label": "Business Count",
        "type": "number"
      },
      {
        "key": "parent_id",
        "label": "Parent ID"
      },
      {
        "key": "url",
        "label": "URL"
      },
      {
        "key": "subcategories[]category_id",
        "label": "Subcategories: Category ID"
      },
      {
        "key": "subcategories[]name",
        "label": "Subcategories: Name"
      },
      {
        "key": "subcategories[]business_count",
        "label": "Subcategories: Business Count",
        "type": "number"
      }
    ],
    "trigger": null
  },
  {
    "key": "trustpilot_categories",
    "path": "/v1/trustpilot/categories",
    "method": "GET",
    "platform": "Trustpilot",
    "noun": "Category",
    "kind": "list",
    "listKey": "categories",
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/trustpilot-categories",
    "action": {
      "label": "Search Trustpilot Categories",
      "description": "Searches Trustpilot categories by keyword to find category IDs at any level of the taxonomy. $0.005 per request after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "query",
        "label": "Search Query",
        "required": true,
        "type": "string",
        "helpText": "Keyword, e.g. bank or shop (max 200 characters)",
        "placeholder": "bank"
      }
    ],
    "sample": {
      "categories": [
        {
          "category_id": "bank",
          "name": "Bank"
        },
        {
          "category_id": "savings_bank",
          "name": "Savings Bank"
        },
        {
          "category_id": "private_sector_bank",
          "name": "Private Sector Bank"
        }
      ],
      "count": 6,
      "query": "bank"
    },
    "outputFields": [
      {
        "key": "categories[]category_id",
        "label": "Categories: Category ID"
      },
      {
        "key": "categories[]name",
        "label": "Categories: Name"
      },
      {
        "key": "count",
        "label": "Count",
        "type": "number"
      },
      {
        "key": "query",
        "label": "Query"
      }
    ],
    "trigger": {
      "label": "New Trustpilot Category Matching Search",
      "description": "Triggers when a new Trustpilot category matches your search. Each check runs Search Trustpilot Categories ($0.005 per request).",
      "inputFields": [
        {
          "key": "query",
          "label": "Search Query",
          "required": true,
          "type": "string",
          "helpText": "Keyword, e.g. bank or shop (max 200 characters)",
          "placeholder": "bank"
        }
      ],
      "sample": {
        "id": "bank",
        "category_id": "bank",
        "name": "Bank"
      },
      "outputFields": [
        {
          "key": "id",
          "label": "ID",
          "primary": true
        },
        {
          "key": "category_id",
          "label": "Category ID"
        },
        {
          "key": "name",
          "label": "Name"
        }
      ]
    }
  },
  {
    "key": "trustpilot_user",
    "path": "/v1/trustpilot/user",
    "method": "GET",
    "platform": "Trustpilot",
    "noun": "Review",
    "kind": "list",
    "listKey": "reviews",
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/trustpilot-user",
    "action": {
      "label": "Get Trustpilot User Reviews",
      "description": "Gets a Trustpilot reviewer's public profile and the reviews they have written across all companies, 20 per page. $0.005 per request after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "user_id",
        "label": "User ID",
        "required": true,
        "type": "string",
        "helpText": "Reviewer ID (24 hex characters), from a review's author_id on Company Reviews ([docs](https://apidirect.io/docs/trustpilot-company-reviews)). A trustpilot.com/users/... URL also works",
        "placeholder": "5724f5f50000ff000a1c0f61"
      },
      {
        "key": "page",
        "label": "Page Number",
        "required": false,
        "type": "integer",
        "default": "1",
        "helpText": "Page number, 1-500 (default: 1). Each page returns up to 20 reviews (1-500)."
      }
    ],
    "sample": {
      "user": {
        "user_id": "5724f5f50000ff000a1c0f61",
        "name": "Phillip Williams.",
        "country": "United Kingdom",
        "review_count": 134,
        "verified": true,
        "has_product_reviews": false,
        "likes": 136,
        "reads": 19656,
        "url": "https://www.trustpilot.com/users/5724f5f50000ff000a1c0f61"
      },
      "reviews": [
        {
          "review_id": "6a9ddb3f9185b6cc96d8b88f",
          "review_link": "https://www.trustpilot.com/reviews/6a9ddb3f9185b6cc96d8b88f",
          "rating": 1,
          "title": "Please just fix my landline.",
          "review_text": "Just had my broadband upgraded. Nice.\nUnfortunately my land line is now dead, mort, kapoot, silent, no more.\nWould you please arrange to fix it.\nI did try calling last friday, only to be told waiting…",
          "review_language": "en",
          "review_datetime_utc": "2026-09-06T23:29:35.000Z",
          "review_timestamp": 1788737375,
          "experience_date": "2026-09-06",
          "updated_datetime_utc": "2026-09-07T13:26:39.000Z",
          "is_verified": false,
          "verification_level": "not-verified",
          "like_count": 0,
          "company_name": "Utility Warehouse",
          "company_domain": "uw.co.uk",
          "company_url": "https://www.trustpilot.com/review/uw.co.uk",
          "business_unit_id": "48e8f676000064000503c337",
          "owner_response": {
            "text": "Hi Phillip,\n\nWe are very sorry to hear that your landline is non functional following your broadband upgrade and that you experienced such a long wait time when calling us.\n\nWe are unable to fix the …",
            "datetime_utc": "2026-09-07T07:02:13.000Z",
            "timestamp": 1788764533
          }
        },
        {
          "review_id": "6a9abe16910951bc588a6399",
          "review_link": "https://www.trustpilot.com/reviews/6a9abe16910951bc588a6399",
          "rating": 3,
          "title": "We had our broadband updated yesterday",
          "review_text": "We had our broadband updated yesterday, and I am pleased to say that my TV no longer buffers.\nUnfortunately we now have no landline phone.\nCould you please resolve this for us.\nI have just dialled 03…",
          "review_language": "en",
          "review_datetime_utc": "2026-09-04T14:48:22.000Z",
          "review_timestamp": 1788533302,
          "experience_date": "2026-09-04",
          "updated_datetime_utc": "2026-09-04T15:28:19.000Z",
          "is_verified": false,
          "verification_level": "not-verified",
          "like_count": 0,
          "company_name": "Utility Warehouse",
          "company_domain": "uw.co.uk",
          "company_url": "https://www.trustpilot.com/review/uw.co.uk",
          "business_unit_id": "48e8f676000064000503c337",
          "owner_response": {
            "text": "Hi Phillip,\n\nWe are so pleased to hear that your TV is no longer buffering following your broadband upgrade. However, we are very sorry to hear that your landline is currently not working and that yo…",
            "datetime_utc": "2026-09-04T15:02:44.000Z",
            "timestamp": 1788534164
          }
        }
      ],
      "count": 20,
      "page": 1,
      "total_pages": 7
    },
    "outputFields": [
      {
        "key": "user__user_id",
        "label": "User User ID"
      },
      {
        "key": "user__name",
        "label": "User Name"
      },
      {
        "key": "user__country",
        "label": "User Country"
      },
      {
        "key": "user__review_count",
        "label": "User Review Count",
        "type": "number"
      },
      {
        "key": "user__verified",
        "label": "User Verified",
        "type": "boolean"
      },
      {
        "key": "user__has_product_reviews",
        "label": "User Has Product Reviews",
        "type": "boolean"
      },
      {
        "key": "user__likes",
        "label": "User Likes",
        "type": "number"
      },
      {
        "key": "user__reads",
        "label": "User Reads",
        "type": "number"
      },
      {
        "key": "user__url",
        "label": "User URL"
      },
      {
        "key": "reviews[]review_id",
        "label": "Reviews: Review ID"
      },
      {
        "key": "reviews[]review_link",
        "label": "Reviews: Review Link"
      },
      {
        "key": "reviews[]rating",
        "label": "Reviews: Rating",
        "type": "number"
      },
      {
        "key": "reviews[]title",
        "label": "Reviews: Title"
      },
      {
        "key": "reviews[]review_text",
        "label": "Reviews: Review Text"
      },
      {
        "key": "reviews[]review_language",
        "label": "Reviews: Review Language"
      },
      {
        "key": "reviews[]review_datetime_utc",
        "label": "Reviews: Review Datetime UTC"
      },
      {
        "key": "reviews[]review_timestamp",
        "label": "Reviews: Review Timestamp",
        "type": "number"
      },
      {
        "key": "reviews[]experience_date",
        "label": "Reviews: Experience Date"
      },
      {
        "key": "reviews[]updated_datetime_utc",
        "label": "Reviews: Updated Datetime UTC"
      },
      {
        "key": "reviews[]is_verified",
        "label": "Reviews: Is Verified",
        "type": "boolean"
      },
      {
        "key": "reviews[]verification_level",
        "label": "Reviews: Verification Level"
      },
      {
        "key": "reviews[]like_count",
        "label": "Reviews: Like Count",
        "type": "number"
      },
      {
        "key": "reviews[]company_name",
        "label": "Reviews: Company Name"
      },
      {
        "key": "reviews[]company_domain",
        "label": "Reviews: Company Domain"
      },
      {
        "key": "reviews[]company_url",
        "label": "Reviews: Company URL"
      },
      {
        "key": "reviews[]business_unit_id",
        "label": "Reviews: Business Unit ID"
      },
      {
        "key": "reviews[]owner_response__text",
        "label": "Owner Response Text"
      },
      {
        "key": "reviews[]owner_response__datetime_utc",
        "label": "Owner Response Datetime UTC"
      },
      {
        "key": "reviews[]owner_response__timestamp",
        "label": "Owner Response Timestamp",
        "type": "number"
      },
      {
        "key": "count",
        "label": "Count",
        "type": "number"
      },
      {
        "key": "page",
        "label": "Page",
        "type": "number"
      },
      {
        "key": "total_pages",
        "label": "Total Pages",
        "type": "number"
      }
    ],
    "trigger": {
      "label": "New Trustpilot Review by User",
      "description": "Triggers when a Trustpilot user writes a new review. Each check runs Get Trustpilot User Reviews ($0.005 per request).",
      "inputFields": [
        {
          "key": "user_id",
          "label": "User ID",
          "required": true,
          "type": "string",
          "helpText": "Reviewer ID (24 hex characters), from a review's author_id on Company Reviews ([docs](https://apidirect.io/docs/trustpilot-company-reviews)). A trustpilot.com/users/... URL also works",
          "placeholder": "5724f5f50000ff000a1c0f61"
        },
        {
          "key": "page",
          "label": "Page Number",
          "required": false,
          "type": "integer",
          "default": "1",
          "helpText": "Page number, 1-500 (default: 1). Each page returns up to 20 reviews (1-500)."
        }
      ],
      "sample": {
        "id": "6a9ddb3f9185b6cc96d8b88f",
        "review_id": "6a9ddb3f9185b6cc96d8b88f",
        "review_link": "https://www.trustpilot.com/reviews/6a9ddb3f9185b6cc96d8b88f",
        "rating": 1,
        "title": "Please just fix my landline.",
        "review_text": "Just had my broadband upgraded. Nice.\nUnfortunately my land line is now dead, mort, kapoot, silent, no more.\nWould you please arrange to fix it.\nI did try calling last friday, only to be told waiting…",
        "review_language": "en",
        "review_datetime_utc": "2026-09-06T23:29:35.000Z",
        "review_timestamp": 1788737375,
        "experience_date": "2026-09-06",
        "updated_datetime_utc": "2026-09-07T13:26:39.000Z",
        "is_verified": false,
        "verification_level": "not-verified",
        "like_count": 0,
        "company_name": "Utility Warehouse",
        "company_domain": "uw.co.uk",
        "company_url": "https://www.trustpilot.com/review/uw.co.uk",
        "business_unit_id": "48e8f676000064000503c337",
        "owner_response": {
          "text": "Hi Phillip,\n\nWe are very sorry to hear that your landline is non functional following your broadband upgrade and that you experienced such a long wait time when calling us.\n\nWe are unable to fix the …",
          "datetime_utc": "2026-09-07T07:02:13.000Z",
          "timestamp": 1788764533
        }
      },
      "outputFields": [
        {
          "key": "id",
          "label": "ID",
          "primary": true
        },
        {
          "key": "review_id",
          "label": "Review ID"
        },
        {
          "key": "review_link",
          "label": "Review Link"
        },
        {
          "key": "rating",
          "label": "Rating",
          "type": "number"
        },
        {
          "key": "title",
          "label": "Title"
        },
        {
          "key": "review_text",
          "label": "Review Text"
        },
        {
          "key": "review_language",
          "label": "Review Language"
        },
        {
          "key": "review_datetime_utc",
          "label": "Review Datetime UTC"
        },
        {
          "key": "review_timestamp",
          "label": "Review Timestamp",
          "type": "number"
        },
        {
          "key": "experience_date",
          "label": "Experience Date"
        },
        {
          "key": "updated_datetime_utc",
          "label": "Updated Datetime UTC"
        },
        {
          "key": "is_verified",
          "label": "Is Verified",
          "type": "boolean"
        },
        {
          "key": "verification_level",
          "label": "Verification Level"
        },
        {
          "key": "like_count",
          "label": "Like Count",
          "type": "number"
        },
        {
          "key": "company_name",
          "label": "Company Name"
        },
        {
          "key": "company_domain",
          "label": "Company Domain"
        },
        {
          "key": "company_url",
          "label": "Company URL"
        },
        {
          "key": "business_unit_id",
          "label": "Business Unit ID"
        },
        {
          "key": "owner_response__text",
          "label": "Owner Response Text"
        },
        {
          "key": "owner_response__datetime_utc",
          "label": "Owner Response Datetime UTC"
        },
        {
          "key": "owner_response__timestamp",
          "label": "Owner Response Timestamp",
          "type": "number"
        }
      ]
    }
  }
];
