// Generated by scripts/generate.py from spec/openapi.json. Do not edit by hand;
// change the spec or the generator and run `npm run generate`.
module.exports = [
  {
    "key": "truthsocial_user_posts",
    "path": "/v1/truthsocial/user/posts",
    "method": "GET",
    "platform": "Truth Social",
    "noun": "Post",
    "kind": "list",
    "listKey": "posts",
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/truthsocial-user-posts",
    "action": {
      "label": "Get Truth Social User Posts",
      "description": "Gets a single Truth Social user's recent posts (their feed) by username. Returns post text, engagement metrics (replies, reposts, likes), media attachments (image, video and other Mastodon-style types), hashtags, language, visibility, reply status and a direct link to each post. Set get_sentiment=true to add AI emotion analysis (+$0.001/page). $0.006 per page after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "username",
        "label": "Username",
        "required": true,
        "type": "string",
        "helpText": "Truth Social username, with or without leading @ (max 100 characters)",
        "placeholder": "realDonaldTrump"
      },
      {
        "key": "pages",
        "label": "Pages to Fetch",
        "required": false,
        "type": "integer",
        "default": "1",
        "helpText": "Number of pages to fetch and merge into one response (1-20, billed per page). Each page returns up to 20 posts. Fetching stops early when there are no more results (1-20).",
        "placeholder": "2"
      },
      {
        "key": "get_sentiment",
        "label": "Add Sentiment Analysis",
        "required": false,
        "type": "boolean",
        "helpText": "Set to true to add AI emotion analysis to each post. Adds a `sentiment` object containing `emotions` (joy, trust, fear, surprise, sadness, disgust, anger and anticipation, each scored 0-100), `dominant_emotion`, `emotional_intensity` (0-10), and `polarity` (positive, negative or neutral). Any post that cannot be scored returns `sentiment: null`."
      }
    ],
    "sample": {
      "count": 40,
      "pages": 2,
      "username": "realDonaldTrump",
      "posts": [
        {
          "title": "@realDonaldTrump on Truth Social",
          "url": "https://truthsocial.com/@realDonaldTrump/117043133534824966",
          "date": "2026-08-05T13:28:05Z",
          "author": "realDonaldTrump",
          "source": "Truth Social",
          "domain": "truthsocial.com",
          "snippet": "Thank you for your attention to this matter! President DJT",
          "likes": 5514,
          "replies": 567,
          "reposts": 1399,
          "post_id": "117043133534824966",
          "content_html": "<p>Thank you for your attention to this matter! President DJT</p>",
          "media": [
            {
              "media_id": "117041192378469520",
              "type": "video",
              "url": "https://static-assets-1.truthsocial.com/media_attachments/files/117/041/192/original/9cbc020383d40cd5.mp4",
              "description": ""
            }
          ],
          "hashtags": [],
          "language": "en",
          "visibility": "public",
          "sensitive": false,
          "spoiler_text": "",
          "sponsored": false,
          "is_reply": false,
          "in_reply_to_id": ""
        }
      ]
    },
    "outputFields": [
      {
        "key": "count",
        "label": "Count",
        "type": "number"
      },
      {
        "key": "pages",
        "label": "Pages",
        "type": "number"
      },
      {
        "key": "username",
        "label": "Username"
      },
      {
        "key": "posts[]title",
        "label": "Posts: Title"
      },
      {
        "key": "posts[]url",
        "label": "Posts: URL"
      },
      {
        "key": "posts[]date",
        "label": "Posts: Date"
      },
      {
        "key": "posts[]author",
        "label": "Posts: Author"
      },
      {
        "key": "posts[]source",
        "label": "Posts: Source"
      },
      {
        "key": "posts[]domain",
        "label": "Posts: Domain"
      },
      {
        "key": "posts[]snippet",
        "label": "Posts: Snippet"
      },
      {
        "key": "posts[]likes",
        "label": "Posts: Likes",
        "type": "number"
      },
      {
        "key": "posts[]replies",
        "label": "Posts: Replies",
        "type": "number"
      },
      {
        "key": "posts[]reposts",
        "label": "Posts: Reposts",
        "type": "number"
      },
      {
        "key": "posts[]post_id",
        "label": "Posts: Post ID"
      },
      {
        "key": "posts[]content_html",
        "label": "Posts: Content HTML"
      },
      {
        "key": "posts[]media[]media_id",
        "label": "Media: Media ID"
      },
      {
        "key": "posts[]media[]type",
        "label": "Media: Type"
      },
      {
        "key": "posts[]media[]url",
        "label": "Media: URL"
      },
      {
        "key": "posts[]media[]description",
        "label": "Media: Description"
      },
      {
        "key": "posts[]hashtags",
        "label": "Posts: Hashtags",
        "list": true
      },
      {
        "key": "posts[]language",
        "label": "Posts: Language"
      },
      {
        "key": "posts[]visibility",
        "label": "Posts: Visibility"
      },
      {
        "key": "posts[]sensitive",
        "label": "Posts: Sensitive",
        "type": "boolean"
      },
      {
        "key": "posts[]spoiler_text",
        "label": "Posts: Spoiler Text"
      },
      {
        "key": "posts[]sponsored",
        "label": "Posts: Sponsored",
        "type": "boolean"
      },
      {
        "key": "posts[]is_reply",
        "label": "Posts: Is Reply",
        "type": "boolean"
      },
      {
        "key": "posts[]in_reply_to_id",
        "label": "Posts: In Reply To ID"
      }
    ],
    "trigger": {
      "label": "New Truth Social Post by User",
      "description": "Triggers when a Truth Social user publishes a new post. Each check runs Get Truth Social User Posts ($0.006 per page after the free tier (50 requests/month)).",
      "inputFields": [
        {
          "key": "username",
          "label": "Username",
          "required": true,
          "type": "string",
          "helpText": "Truth Social username, with or without leading @ (max 100 characters)",
          "placeholder": "realDonaldTrump"
        },
        {
          "key": "pages",
          "label": "Pages to Fetch",
          "required": false,
          "type": "integer",
          "default": "1",
          "helpText": "Number of pages to fetch and merge into one response (1-20, billed per page). Each page returns up to 20 posts. Fetching stops early when there are no more results (1-20). Every check of this trigger fetches this many pages, each billed as one request.",
          "placeholder": "2"
        },
        {
          "key": "get_sentiment",
          "label": "Add Sentiment Analysis",
          "required": false,
          "type": "boolean",
          "helpText": "Set to true to add AI emotion analysis to each post. Adds a `sentiment` object containing `emotions` (joy, trust, fear, surprise, sadness, disgust, anger and anticipation, each scored 0-100), `dominant_emotion`, `emotional_intensity` (0-10), and `polarity` (positive, negative or neutral). Any post that cannot be scored returns `sentiment: null`."
        }
      ],
      "sample": {
        "id": "117043133534824966",
        "title": "@realDonaldTrump on Truth Social",
        "url": "https://truthsocial.com/@realDonaldTrump/117043133534824966",
        "date": "2026-08-05T13:28:05Z",
        "author": "realDonaldTrump",
        "source": "Truth Social",
        "domain": "truthsocial.com",
        "snippet": "Thank you for your attention to this matter! President DJT",
        "likes": 5514,
        "replies": 567,
        "reposts": 1399,
        "post_id": "117043133534824966",
        "content_html": "<p>Thank you for your attention to this matter! President DJT</p>",
        "media": [
          {
            "media_id": "117041192378469520",
            "type": "video",
            "url": "https://static-assets-1.truthsocial.com/media_attachments/files/117/041/192/original/9cbc020383d40cd5.mp4",
            "description": ""
          }
        ],
        "hashtags": [],
        "language": "en",
        "visibility": "public",
        "sensitive": false,
        "spoiler_text": "",
        "sponsored": false,
        "is_reply": false,
        "in_reply_to_id": ""
      },
      "outputFields": [
        {
          "key": "id",
          "label": "ID",
          "primary": true
        },
        {
          "key": "title",
          "label": "Title"
        },
        {
          "key": "url",
          "label": "URL"
        },
        {
          "key": "date",
          "label": "Date"
        },
        {
          "key": "author",
          "label": "Author"
        },
        {
          "key": "source",
          "label": "Source"
        },
        {
          "key": "domain",
          "label": "Domain"
        },
        {
          "key": "snippet",
          "label": "Snippet"
        },
        {
          "key": "likes",
          "label": "Likes",
          "type": "number"
        },
        {
          "key": "replies",
          "label": "Replies",
          "type": "number"
        },
        {
          "key": "reposts",
          "label": "Reposts",
          "type": "number"
        },
        {
          "key": "post_id",
          "label": "Post ID"
        },
        {
          "key": "content_html",
          "label": "Content HTML"
        },
        {
          "key": "media[]media_id",
          "label": "Media: Media ID"
        },
        {
          "key": "media[]type",
          "label": "Media: Type"
        },
        {
          "key": "media[]url",
          "label": "Media: URL"
        },
        {
          "key": "media[]description",
          "label": "Media: Description"
        },
        {
          "key": "hashtags",
          "label": "Hashtags",
          "list": true
        },
        {
          "key": "language",
          "label": "Language"
        },
        {
          "key": "visibility",
          "label": "Visibility"
        },
        {
          "key": "sensitive",
          "label": "Sensitive",
          "type": "boolean"
        },
        {
          "key": "spoiler_text",
          "label": "Spoiler Text"
        },
        {
          "key": "sponsored",
          "label": "Sponsored",
          "type": "boolean"
        },
        {
          "key": "is_reply",
          "label": "Is Reply",
          "type": "boolean"
        },
        {
          "key": "in_reply_to_id",
          "label": "In Reply To ID"
        }
      ]
    }
  }
];
