// Generated by scripts/generate.py from spec/openapi.json. Do not edit by hand;
// change the spec or the generator and run `npm run generate`.
module.exports = [
  {
    "key": "youtube_posts",
    "path": "/v1/youtube/posts",
    "method": "GET",
    "platform": "YouTube",
    "noun": "Video",
    "kind": "list",
    "listKey": "posts",
    "idFields": [
      "video_id",
      "url"
    ],
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/youtube-videos",
    "action": {
      "label": "Search YouTube Videos",
      "description": "Searches for YouTube videos by keyword. Returns video title, URL, channel name, channel ID, video ID, publication date, description snippet, view count, video length, thumbnail, and a flag for live content. Supports filtering by upload date and fetching up to 20 pages in a single call. Set get_sentiment=true to add AI emotion analysis to each result. $0.005 per page after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "query",
        "label": "Search Query",
        "required": true,
        "type": "string",
        "helpText": "Search query (max 500 characters)",
        "placeholder": "tutorial"
      },
      {
        "key": "pages",
        "label": "Pages to Fetch",
        "required": false,
        "type": "integer",
        "default": "1",
        "helpText": "Number of pages to fetch and merge (1-20). Billed per page (1-20).",
        "placeholder": "2"
      },
      {
        "key": "upload_date",
        "label": "Uploaded Within",
        "required": false,
        "type": "string",
        "helpText": "Filter by upload date",
        "choices": {
          "last_hour": "Last Hour",
          "today": "Today",
          "this_week": "This Week",
          "this_month": "This Month",
          "this_year": "This Year"
        },
        "placeholder": "this_week"
      },
      {
        "key": "get_sentiment",
        "label": "Add Sentiment Analysis",
        "required": false,
        "type": "boolean",
        "helpText": "Set to true to add AI emotion analysis to each post. Adds a `sentiment` object containing `emotions` (joy, trust, fear, surprise, sadness, disgust, anger and anticipation, each scored 0-100), `dominant_emotion`, `emotional_intensity` (0-10), and `polarity` (positive, negative or neutral). Any post that cannot be scored returns `sentiment: null`."
      }
    ],
    "sample": {
      "count": 16,
      "pages": 1,
      "posts": [
        {
          "author": "YouFact Tech",
          "channel_id": "UCSWZxpzUTkriCZRe0Nl0UqA",
          "date": "2026-02-03T21:35:11Z",
          "domain": "youtube.com",
          "is_live": null,
          "keywords": [],
          "snippet": "We've gathered some truly wild gadgets, including a mirror that estimates your lifespan just by analyzing blood flow, a holographic ...",
          "source": "YouTube",
          "thumbnail": "https://i.ytimg.com/vi/fuiJ-3CdU3Q/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAev9WRIrRFlpYFnrcJt1FV-UFF7A",
          "title": "Coolest New Technologies of 2026",
          "type": "NORMAL",
          "url": "https://youtube.com/watch?v=fuiJ-3CdU3Q",
          "video_id": "fuiJ-3CdU3Q",
          "video_length": "18:07",
          "views": 301590
        },
        {
          "author": "TechZone",
          "channel_id": "UC6H07z6zAwbHRl4Lbl0GSsw",
          "date": "2025-04-04T21:35:11Z",
          "domain": "youtube.com",
          "is_live": null,
          "keywords": [],
          "snippet": "https://www.youtube.com/channel/UCMwqyIeElDirBZZwYmmeIYw ...",
          "source": "YouTube",
          "thumbnail": "https://i.ytimg.com/vi/dxWb1Vd9aq8/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDKtEblR7Wiw30NG-_uy0p-LejuMw",
          "title": "20 INVENTIONS THAT WILL CHANGE THE WORLD",
          "type": "NORMAL",
          "url": "https://youtube.com/watch?v=dxWb1Vd9aq8",
          "video_id": "dxWb1Vd9aq8",
          "video_length": "20:10",
          "views": 1370776
        },
        {
          "author": "Core Insights",
          "channel_id": "UCM8NnqS3-cqgUI1MLrZ8X4A",
          "date": "2026-03-26T21:35:11Z",
          "domain": "youtube.com",
          "is_live": null,
          "keywords": [],
          "snippet": "A company that started by selling smartphones, air fryers, and electric scooters just walked into the automotive world and ...",
          "source": "YouTube",
          "thumbnail": "https://i.ytimg.com/vi/-zLQWH2B1Po/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLA2rkwFfoa7XHOFWnnRDAAyQJIKGw",
          "title": "China's INSANE Technology Just Replaced Aluminum! XIAOMI CHASSIS 2026",
          "type": "NORMAL",
          "url": "https://youtube.com/watch?v=-zLQWH2B1Po",
          "video_id": "-zLQWH2B1Po",
          "video_length": "21:20",
          "views": 421111
        }
      ]
    },
    "outputFields": [
      {
        "key": "count",
        "label": "Count",
        "type": "number"
      },
      {
        "key": "pages",
        "label": "Pages",
        "type": "number"
      },
      {
        "key": "posts[]author",
        "label": "Posts: Author"
      },
      {
        "key": "posts[]channel_id",
        "label": "Posts: Channel ID"
      },
      {
        "key": "posts[]date",
        "label": "Posts: Date"
      },
      {
        "key": "posts[]domain",
        "label": "Posts: Domain"
      },
      {
        "key": "posts[]is_live",
        "label": "Posts: Is Live"
      },
      {
        "key": "posts[]keywords",
        "label": "Posts: Keywords",
        "list": true
      },
      {
        "key": "posts[]snippet",
        "label": "Posts: Snippet"
      },
      {
        "key": "posts[]source",
        "label": "Posts: Source"
      },
      {
        "key": "posts[]thumbnail",
        "label": "Posts: Thumbnail"
      },
      {
        "key": "posts[]title",
        "label": "Posts: Title"
      },
      {
        "key": "posts[]type",
        "label": "Posts: Type"
      },
      {
        "key": "posts[]url",
        "label": "Posts: URL"
      },
      {
        "key": "posts[]video_id",
        "label": "Posts: Video ID"
      },
      {
        "key": "posts[]video_length",
        "label": "Posts: Video Length"
      },
      {
        "key": "posts[]views",
        "label": "Posts: Views",
        "type": "number"
      }
    ],
    "trigger": {
      "label": "New YouTube Video Matching Search",
      "description": "Triggers when a new YouTube video matches your search. Each check runs Search YouTube Videos ($0.005 per page).",
      "inputFields": [
        {
          "key": "query",
          "label": "Search Query",
          "required": true,
          "type": "string",
          "helpText": "Search query (max 500 characters)",
          "placeholder": "tutorial"
        },
        {
          "key": "pages",
          "label": "Pages to Fetch",
          "required": false,
          "type": "integer",
          "default": "1",
          "helpText": "Number of pages to fetch and merge (1-20). Billed per page (1-20). Every check of this trigger fetches this many pages, each billed as one request.",
          "placeholder": "2"
        },
        {
          "key": "upload_date",
          "label": "Uploaded Within",
          "required": false,
          "type": "string",
          "helpText": "Filter by upload date",
          "choices": {
            "last_hour": "Last Hour",
            "today": "Today",
            "this_week": "This Week",
            "this_month": "This Month",
            "this_year": "This Year"
          },
          "placeholder": "this_week"
        },
        {
          "key": "get_sentiment",
          "label": "Add Sentiment Analysis",
          "required": false,
          "type": "boolean",
          "helpText": "Set to true to add AI emotion analysis to each post. Adds a `sentiment` object containing `emotions` (joy, trust, fear, surprise, sadness, disgust, anger and anticipation, each scored 0-100), `dominant_emotion`, `emotional_intensity` (0-10), and `polarity` (positive, negative or neutral). Any post that cannot be scored returns `sentiment: null`."
        }
      ],
      "sample": {
        "id": "fuiJ-3CdU3Q",
        "author": "YouFact Tech",
        "channel_id": "UCSWZxpzUTkriCZRe0Nl0UqA",
        "date": "2026-02-03T21:35:11Z",
        "domain": "youtube.com",
        "is_live": null,
        "keywords": [],
        "snippet": "We've gathered some truly wild gadgets, including a mirror that estimates your lifespan just by analyzing blood flow, a holographic ...",
        "source": "YouTube",
        "thumbnail": "https://i.ytimg.com/vi/fuiJ-3CdU3Q/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAev9WRIrRFlpYFnrcJt1FV-UFF7A",
        "title": "Coolest New Technologies of 2026",
        "type": "NORMAL",
        "url": "https://youtube.com/watch?v=fuiJ-3CdU3Q",
        "video_id": "fuiJ-3CdU3Q",
        "video_length": "18:07",
        "views": 301590
      },
      "outputFields": [
        {
          "key": "id",
          "label": "ID",
          "primary": true
        },
        {
          "key": "author",
          "label": "Author"
        },
        {
          "key": "channel_id",
          "label": "Channel ID"
        },
        {
          "key": "date",
          "label": "Date"
        },
        {
          "key": "domain",
          "label": "Domain"
        },
        {
          "key": "is_live",
          "label": "Is Live"
        },
        {
          "key": "keywords",
          "label": "Keywords",
          "list": true
        },
        {
          "key": "snippet",
          "label": "Snippet"
        },
        {
          "key": "source",
          "label": "Source"
        },
        {
          "key": "thumbnail",
          "label": "Thumbnail"
        },
        {
          "key": "title",
          "label": "Title"
        },
        {
          "key": "type",
          "label": "Type"
        },
        {
          "key": "url",
          "label": "URL"
        },
        {
          "key": "video_id",
          "label": "Video ID"
        },
        {
          "key": "video_length",
          "label": "Video Length"
        },
        {
          "key": "views",
          "label": "Views",
          "type": "number"
        }
      ]
    }
  },
  {
    "key": "youtube_channels",
    "path": "/v1/youtube/channels",
    "method": "GET",
    "platform": "YouTube",
    "noun": "Channel",
    "kind": "list",
    "listKey": "channels",
    "idFields": [
      "channel_id",
      "url"
    ],
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/youtube-channels",
    "action": {
      "label": "Search YouTube Channels",
      "description": "Searches for YouTube channels by keyword. Returns channel ID, channel name, description, subscriber count (formatted like \"1.14K\" or \"6.44M\"), thumbnail URL, and channel link. Supports fetching up to 20 pages in a single call. $0.005 per page after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "query",
        "label": "Search Query",
        "required": true,
        "type": "string",
        "helpText": "Search query (max 500 characters)",
        "placeholder": "AI"
      },
      {
        "key": "pages",
        "label": "Pages to Fetch",
        "required": false,
        "type": "integer",
        "default": "1",
        "helpText": "Number of pages to fetch and merge (1-20). Billed per page (1-20).",
        "placeholder": "1"
      }
    ],
    "sample": {
      "channels": [
        {
          "channel_id": "UCy0tKL1T7wFoYcxCe0xjN6Q",
          "description": "",
          "subscriber_count": "3.1M",
          "thumbnail": "https://yt3.googleusercontent.com/ytc/AIdro_lG8iUz4mpHBrzJSDYEKT0qe2XmhZUUUzhzcJbz9cE3rQ=s176-c-k-c0x00ffffff-no-rj-mo",
          "title": "Technology Connections",
          "url": "https://youtube.com/channel/UCy0tKL1T7wFoYcxCe0xjN6Q"
        },
        {
          "channel_id": "UCXuqSBlHAE6Xw-yeJA0Tunw",
          "description": "Linus Tech Tips is a passionate team of \"professionally curious\" experts in consumer technology and video production who aim to ...",
          "subscriber_count": "16.8M",
          "thumbnail": "https://yt3.ggpht.com/gnvYLhXy8FAlPXZ2RTrkrgj-5kyt0vdE2FUGVOiKGdEZIa-wN5A-7nwZBlWJLzUMmoh1NWAU=s176-c-k-c0x00ffffff-no-rj-mo",
          "title": "Linus Tech Tips",
          "url": "https://youtube.com/channel/UCXuqSBlHAE6Xw-yeJA0Tunw"
        },
        {
          "channel_id": "UCAL3JXZSzSm8AlZyD3nQdBA",
          "description": "Primitive technology is a hobby where you build things in the wild completely from scratch using no modern tools or materials.",
          "subscriber_count": "11M",
          "thumbnail": "https://yt3.googleusercontent.com/ytc/AIdro_kltmVPbr5yKSJ8YaCv8ouXktPx-11IkO5dcmqN-dFmug=s176-c-k-c0x00ffffff-no-rj-mo",
          "title": "Primitive Technology",
          "url": "https://youtube.com/channel/UCAL3JXZSzSm8AlZyD3nQdBA"
        }
      ],
      "count": 20,
      "pages": 1
    },
    "outputFields": [
      {
        "key": "channels[]channel_id",
        "label": "Channels: Channel ID"
      },
      {
        "key": "channels[]description",
        "label": "Channels: Description"
      },
      {
        "key": "channels[]subscriber_count",
        "label": "Channels: Subscriber Count"
      },
      {
        "key": "channels[]thumbnail",
        "label": "Channels: Thumbnail"
      },
      {
        "key": "channels[]title",
        "label": "Channels: Title"
      },
      {
        "key": "channels[]url",
        "label": "Channels: URL"
      },
      {
        "key": "count",
        "label": "Count",
        "type": "number"
      },
      {
        "key": "pages",
        "label": "Pages",
        "type": "number"
      }
    ],
    "trigger": {
      "label": "New YouTube Channel Matching Search",
      "description": "Triggers when a new YouTube channel matches your search. Each check runs Search YouTube Channels ($0.005 per page).",
      "inputFields": [
        {
          "key": "query",
          "label": "Search Query",
          "required": true,
          "type": "string",
          "helpText": "Search query (max 500 characters)",
          "placeholder": "AI"
        },
        {
          "key": "pages",
          "label": "Pages to Fetch",
          "required": false,
          "type": "integer",
          "default": "1",
          "helpText": "Number of pages to fetch and merge (1-20). Billed per page (1-20). Every check of this trigger fetches this many pages, each billed as one request.",
          "placeholder": "1"
        }
      ],
      "sample": {
        "id": "UCy0tKL1T7wFoYcxCe0xjN6Q",
        "channel_id": "UCy0tKL1T7wFoYcxCe0xjN6Q",
        "description": "",
        "subscriber_count": "3.1M",
        "thumbnail": "https://yt3.googleusercontent.com/ytc/AIdro_lG8iUz4mpHBrzJSDYEKT0qe2XmhZUUUzhzcJbz9cE3rQ=s176-c-k-c0x00ffffff-no-rj-mo",
        "title": "Technology Connections",
        "url": "https://youtube.com/channel/UCy0tKL1T7wFoYcxCe0xjN6Q"
      },
      "outputFields": [
        {
          "key": "id",
          "label": "ID",
          "primary": true
        },
        {
          "key": "channel_id",
          "label": "Channel ID"
        },
        {
          "key": "description",
          "label": "Description"
        },
        {
          "key": "subscriber_count",
          "label": "Subscriber Count"
        },
        {
          "key": "thumbnail",
          "label": "Thumbnail"
        },
        {
          "key": "title",
          "label": "Title"
        },
        {
          "key": "url",
          "label": "URL"
        }
      ]
    }
  },
  {
    "key": "youtube_channel",
    "path": "/v1/youtube/channel",
    "method": "GET",
    "platform": "YouTube",
    "noun": "Channel",
    "kind": "detail",
    "listKey": null,
    "idFields": null,
    "unwrapKey": "channel",
    "docs": "https://apidirect.io/docs/youtube-channel-details",
    "action": {
      "label": "Find YouTube Channel",
      "description": "Gets detailed information about a YouTube channel by channel ID, URL, or name/handle. Returns the channel name, description, subscriber count, video count, exact total view count, country, creation date, verification status, external links, profile picture, and banner. Provide exactly one of id, url, or name. $0.005 per request after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "id",
        "label": "ID",
        "required": false,
        "type": "string",
        "helpText": "YouTube channel ID (24 characters, starts with UC), e.g. UCXuqSBlHAE6Xw-yeJA0Tunw",
        "placeholder": "UCXuqSBlHAE6Xw-yeJA0Tunw"
      },
      {
        "key": "url",
        "label": "URL",
        "required": false,
        "type": "string",
        "helpText": "Channel URL, used instead of id: youtube.com/channel/..., youtube.com/@handle, /c/ or /user/ forms (up to 500 characters).",
        "placeholder": "https://www.youtube.com/@mkbhd"
      },
      {
        "key": "name",
        "label": "Name",
        "required": false,
        "type": "string",
        "helpText": "Channel name or @handle, used instead of id (e.g. @mkbhd or Linus Tech Tips) (up to 500 characters).",
        "placeholder": "Linus Tech Tips"
      }
    ],
    "sample": {
      "channel_id": "UCXuqSBlHAE6Xw-yeJA0Tunw",
      "channel_name": "Linus Tech Tips",
      "description": "Linus Tech Tips is a passionate team of \"professionally curious\" experts in consumer technology and video production who aim to educate and entertain.",
      "subscriber_count": "16.9M",
      "video_count": "7.8K",
      "view_count": 9633982641,
      "country": "Canada",
      "creation_date": "2008-11-25",
      "verified": true,
      "has_business_email": true,
      "links": [
        {
          "name": "lttstore.com",
          "url": "https://lttstore.com"
        },
        {
          "name": "Twitter",
          "url": "https://twitter.com/LinusTech"
        }
      ],
      "profile_pic_url": "https://yt3.googleusercontent.com/.../photo.jpg",
      "banner": "https://yt3.googleusercontent.com/.../banner.jpg",
      "url": "https://youtube.com/channel/UCXuqSBlHAE6Xw-yeJA0Tunw"
    },
    "outputFields": [
      {
        "key": "channel_id",
        "label": "Channel ID"
      },
      {
        "key": "channel_name",
        "label": "Channel Name"
      },
      {
        "key": "description",
        "label": "Description"
      },
      {
        "key": "subscriber_count",
        "label": "Subscriber Count"
      },
      {
        "key": "video_count",
        "label": "Video Count"
      },
      {
        "key": "view_count",
        "label": "View Count",
        "type": "number"
      },
      {
        "key": "country",
        "label": "Country"
      },
      {
        "key": "creation_date",
        "label": "Creation Date"
      },
      {
        "key": "verified",
        "label": "Verified",
        "type": "boolean"
      },
      {
        "key": "has_business_email",
        "label": "Has Business Email",
        "type": "boolean"
      },
      {
        "key": "links[]name",
        "label": "Links: Name"
      },
      {
        "key": "links[]url",
        "label": "Links: URL"
      },
      {
        "key": "profile_pic_url",
        "label": "Profile Pic URL"
      },
      {
        "key": "banner",
        "label": "Banner"
      },
      {
        "key": "url",
        "label": "URL"
      }
    ],
    "trigger": null
  },
  {
    "key": "youtube_video",
    "path": "/v1/youtube/video",
    "method": "GET",
    "platform": "YouTube",
    "noun": "Video",
    "kind": "detail",
    "listKey": null,
    "idFields": null,
    "unwrapKey": "video",
    "docs": "https://apidirect.io/docs/youtube-video-details",
    "action": {
      "label": "Find YouTube Video",
      "description": "Gets detailed information about a YouTube video by URL or video ID. Returns the title, full description, channel name and ID, publish date, duration in seconds, view count, category, keywords, and thumbnail. Works for regular videos, Shorts, and live streams. $0.005 per request after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "url",
        "label": "URL",
        "required": true,
        "type": "string",
        "helpText": "YouTube video URL (watch?v=, youtu.be/, /shorts/, /embed/, /live/ or /v/ forms) or 11-character video ID",
        "placeholder": "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
      }
    ],
    "sample": {
      "video_id": "dQw4w9WgXcQ",
      "url": "https://youtube.com/watch?v=dQw4w9WgXcQ",
      "title": "Rick Astley - Never Gonna Give You Up (Official Video) (4K Remaster)",
      "description": "The official video for “Never Gonna Give You Up” by Rick Astley...",
      "author": "Rick Astley",
      "channel_id": "UCuAXFkgsw1L7xaCfnd5JJOw",
      "date": "2009-10-25T06:57:33Z",
      "duration": 213,
      "views": 1788679598,
      "category": "Music",
      "type": "NORMAL",
      "is_live": false,
      "keywords": [
        "rick astley",
        "Never Gonna Give You Up",
        "rick roll"
      ],
      "thumbnail": "https://i.ytimg.com/vi_webp/dQw4w9WgXcQ/maxresdefault.webp"
    },
    "outputFields": [
      {
        "key": "video_id",
        "label": "Video ID"
      },
      {
        "key": "url",
        "label": "URL"
      },
      {
        "key": "title",
        "label": "Title"
      },
      {
        "key": "description",
        "label": "Description"
      },
      {
        "key": "author",
        "label": "Author"
      },
      {
        "key": "channel_id",
        "label": "Channel ID"
      },
      {
        "key": "date",
        "label": "Date"
      },
      {
        "key": "duration",
        "label": "Duration",
        "type": "number"
      },
      {
        "key": "views",
        "label": "Views",
        "type": "number"
      },
      {
        "key": "category",
        "label": "Category"
      },
      {
        "key": "type",
        "label": "Type"
      },
      {
        "key": "is_live",
        "label": "Is Live",
        "type": "boolean"
      },
      {
        "key": "keywords",
        "label": "Keywords",
        "list": true
      },
      {
        "key": "thumbnail",
        "label": "Thumbnail"
      }
    ],
    "trigger": null
  },
  {
    "key": "youtube_comments",
    "path": "/v1/youtube/comments",
    "method": "GET",
    "platform": "YouTube",
    "noun": "Comment",
    "kind": "list",
    "listKey": "comments",
    "idFields": [
      "comment_id",
      "url"
    ],
    "unwrapKey": null,
    "docs": "https://apidirect.io/docs/youtube-comments",
    "action": {
      "label": "Get YouTube Video Comments",
      "description": "Gets comments (comment threads) from a YouTube video. Returns each comment's text, author, author channel, like count, reply count, publication date, last-updated date, a direct link, and preview replies. Supports sorting by most recent or relevance, and fetching up to 20 pages in a single call. $0.005 per page after the free tier (50 requests/month)."
    },
    "inputFields": [
      {
        "key": "url",
        "label": "URL",
        "required": true,
        "type": "string",
        "helpText": "YouTube video URL (watch?v=, youtu.be/, /shorts/, /embed/, /live/ or /v/ forms) or 11-character video ID",
        "placeholder": "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
      },
      {
        "key": "pages",
        "label": "Pages to Fetch",
        "required": false,
        "type": "integer",
        "default": "1",
        "helpText": "Number of pages to fetch and merge (1-20). Each page returns up to ~100 comments. Billed per page (1-20).",
        "placeholder": "1"
      },
      {
        "key": "sort_by",
        "label": "Sort By",
        "required": false,
        "type": "string",
        "default": "relevance",
        "helpText": "Sort order",
        "choices": {
          "most_recent": "Most Recent",
          "relevance": "Relevance"
        },
        "placeholder": "relevance"
      }
    ],
    "sample": {
      "comments": [
        {
          "comment_id": "Ugzge340dBgB75hWBm54AaABAg",
          "text": "can confirm: he never gave us up",
          "author": "@YouTube",
          "author_channel_id": "UCBR8-60-B28hp2BmDPdntcQ",
          "author_channel_url": "http://www.youtube.com/@YouTube",
          "author_thumbnail": "https://yt3.ggpht.com/.../photo.jpg",
          "likes": 261929,
          "reply_count": 1000,
          "date": "2025-04-22T19:05:08Z",
          "updated_date": "2025-04-22T19:05:08Z",
          "url": "https://youtube.com/watch?v=dQw4w9WgXcQ&lc=Ugzge340dBgB75hWBm54AaABAg",
          "video_id": "dQw4w9WgXcQ",
          "channel_id": "UCuAXFkgsw1L7xaCfnd5JJOw",
          "source": "YouTube",
          "domain": "youtube.com",
          "replies": [
            {
              "comment_id": "Ugzge340dBgB75hWBm54AaABAg.AHE8_QAWJx9AHE9eIiztxR",
              "text": "YOUTUBE AND ONE LIKE WOOHAAAAH",
              "author": "@linganguliguliwatcha",
              "author_channel_id": "UCjFRISlX-LPxiqViJAE3h6Q",
              "author_channel_url": "http://www.youtube.com/@linganguliguliwatcha",
              "author_thumbnail": "https://yt3.ggpht.com/.../photo.jpg",
              "likes": 7026,
              "date": "2025-04-22T19:14:32Z",
              "url": "https://youtube.com/watch?v=dQw4w9WgXcQ&lc=Ugzge340dBgB75hWBm54AaABAg.AHE8_QAWJx9AHE9eIiztxR",
              "video_id": "dQw4w9WgXcQ"
            }
          ]
        }
      ],
      "pages": 1,
      "count": 100
    },
    "outputFields": [
      {
        "key": "comments[]comment_id",
        "label": "Comments: Comment ID"
      },
      {
        "key": "comments[]text",
        "label": "Comments: Text"
      },
      {
        "key": "comments[]author",
        "label": "Comments: Author"
      },
      {
        "key": "comments[]author_channel_id",
        "label": "Comments: Author Channel ID"
      },
      {
        "key": "comments[]author_channel_url",
        "label": "Comments: Author Channel URL"
      },
      {
        "key": "comments[]author_thumbnail",
        "label": "Comments: Author Thumbnail"
      },
      {
        "key": "comments[]likes",
        "label": "Comments: Likes",
        "type": "number"
      },
      {
        "key": "comments[]reply_count",
        "label": "Comments: Reply Count",
        "type": "number"
      },
      {
        "key": "comments[]date",
        "label": "Comments: Date"
      },
      {
        "key": "comments[]updated_date",
        "label": "Comments: Updated Date"
      },
      {
        "key": "comments[]url",
        "label": "Comments: URL"
      },
      {
        "key": "comments[]video_id",
        "label": "Comments: Video ID"
      },
      {
        "key": "comments[]channel_id",
        "label": "Comments: Channel ID"
      },
      {
        "key": "comments[]source",
        "label": "Comments: Source"
      },
      {
        "key": "comments[]domain",
        "label": "Comments: Domain"
      },
      {
        "key": "comments[]replies[]comment_id",
        "label": "Replies: Comment ID"
      },
      {
        "key": "comments[]replies[]text",
        "label": "Replies: Text"
      },
      {
        "key": "comments[]replies[]author",
        "label": "Replies: Author"
      },
      {
        "key": "comments[]replies[]author_channel_id",
        "label": "Replies: Author Channel ID"
      },
      {
        "key": "comments[]replies[]author_channel_url",
        "label": "Replies: Author Channel URL"
      },
      {
        "key": "comments[]replies[]author_thumbnail",
        "label": "Replies: Author Thumbnail"
      },
      {
        "key": "comments[]replies[]likes",
        "label": "Replies: Likes",
        "type": "number"
      },
      {
        "key": "comments[]replies[]date",
        "label": "Replies: Date"
      },
      {
        "key": "comments[]replies[]url",
        "label": "Replies: URL"
      },
      {
        "key": "comments[]replies[]video_id",
        "label": "Replies: Video ID"
      },
      {
        "key": "pages",
        "label": "Pages",
        "type": "number"
      },
      {
        "key": "count",
        "label": "Count",
        "type": "number"
      }
    ],
    "trigger": {
      "label": "New YouTube Video Comment",
      "description": "Triggers when a YouTube video gets a new comment. Each check runs Get YouTube Video Comments ($0.005 per page).",
      "inputFields": [
        {
          "key": "url",
          "label": "URL",
          "required": true,
          "type": "string",
          "helpText": "YouTube video URL (watch?v=, youtu.be/, /shorts/, /embed/, /live/ or /v/ forms) or 11-character video ID",
          "placeholder": "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
        },
        {
          "key": "pages",
          "label": "Pages to Fetch",
          "required": false,
          "type": "integer",
          "default": "1",
          "helpText": "Number of pages to fetch and merge (1-20). Each page returns up to ~100 comments. Billed per page (1-20). Every check of this trigger fetches this many pages, each billed as one request.",
          "placeholder": "1"
        },
        {
          "key": "sort_by",
          "label": "Sort By",
          "required": false,
          "type": "string",
          "default": "most_recent",
          "helpText": "Sort order",
          "choices": {
            "most_recent": "Most Recent",
            "relevance": "Relevance"
          },
          "placeholder": "relevance"
        }
      ],
      "sample": {
        "id": "Ugzge340dBgB75hWBm54AaABAg",
        "comment_id": "Ugzge340dBgB75hWBm54AaABAg",
        "text": "can confirm: he never gave us up",
        "author": "@YouTube",
        "author_channel_id": "UCBR8-60-B28hp2BmDPdntcQ",
        "author_channel_url": "http://www.youtube.com/@YouTube",
        "author_thumbnail": "https://yt3.ggpht.com/.../photo.jpg",
        "likes": 261929,
        "reply_count": 1000,
        "date": "2025-04-22T19:05:08Z",
        "updated_date": "2025-04-22T19:05:08Z",
        "url": "https://youtube.com/watch?v=dQw4w9WgXcQ&lc=Ugzge340dBgB75hWBm54AaABAg",
        "video_id": "dQw4w9WgXcQ",
        "channel_id": "UCuAXFkgsw1L7xaCfnd5JJOw",
        "source": "YouTube",
        "domain": "youtube.com",
        "replies": [
          {
            "comment_id": "Ugzge340dBgB75hWBm54AaABAg.AHE8_QAWJx9AHE9eIiztxR",
            "text": "YOUTUBE AND ONE LIKE WOOHAAAAH",
            "author": "@linganguliguliwatcha",
            "author_channel_id": "UCjFRISlX-LPxiqViJAE3h6Q",
            "author_channel_url": "http://www.youtube.com/@linganguliguliwatcha",
            "author_thumbnail": "https://yt3.ggpht.com/.../photo.jpg",
            "likes": 7026,
            "date": "2025-04-22T19:14:32Z",
            "url": "https://youtube.com/watch?v=dQw4w9WgXcQ&lc=Ugzge340dBgB75hWBm54AaABAg.AHE8_QAWJx9AHE9eIiztxR",
            "video_id": "dQw4w9WgXcQ"
          }
        ]
      },
      "outputFields": [
        {
          "key": "id",
          "label": "ID",
          "primary": true
        },
        {
          "key": "comment_id",
          "label": "Comment ID"
        },
        {
          "key": "text",
          "label": "Text"
        },
        {
          "key": "author",
          "label": "Author"
        },
        {
          "key": "author_channel_id",
          "label": "Author Channel ID"
        },
        {
          "key": "author_channel_url",
          "label": "Author Channel URL"
        },
        {
          "key": "author_thumbnail",
          "label": "Author Thumbnail"
        },
        {
          "key": "likes",
          "label": "Likes",
          "type": "number"
        },
        {
          "key": "reply_count",
          "label": "Reply Count",
          "type": "number"
        },
        {
          "key": "date",
          "label": "Date"
        },
        {
          "key": "updated_date",
          "label": "Updated Date"
        },
        {
          "key": "url",
          "label": "URL"
        },
        {
          "key": "video_id",
          "label": "Video ID"
        },
        {
          "key": "channel_id",
          "label": "Channel ID"
        },
        {
          "key": "source",
          "label": "Source"
        },
        {
          "key": "domain",
          "label": "Domain"
        },
        {
          "key": "replies[]comment_id",
          "label": "Replies: Comment ID"
        },
        {
          "key": "replies[]text",
          "label": "Replies: Text"
        },
        {
          "key": "replies[]author",
          "label": "Replies: Author"
        },
        {
          "key": "replies[]author_channel_id",
          "label": "Replies: Author Channel ID"
        },
        {
          "key": "replies[]author_channel_url",
          "label": "Replies: Author Channel URL"
        },
        {
          "key": "replies[]author_thumbnail",
          "label": "Replies: Author Thumbnail"
        },
        {
          "key": "replies[]likes",
          "label": "Replies: Likes",
          "type": "number"
        },
        {
          "key": "replies[]date",
          "label": "Replies: Date"
        },
        {
          "key": "replies[]url",
          "label": "Replies: URL"
        },
        {
          "key": "replies[]video_id",
          "label": "Replies: Video ID"
        }
      ]
    }
  }
];
